import type { MapPillar } from './overwatch-maps'

export const CONTROL_MAP_PILLARS: MapPillar[] = [
  {
    slug: 'antarctic-peninsula',
    name: 'Antarctic Peninsula',
    mode: 'Control',
    location: 'Antártida',
    image: '/maps/antarctic-peninsula.png',
    imageAlt: 'Instalación científica y formaciones de hielo de Antarctic Peninsula en Overwatch',
    seoTitle: 'Antarctic Peninsula: guía de Drilling Rig, Icebreaker y Anomaly',
    seoDescription: 'Guía actualizada de Antarctic Peninsula en Overwatch: rutas y planes para Drilling Rig, Icebreaker y Anomaly, héroes, composiciones y revisión de VOD.',
    updatedAtIso: '2026-07-19',
    updatedAt: '19 de julio de 2026',
    intro: [
      'Antarctic Peninsula dejó de ser aquel mapa en el que uno podía perderse entre pasillos blancos y llegar tarde a una pelea que ya había terminado. Su versión actual conserva el ambiente de expedición helada, pero ordena mejor las rutas de Drilling Rig, Icebreaker y Anomaly. Sigue siendo un mapa con muchos accesos, solo que ahora resulta más fácil entender adónde conduce cada uno y qué espacio estás intentando ganar.',
      'Aquí las rondas rara vez se deciden por quedarse plantado en el objetivo. Drilling Rig obliga a vigilar la altura que rodea el punto; Icebreaker premia a quien usa el barco como cobertura y cambia de lado a tiempo; Anomaly mezcla un interior estrecho con un borde exterior que puede convertirse en una trampa. Antes de entrar, mira dónde está tu backline y decide por qué puerta va a jugar el equipo. Esa pequeña pausa evita más derrotas que cualquier flanco brillante improvisado.',
    ],
    quickRead: [
      { title: 'No alargues los flancos', body: 'Si doblas dos esquinas, tus supports dejarán de verte. Usa los pasillos para abrir un ángulo corto y vuelve al equipo en cuanto el rival abandone la posición.' },
      { title: 'Limpia la entrada antes de tocar', body: 'El punto está expuesto desde varios lados. Desaloja primero la altura o la esquina más peligrosa y entra cuando tu Tank pueda recibir ayuda.' },
      { title: 'Juega lejos del borde', body: 'En Anomaly hay peleas que se pierden por colocarse junto al vacío sin necesidad. La pared interior ofrece casi la misma visión y te protege de los empujes.' },
    ],
    phases: [
      {
        name: 'Drilling Rig',
        attack: 'La entrada más directa desemboca en una zona donde es fácil recibir daño desde arriba y desde el lateral al mismo tiempo. No hace falta organizar una expedición por medio mapa: basta con que el Tank cruce hacia una cobertura, un DPS enseñe el segundo ángulo y ambos grupos puedan verse. Si consigues echar al rival de la plataforma que domina el punto, la captura suele llegar sola. Si saltas al objetivo sin mirar esa posición, pasarás la pelea girando la cámara.',
        defense: 'Con el punto capturado, juega un poco por delante y utiliza las puertas como aviso temprano. La defensa cómoda es la que puede molestar una entrada y retroceder sin gastar todas sus habilidades. Evita bajar los cinco al objetivo para rematar a alguien: un rival que escapa por fuera no importa tanto como el grupo que está entrando por la otra puerta. Conserva una posición elevada o un ángulo lateral para que la siguiente pelea no empiece desde el suelo.',
        vodReview: 'Detén la repetición al abrirse el punto. Comprueba quién podía disputar la altura, quién veía al Tank y si el primer jugador que cayó tenía una cobertura a menos de dos pasos.',
      },
      {
        name: 'Icebreaker',
        attack: 'El barco da refugio, pero también corta líneas de curación con una facilidad desesperante. Avanza por el lado que permita a tus supports seguir viendo la pelea y usa el interior para cruzar, no para quedarte librando un duelo eterno. Cuando el rival acumula gente en una entrada, cambiar al otro costado es mejor que insistir durante treinta segundos. Hazlo juntos: una rotación de cinco tarda poco; cinco rutas distintas no son una rotación.',
        defense: 'No esperes literalmente sobre el círculo. Las esquinas del barco permiten forzar movilidad y regresar al punto con recursos. Si un héroe de flanco entra por dentro, una persona puede marcarlo mientras el resto mantiene la puerta principal; enviar a tres jugadores detrás de él abre el objetivo. Cuando tengas que ceder, cruza al lado opuesto con tiempo. Morir en el pasillo del barco deja a tu equipo sin una segunda pelea limpia.',
        vodReview: 'Fíjate en cuántas veces una pared del barco cortó la curación. Si la respuesta es varias, el problema seguramente fue la ruta elegida o el momento de cruzar, no la cantidad de healing.',
      },
      {
        name: 'Anomaly',
        attack: 'Anomaly invita a entrar rápido porque el objetivo parece estar a mano, pero la primera puerta suele concentrar demasiado daño. Asoma, fuerza una habilidad defensiva y decide si cruzas por dentro o rodeas por el exterior. La ruta exterior funciona para abrir la mirada rival, no para mandar solo a un compañero junto al precipicio. Una vez dentro, ocupa las esquinas alrededor del punto; cinco jugadores dentro del círculo ofrecen un blanco demasiado sencillo.',
        defense: 'Defiende la puerta que el rival necesita, pero deja libre tu retirada. Los héroes con empuje pueden amenazar el exterior sin exponerse ellos mismos, mientras que los de rango medio funcionan mejor desde la pared interior. Si el ataque gasta varias definitivas para entrar, no respondas con todo por orgullo. Cede, sobrevive y prepara la recuperación: las rutas son cortas y permiten volver con el equipo completo.',
        vodReview: 'Revisa cada caída ambiental y cada muerte en una puerta. Pregúntate si estabas allí por una razón concreta o simplemente seguiste al primer compañero que avanzó.',
      },
    ],
    attackPlan: [
      { title: 'Mira antes de elegir puerta', body: 'Localiza al Tank rival y a sus supports. En Antarctic, diez metros de pasillo pueden ocultar a media composición y cambiar qué entrada es segura.' },
      { title: 'Abre un ángulo corto', body: 'Un DPS lateral no necesita desaparecer. Basta con colocarse donde obligue al rival a girarse mientras sigue a distancia de ayuda.' },
      { title: 'Cruza después del cooldown', body: 'Fuerza primero el cooldown que puede frenar la entrada. Cuando desaparezca, avanza de verdad; no gastes movilidad solo para asomarte.' },
      { title: 'Quédate con el espacio', body: 'Si ganas una baja, ocupa la altura o la puerta importante. Perseguir por los corredores suele regalar justo el terreno que acababas de conquistar.' },
    ],
    defensePlan: [
      { title: 'Recibe fuera del círculo', body: 'Presiona desde una cobertura adelantada y vuelve al punto cuando sea necesario. Esperar dentro permite que el rival elija todas las distancias.' },
      { title: 'Reparte la atención', body: 'Una persona vigila el lateral y el resto sostiene la entrada principal. Comunicar un flanco no significa abandonar la pelea para perseguirlo.' },
      { title: 'Retrocede con vida', body: 'Los pasillos castigan las retiradas tardías. Si has perdido a dos compañeros, sal antes de que la siguiente ronda empiece con reapariciones separadas.' },
      { title: 'Prepara la recuperación', body: 'Decide qué definitiva abre el regreso y desde qué puerta. Tocar por turnos solo añade porcentaje al rival sin crear una oportunidad real.' },
    ],
    heroPicks: [
      { name: 'Winston', slug: 'winston', role: 'tank', reason: 'Salta entre plataformas y puede romper una formación que se acomoda demasiado en una puerta.' },
      { name: 'D.Va', slug: 'dva', role: 'tank', reason: 'Disputa altura, protege un cruce con Matriz y corrige rápido si aparece un héroe de flanco por otro pasillo.' },
      { name: 'Mei', slug: 'mei', role: 'dps', reason: 'Muro resulta muy incómodo en las entradas estrechas y ayuda a separar a quien cruza antes que su equipo.' },
      { name: 'Tracer', slug: 'tracer', role: 'dps', reason: 'Recorre los laterales sin quedar atrapada y obliga a la backline a apartar la vista de la puerta principal.' },
      { name: 'Kiriko', slug: 'kiriko', role: 'support', reason: 'Puede seguir cambios de ruta repentinos y salir de un pasillo que deje de ser seguro.' },
      { name: 'Lúcio', slug: 'lucio', role: 'support', reason: 'Acelera los cruces, ayuda a reagrupar y convierte los bordes del mapa en una amenaza constante.' },
    ],
    compositions: [
      {
        name: 'Dive de pasillos',
        lineup: ['Winston', 'Tracer', 'Genji', 'Kiriko', 'Lúcio'],
        plan: 'Winston no salta hasta reconocer dónde puede aterrizar. Lúcio acerca al grupo, Tracer enseña el lateral y Genji entra cuando el rival ya ha girado o gastado movilidad. Kiriko mantiene una salida disponible en vez de teleportarse al primer amago.',
        weakness: 'Se rompe cuando cada jugador escoge un objetivo distinto o cuando el salto atraviesa una pared que deja a los supports sin visión. Contra una defensa compacta hay que provocar recursos antes de comprometerse.',
      },
      {
        name: 'Brawl para las puertas',
        lineup: ['Reinhardt', 'Mei', 'Cassidy', 'Lúcio', 'Kiriko'],
        plan: 'El equipo cruza una puerta con velocidad, Muro impide la retirada y Reinhardt juega la siguiente esquina. Cassidy se queda a una distancia desde la que puede vigilar el lateral sin separarse del grupo.',
        weakness: 'Sufre si intenta perseguir por rutas largas o si gasta velocidad, Muro y Suzu antes de cruzar. También puede quedarse mirando hacia arriba contra una composición que conserve la altura.',
      },
    ],
    mistakes: [
      'Entrar al punto por la primera puerta visible sin comprobar qué ángulo domina el rival.',
      'Confundir una ruta lateral con permiso para jugar solo durante toda la pelea.',
      'Perseguir por el interior del barco y perder tanto la visión de los supports como el objetivo.',
      'Defender pegado al borde cuando existe una cobertura interior igual de útil.',
      'Intentar recuperar con contactos aislados en lugar de conceder porcentaje y volver como cinco.',
    ],
    vodChecklist: [
      '¿Qué puerta eligió el equipo y quién comunicó el cambio de ruta?',
      '¿El Tank podía recibir ayuda al cruzar la primera esquina?',
      '¿Se controló la altura antes de bajar al objetivo?',
      '¿Cuántas muertes ocurrieron persiguiendo por un pasillo?',
      '¿Se conservaron recursos para salir después de la entrada?',
      '¿La recuperación empezó con el equipo agrupado o con alguien tocando por obligación?',
    ],
    faq: [
      { question: '¿Cuáles son los escenarios actuales de Antarctic Peninsula?', answer: 'La versión actual se juega en Drilling Rig, Icebreaker y Anomaly. Anomaly sustituyó al antiguo Sublevel y el conjunto recibió rutas más claras, más cobertura y cambios importantes en el espacio alrededor de los objetivos.' },
      { question: '¿Qué héroes funcionan bien en Antarctic Peninsula?', answer: 'La movilidad de Winston, D.Va, Tracer y Kiriko ayuda a manejar las alturas y los pasillos. Mei y Lúcio también sacan mucho partido de las puertas estrechas y los bordes, aunque la elección debe encajar con el plan del equipo.' },
      { question: '¿Cómo se ataca Antarctic Peninsula sin separarse?', answer: 'Elige una puerta principal y un lateral corto que sigan conectados. El lateral debe crear otro ángulo, no iniciar una pelea distinta. Cruza después de forzar una habilidad rival y ocupa una cobertura antes de tocar.' },
      { question: '¿Qué debería revisar en una VOD de este mapa?', answer: 'Empieza por las rutas y las líneas de curación. Después mira si tu equipo controló altura y puertas antes de bajar al punto, y termina revisando las muertes tardías en pasillos o cerca de los bordes.' },
    ],
    relatedLinks: [
      { href: '/guides/como-elegir-composicion-dive-poke-brawl', label: 'Cómo elegir composición' },
      { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Cómo revisar tu VOD' },
      { href: '/heroes/winston', label: 'Guía de Winston' },
      { href: '/heroes/kiriko', label: 'Guía de Kiriko' },
    ],
  },
  {
    slug: 'busan',
    name: 'Busan',
    mode: 'Control',
    location: 'Corea del Sur',
    image: '/maps/busan.png',
    imageAlt: 'Santuario tradicional coreano de Busan en Overwatch',
    seoTitle: 'Busan en Overwatch: guía de Downtown, Sanctuary y MEKA Base',
    seoDescription: 'Guía de Busan en Overwatch con planes para Downtown, Sanctuary y MEKA Base, mejores héroes, composiciones, errores frecuentes y checklist de VOD.',
    updatedAtIso: '2026-07-04',
    updatedAt: '4 de julio de 2026',
    intro: [
      'Busan cambia de personalidad en cada ronda. Downtown es rápido, vertical y bastante caótico; Sanctuary deja respirar más, pero castiga mucho a quien cruza una zona abierta sin mirar; MEKA Base encierra a los equipos alrededor de paredes y accesos cortos. Una composición puede sentirse perfecta en el primer escenario y completamente torpe en el siguiente. Cambiar entre rondas no es admitir un error: es leer el mapa que acaba de salir.',
      'La constante está en saber desde dónde quieres pelear antes de pisar el objetivo. En Busan se pierde mucho tiempo intentando desalojar a alguien que ni siquiera necesita morir. Si lo echas del balcón, de la puerta o de la cobertura que estaba usando, ya has conseguido lo importante. Captura, obliga al rival a entrar y no conviertas cada ventaja en una persecución por las calles.',
    ],
    quickRead: [
      { title: 'Cambia el plan entre rondas', body: 'Downtown favorece la movilidad, Sanctuary abre las distancias y MEKA Base obliga a pelear más cerca. Revisa la composición cuando cambie el escenario.' },
      { title: 'Llega junto a la primera pelea', body: 'Capturar primero permite defender las entradas desde cobertura. Un flanco largo al comienzo puede regalar demasiado porcentaje antes de volver.' },
      { title: 'No persigas a quien ya se va', body: 'Si expulsas a un rival de la altura o de una puerta, ya has hecho el trabajo. Ocupa su posición y obliga a que vuelva a exponerse.' },
    ],
    phases: [
      {
        name: 'Downtown',
        attack: 'Downtown tiene tantas alturas y escaparates que es fácil empezar cinco peleas pequeñas. El plan más fiable es cruzar hacia una cobertura cercana al punto y mandar solo una amenaza al balcón o al lateral. Cuando el rival mire hacia arriba, entra por abajo; cuando se apile en el punto, usa la altura. No te quedes disparando desde la avenida inicial: allí se ve mucho, pero se decide poco.',
        defense: 'Con el punto controlado, el balcón y las esquinas exteriores permiten avisar de la entrada sin quedar atrapado. La defensa debe tener claro quién vigila la altura y quién puede volver al objetivo. Si un DPS enemigo aparece detrás, presiónalo lo suficiente para que no dispare gratis, pero no abandones el centro en bloque. Downtown premia a quien cambia la mirada rápido, no a quien persigue más lejos.',
        vodReview: 'Mira la cámara justo antes de cada muerte. ¿Había una segunda línea de tiro que no habías visto? Anota también cuánto tardó el equipo en decidir si quería pelear arriba o abajo.',
      },
      {
        name: 'Sanctuary',
        attack: 'El patio de Sanctuary parece abierto, pero sus paredes y desniveles ofrecen rutas bastante seguras si no corres por el centro. Acércate usando cobertura, fuerza al rival a enseñar su posición y abre un ángulo corto por uno de los lados. Los puentes y bordes convierten el empuje en una amenaza real, así que evita agruparte junto al vacío. Capturar no exige limpiar todo el santuario: basta con expulsar al rival del área desde la que puede contestar.',
        defense: 'Defiende con espacio a la espalda. Si te plantas en el borde delantero sin salida, cualquier presión te obliga a gastar supervivencia demasiado pronto. Los supports funcionan mejor desde una esquina que vea el punto y permita ocultarse del ángulo opuesto. Cuando el rival rodee, gira la formación en lugar de dividirla: el objetivo es que la nueva primera línea siga estando entre la amenaza y la backline.',
        vodReview: 'Comprueba si cruzaste zonas abiertas por costumbre y si las muertes ambientales empezaron por una mala posición previa. El empujón suele ser el final del error, no el principio.',
      },
      {
        name: 'MEKA Base',
        attack: 'En MEKA Base, disparar desde fuera durante medio minuto rara vez mejora la entrada. Hay que elegir una puerta, forzar el recurso que la bloquea y cruzar con decisión. Una amenaza por la entrada opuesta puede ayudar, siempre que no llegue cuando la pelea ya terminó. Dentro, reparte al equipo alrededor de las paredes del punto: apilarse en el centro facilita el daño de área y hace imposible proteger a quien queda detrás.',
        defense: 'La puerta es una ventaja mientras puedas abandonarla. Presiona el cruce, pero retrocede en cuanto el rival comprometa velocidad, barrera o definitivas. Las paredes móviles cambian la visión y pueden separar curación, así que no des por hecho que tu support sigue viéndote. Si pierdes el punto, reagrupa fuera y vuelve por dos accesos cercanos; entrar uno por cada puerta solo maquilla una pelea perdida.',
        vodReview: 'Revisa qué habilidades se gastaron antes de atravesar la puerta y cuántas veces una pared cortó la visión. Después compara el primer intento con el que sí funcionó: casi siempre cambia la coordinación, no la puntería.',
      },
    ],
    attackPlan: [
      { title: 'Reconoce el escenario', body: 'No salgas de zona de reaparición en piloto automático. Decide si necesitas movilidad, alcance o velocidad para el escenario concreto que ha tocado.' },
      { title: 'Llega a una cobertura', body: 'La primera meta no es el círculo, sino una esquina desde la que el equipo pueda pelear sin gastar todo para sobrevivir.' },
      { title: 'Abre solo un lateral', body: 'Un flanco bien elegido basta para romper la defensa. Mandar a ambos DPS por rutas distintas suele dejar al Tank sin presión útil.' },
      { title: 'Captura y frena', body: 'Tras ganar, no persigas hasta zona de reaparición. Adelanta una línea razonable, cuenta reapariciones y vuelve antes de que el rival pueda aislarte.' },
    ],
    defensePlan: [
      { title: 'Asigna el lateral', body: 'Que alguien mire el acceso secundario y lo comunique. Si nadie tiene esa tarea, todo flanco parecerá una sorpresa.' },
      { title: 'No mueras en la puerta', body: 'MEKA Base castiga especialmente la retirada tardía. Cede la entrada mientras aún conserves habilidades para jugar el punto.' },
      { title: 'Respeta los bordes', body: 'En Sanctuary, posiciónate a un paso de cobertura interior. No regales una eliminación ambiental antes de que empiece el intercambio.' },
      { title: 'Cambia de forma', body: 'Si el rival entra por detrás o por arriba, gira como equipo. Mantener la primera línea apuntando al sitio equivocado no protege a nadie.' },
    ],
    heroPicks: [
      { name: 'D.Va', slug: 'dva', role: 'tank', reason: 'Puede subir a los balcones de Downtown y volver a proteger al equipo cuando cambia el ángulo.' },
      { name: 'Reinhardt', slug: 'reinhardt', role: 'tank', reason: 'Encuentra peleas cómodas en las puertas de MEKA Base y puede cerrar distancia con ayuda de velocidad.' },
      { name: 'Tracer', slug: 'tracer', role: 'dps', reason: 'Aprovecha las rutas de Downtown sin comprometerse a un flanco del que no pueda regresar.' },
      { name: 'Mei', slug: 'mei', role: 'dps', reason: 'Separa entradas en MEKA Base y ayuda a sostener zonas cerradas sin depender solo del daño.' },
      { name: 'Lúcio', slug: 'lucio', role: 'support', reason: 'La velocidad facilita cruces y sus empujones obligan a respetar los bordes de Sanctuary.' },
      { name: 'Kiriko', slug: 'kiriko', role: 'support', reason: 'Acompaña los cambios de altura y puede corregir una rotación que quede cortada por las paredes.' },
    ],
    compositions: [
      {
        name: 'Movilidad para Downtown',
        lineup: ['D.Va', 'Tracer', 'Genji', 'Kiriko', 'Lúcio'],
        plan: 'D.Va disputa el balcón sin quedarse a vivir allí. Tracer y Genji presionan el mismo lado con unos segundos de diferencia, mientras Lúcio y Kiriko permiten que el núcleo cambie de altura sin perder el ritmo.',
        weakness: 'La composición pierde fuerza si todos saltan a posiciones distintas o si intenta jugar MEKA Base como una serie de duelos. Contra mucho control necesita provocar habilidades antes de entrar.',
      },
      {
        name: 'Brawl para MEKA Base',
        lineup: ['Reinhardt', 'Mei', 'Cassidy', 'Lúcio', 'Kiriko'],
        plan: 'Lúcio marca el cruce, Reinhardt ocupa la pared siguiente y Mei busca separar al jugador que llegue tarde. Cassidy protege el espacio cercano en vez de abrir un flanco largo.',
        weakness: 'En Downtown o Sanctuary puede sufrir si no encuentra cómo cerrar distancia. Tampoco funciona si gasta velocidad y Muro en un amago y luego se queda mirando la puerta.',
      },
    ],
    mistakes: [
      'Repetir la misma composición en los tres escenarios sin preguntarse qué herramienta ha perdido valor.',
      'Quedarse en la avenida de Downtown disparando a una altura que nadie intenta disputar.',
      'Jugar junto al borde de Sanctuary aunque no exista ninguna razón para exponerse al empujón.',
      'Gastar todas las habilidades delante de la puerta de MEKA Base y cruzar cuando ya no queda ninguna.',
      'Perseguir una baja después de capturar y regalar al rival una entrada limpia por el lado opuesto.',
    ],
    vodChecklist: [
      '¿La composición se adaptó al escenario entre rondas?',
      '¿Quién tenía la responsabilidad de mirar la altura o el lateral?',
      '¿El equipo llegó junto a la primera pelea?',
      '¿Se usó cobertura al cruzar las zonas abiertas?',
      '¿Qué recurso permitió atravesar la puerta de MEKA Base?',
      '¿Las persecuciones posteriores a una victoria costaron el punto?',
    ],
    faq: [
      { question: '¿Cuáles son los tres escenarios de Busan?', answer: 'Busan se juega en Downtown, Sanctuary y MEKA Base. Downtown tiene más verticalidad y rutas, Sanctuary abre las distancias y añade bordes peligrosos, y MEKA Base concentra la acción alrededor de puertas y paredes.' },
      { question: '¿Qué héroes son buenos en Busan?', answer: 'D.Va, Tracer, Genji, Kiriko y Lúcio encajan bien con la movilidad de Downtown. Reinhardt y Mei ganan valor en MEKA Base. Lo más sensato es ajustar la composición al escenario en vez de buscar cinco picks universales.' },
      { question: '¿Cómo se juega la primera pelea en Busan?', answer: 'Llega agrupado a una cobertura cercana y decide qué altura o puerta quieres controlar. Un jugador puede abrir un lateral corto, pero debe coincidir con la entrada principal. Ganar esa posición suele ser más importante que tocar primero.' },
      { question: '¿Qué revisar en una VOD de Busan?', answer: 'Mira las decisiones entre rondas, el control de alturas en Downtown, la posición respecto a los bordes en Sanctuary y los recursos gastados antes de cruzar en MEKA Base. También cuenta cuántas peleas empezaron con alguien todavía rotando.' },
    ],
    relatedLinks: [
      { href: '/guides/como-elegir-composicion-dive-poke-brawl', label: 'Dive, poke o brawl' },
      { href: '/guides/como-revisar-habilidades-overwatch', label: 'Cómo revisar habilidades' },
      { href: '/heroes/dva', label: 'Guía de D.Va' },
      { href: '/heroes/kiriko', label: 'Guía de Kiriko' },
    ],
  },
  {
    slug: 'ilios',
    name: 'Ilios',
    mode: 'Control',
    location: 'Grecia',
    image: '/maps/ilios.png',
    imageAlt: 'Casas blancas, cúpulas azules y pozo central de Ilios en Overwatch',
    seoTitle: 'Ilios en Overwatch: guía de Lighthouse, Ruins y Well',
    seoDescription: 'Aprende a jugar Ilios en Overwatch: rutas y posiciones en Lighthouse, Ruins y Well, héroes recomendados, composiciones, errores y revisión de VOD.',
    updatedAtIso: '2026-07-19',
    updatedAt: '19 de julio de 2026',
    intro: [
      'Ilios tiene fama por el pozo, pero la mayoría de rondas no se pierden por un empujón espectacular. Se pierden unos segundos antes, cuando alguien cruza por el borde sin necesidad, abandona una cobertura para perseguir o deja que el rival ocupe gratis la zona desde la que amenaza ese empujón. Lighthouse, Ruins y Well comparten cielo azul y paredes blancas, pero piden distancias muy distintas.',
      'Lighthouse concentra la pelea alrededor de una casa pequeña y entradas cortas. Ruins abre el mapa y da mucho valor a la altura, las sightlines largas y los cambios de ángulo. Well mezcla ambas cosas: hay espacio para disparar desde lejos, pero el objetivo obliga a acercarse a una zona donde cualquier desplazamiento cuenta. La mejor preparación entre rondas es muy simple: mira el nombre del escenario y pregúntate si tu héroe puede llegar vivo a la distancia que necesita.',
    ],
    quickRead: [
      { title: 'El borde no es cobertura', body: 'Acercarte al vacío para ganar un metro de visión rara vez compensa. Juega desde la pared interior y obliga al rival a exponerse si quiere buscar el empujón.' },
      { title: 'Ruins pide poke o movilidad', body: 'Si tu equipo no puede disputar la altura ni cruzar contra snipers, cambia el plan o los héroes. Avanzar por el centro una y otra vez no cerrará la distancia por sí solo.' },
      { title: 'Lighthouse se gana en la puerta', body: 'Quien controla las entradas puede pelear sin apilarse dentro del punto. Fuerza recursos fuera y entra cuando la defensa ya no pueda sostener la primera esquina.' },
    ],
    phases: [
      {
        name: 'Lighthouse',
        attack: 'La puerta principal de Lighthouse recibe daño desde demasiados sitios si cruzas despacio. Elige una entrada, acerca al equipo usando la pared y enseña un lateral corto para que la defensa no pueda mirar a los cinco a la vez. No todos tienen que entrar en la habitación: el Tank puede ocupar una esquina, un DPS vigilar la salida y los supports mantener una línea segura desde fuera. El punto se captura cuando el rival ya no puede asomarse, no cuando todo el equipo se amontona en él.',
        defense: 'Defiende las puertas desde una distancia que permita retroceder alrededor de la casa. Si te quedas pegado a la entrada, una sola habilidad puede separarte del equipo. El jugador que controla el lateral debe avisar pronto y regresar; perseguir alrededor del faro abre la puerta contraria. Cuando el ataque gaste varias definitivas, salir con vida y preparar la recuperación puede ser mejor que morir dentro por un porcentaje que ya está perdido.',
        vodReview: 'Pausa al comenzar cada entrada y dibuja mentalmente la línea de curación. Si el Tank cruzó la puerta y desapareció de la vista, la solución no es pedir más curación, sino cambiar el ángulo o la coordinación.',
      },
      {
        name: 'Ruins',
        attack: 'Ruins castiga a los equipos que pretenden caminar por la zona abierta sin haber molestado antes a quienes disparan desde arriba. Usa columnas y desniveles para acercarte, manda movilidad a disputar la altura o responde con poke propio. No es necesario eliminar al sniper para avanzar; obligarlo a abandonar su posición durante unos segundos ya abre la ventana. Cuando llegues al punto, conserva algún jugador fuera del círculo para vigilar la siguiente rotación.',
        defense: 'La altura sirve mientras tengas una ruta para bajar. Quédate demasiado tiempo y el ataque convertirá tu buena posición en una jaula. Los jugadores de poke deben cambiar de ángulo después de ser vistos, mientras el resto protege el acceso al objetivo. Si el rival cruza con cobertura, evita bajar todos sobre el mismo blanco. Mantén una sightline activa para que su backline tampoco pueda caminar gratis.',
        vodReview: 'Observa las muertes en campo abierto y retrocede cinco segundos. ¿Qué cobertura acababas de dejar? ¿Se había marcado la posición del sniper o hitscan rival? Esa información suele explicar más que el disparo final.',
      },
      {
        name: 'Well',
        attack: 'La ruta más corta al objetivo pasa junto al pozo y por eso no siempre es la más segura. Acércate por la pared exterior, controla primero la casa lateral o amenaza desde el lado opuesto. Un héroe con empuje condiciona el espacio incluso sin usar la habilidad: si lo tienes localizado, puedes jugar donde su ángulo no funcione. Tras ganar la entrada, reparte posiciones alrededor del punto y deja de mirar al pozo como si fuera el único peligro.',
        defense: 'La defensa puede recibir antes del punto, pero no debería regalarse por buscar una jugada ambiental. Mantén una esquina interior y obliga al ataque a cruzar hacia tu daño. Si alguien cae al pozo, aprovecha la ventaja sin lanzarte detrás del resto; muchas rondas vuelven a igualarse porque el equipo ganador se separa para perseguir. En el último intento, una persona toca y las demás recuperan cobertura antes de comprometer definitivas.',
        vodReview: 'Anota cada vez que cambiaste tu ruta por miedo al empujón y cada vez que lo ignoraste. La meta es reconocer la amenaza sin permitir que controle todas tus decisiones.',
      },
    ],
    attackPlan: [
      { title: 'Identifica el rango', body: 'Antes de salir, decide cómo vas a acercarte en Ruins o cómo vas a cruzar la puerta en Lighthouse. El escenario ya te dice qué pregunta debe responder la composición.' },
      { title: 'Marca la amenaza ambiental', body: 'Localiza a Lúcio, Pharah o cualquier héroe con desplazamiento. Saber dónde está permite elegir una ruta sin convertir el borde en territorio prohibido.' },
      { title: 'Usa la pared', body: 'Las construcciones blancas no son decoración. Avanza pegado a cobertura y asoma cuando tu equipo pueda responder, no mientras atraviesas una plaza abierta.' },
      { title: 'Ocupa fuera del punto', body: 'Después de capturar, toma las entradas y alturas cercanas. Cinco jugadores sobre el círculo conceden toda la iniciativa al siguiente ataque.' },
    ],
    defensePlan: [
      { title: 'Amenaza sin regalarte', body: 'Un posible empujón ya modifica la ruta rival. No necesitas caminar tú también por el borde para demostrar que tienes la habilidad disponible.' },
      { title: 'Cambia el ángulo en Ruins', body: 'Después de disparar, muévete entre columnas o alturas. Repetir la misma línea permite que el rival prepare una entrada demasiado sencilla.' },
      { title: 'Controla dos puertas', body: 'En Lighthouse, reparte la atención entre entrada principal y lateral. El equipo debe poder girar sin dejar a los supports solos dentro.' },
      { title: 'No persigas la ventaja', body: 'Una baja temprana ya obliga al rival a retirarse. Quédate con la posición y evita convertir un cinco contra cuatro en duelos dispersos.' },
    ],
    heroPicks: [
      { name: 'Winston', slug: 'winston', role: 'tank', reason: 'Puede disputar la altura de Ruins y atravesar líneas abiertas sin obligar a todo el equipo a seguir la misma ruta.' },
      { name: 'D.Va', slug: 'dva', role: 'tank', reason: 'Llega a posiciones elevadas, protege cruces y puede volver con rapidez si la pelea gira alrededor del punto.' },
      { name: 'Widowmaker', slug: 'widowmaker', role: 'dps', reason: 'Ruins ofrece sightlines largas y ángulos que obligan al rival a moverse con más cuidado.' },
      { name: 'Pharah', slug: 'pharah', role: 'dps', reason: 'Aprovecha el espacio vertical y amenaza desplazamientos cerca del pozo y de los bordes.' },
      { name: 'Ana', slug: 'ana', role: 'support', reason: 'Tiene buenas líneas en Ruins y Well si rota antes de que una pared corte la visión de su primera línea.' },
      { name: 'Lúcio', slug: 'lucio', role: 'support', reason: 'Ayuda a cruzar zonas abiertas y su mera presencia obliga a respetar los bordes de Well y Lighthouse.' },
    ],
    compositions: [
      {
        name: 'Dive para Ruins',
        lineup: ['Winston', 'Tracer', 'Genji', 'Ana', 'Kiriko'],
        plan: 'Ana juega una cobertura desde la que pueda ver el aterrizaje. Winston salta para desplazar al rival de altura, no para perseguirlo hasta zona de reaparición; Tracer y Genji aprovechan ese movimiento y Kiriko mantiene una salida para el segundo tiempo.',
        weakness: 'Si el salto cruza detrás de una columna o los DPS llegan antes que Winston, la composición se fragmenta. También necesita paciencia contra equipos que esperan juntos y conservan todo su control.',
      },
      {
        name: 'Brawl de Lighthouse',
        lineup: ['Reinhardt', 'Mei', 'Cassidy', 'Lúcio', 'Kiriko'],
        plan: 'Lúcio acelera el cruce de puerta, Reinhardt toma la esquina interior y Mei corta la ayuda al jugador que quede expuesto. Cassidy vigila la salida lateral sin alejarse de la zona que controla el equipo.',
        weakness: 'En Ruins puede pasar demasiado tiempo intentando acercarse. Si no cambia picks o no usa la cobertura para cerrar distancia, cederá altura y líneas de tiro antes de empezar.',
      },
    ],
    mistakes: [
      'Caminar junto al pozo cuando la pared interior ofrece la misma visión y mucha más seguridad.',
      'Cruzar Ruins por el centro sin haber desplazado a los héroes que controlan la altura.',
      'Apilar a todo el equipo dentro de Lighthouse y perder las dos puertas al mismo tiempo.',
      'Perseguir a un rival tocado alrededor de una casa hasta cortar la línea de curación.',
      'Mantener una composición de corto alcance en Ruins solo porque funcionó en la ronda anterior.',
    ],
    vodChecklist: [
      '¿La ruta elegida respetaba los empujones y las sightlines largas?',
      '¿Quién disputó la altura de Ruins y cuándo lo hizo?',
      '¿Se cruzó Lighthouse con recursos o después de gastarlos?',
      '¿Las paredes cortaron la visión entre primera línea y supports?',
      '¿El equipo ocupó entradas tras capturar o esperó sobre el círculo?',
      '¿Se adaptaron los picks al cambiar de escenario?',
    ],
    faq: [
      { question: '¿Cuáles son los escenarios de Ilios?', answer: 'Ilios se divide en Lighthouse, Ruins y Well. Lighthouse concentra las peleas alrededor de una casa, Ruins ofrece sightlines largas y altura, y Well combina espacio abierto con un pozo central que condiciona la posición.' },
      { question: '¿Qué héroes funcionan bien en Ilios?', answer: 'Winston y D.Va ayudan a disputar alturas; Widowmaker y Ana aprovechan Ruins; Lúcio y Pharah amenazan los bordes. No todos encajan igual en los tres escenarios, así que conviene revisar la composición entre rondas.' },
      { question: '¿Cómo evitar caer al pozo de Ilios?', answer: 'Juega desde la pared interior, localiza a los héroes con empuje y guarda movilidad cuando tengas que cruzar cerca del borde. La prevención empieza en la ruta y la cobertura elegidas, no en reaccionar cuando ya estás en el aire.' },
      { question: '¿Cómo se recupera el punto en Ilios?', answer: 'Agrupa, identifica la posición que domina la entrada y fuerza una habilidad antes de cruzar. Abre un ángulo corto, conserva recursos para sobrevivir dentro y evita mandar contactos aislados solo para frenar el porcentaje.' },
    ],
    relatedLinks: [
      { href: '/guides/como-mejorar-posicionamiento-overwatch', label: 'Mejorar el posicionamiento' },
      { href: '/guides/como-elegir-composicion-dive-poke-brawl', label: 'Elegir una composición' },
      { href: '/heroes/winston', label: 'Guía de Winston' },
      { href: '/heroes/ana', label: 'Guía de Ana' },
    ],
  },
  {
    slug: 'nepal',
    name: 'Nepal',
    mode: 'Control',
    location: 'Nepal',
    image: '/maps/nepal.png',
    imageAlt: 'Santuario de Nepal con el objetivo de control en Overwatch',
    seoTitle: 'Nepal en Overwatch: guía de Village, Shrine y Sanctum',
    seoDescription: 'Guía completa de Nepal en Overwatch: cómo jugar Village, Shrine y Sanctum, rutas, héroes, composiciones, errores habituales y checklist para VOD.',
    updatedAtIso: '2026-07-04',
    updatedAt: '4 de julio de 2026',
    intro: [
      'Nepal parece amable con las composiciones de corto alcance porque hay puertas, patios pequeños y muchas paredes. Esa lectura funciona en Village, pero se queda corta en Shrine y puede resultar directamente peligrosa en Sanctum. El mapa premia a quien sabe cuándo acelerar y cuándo dejar de correr. Entrar rápido es útil; entrar rápido hacia un sitio donde nadie puede ayudarte no lo es.',
      'Los tres escenarios comparten una idea: el equipo que captura puede defender un acceso sin permanecer sobre el objetivo. Village gira alrededor de edificios y patios; Shrine abre varios caminos hacia una zona central; Sanctum añade alturas, columnas y un borde que castiga cualquier despiste. Para recuperar, no necesitas sorprender con una ruta de cinco minutos. Necesitas llegar juntos, enseñar una segunda amenaza y conservar suficientes habilidades para aguantar después del primer contacto.',
    ],
    quickRead: [
      { title: 'Village no se gana solo de frente', body: 'Las peleas son cercanas, pero los laterales importan. Si todo el equipo mira la puerta principal, un DPS puede disparar desde la casa hasta que sea demasiado tarde.' },
      { title: 'Mira la defensa antes de entrar', body: 'Shrine tiene varias rutas útiles. Asómate, identifica dónde está colocado el rival y cambia de acceso antes de gastar tus habilidades.' },
      { title: 'Sanctum castiga un paso', body: 'El borde y las columnas reducen el margen de error. Mantén una salida interior y no gastes movilidad únicamente para llegar primero al punto.' },
    ],
    phases: [
      {
        name: 'Village',
        attack: 'La puerta principal conduce a una pelea corta, pero no tiene por qué ser frontal. Usa la casa o el lateral para obligar a la defensa a repartir la atención y entra cuando uno de sus jugadores ya no pueda recibir ayuda. El Tank debe tomar una esquina, no correr hasta el fondo del patio. Desde esa esquina, el equipo puede decidir si presiona el punto, limpia la casa o cambia de lado sin perderse de vista.',
        defense: 'Defiende la primera entrada con una retirada hacia el objetivo. Mei, Cassidy y otros héroes de rango cercano pueden castigar a quien cruza antes, pero perseguirlo dentro de la casa suele romper la formación. Si el rival ocupa un lateral, gira la primera línea y cede unos metros. Village favorece la defensa mientras conserve sus habilidades; quedarse sin ellos delante de la puerta convierte el patio en una trampa.',
        vodReview: 'Revisa quién cruzó primero y cuánto tardó el resto en poder ayudarlo. Después mira las persecuciones dentro de la casa: ¿protegían el punto o solo continuaban un duelo que ya no importaba?',
      },
      {
        name: 'Shrine',
        attack: 'Shrine ofrece más aire y varias entradas, así que primero hay que descubrir dónde está la fuerza rival. Asoma desde cobertura, abre un lateral que siga conectado y ataca el sector con menos ayuda. Caminar directamente al círculo deja a los supports expuestos en los accesos. En cambio, ocupar una de las plataformas o esquinas cercanas permite sostener la pelea y hace que la captura llegue sin forzarla.',
        defense: 'No intentes cubrir todas las rutas desde el punto. Coloca la primera línea en el acceso más probable y usa a un jugador móvil para informar del otro lado. Cuando el rival cambie de puerta, rota por dentro y mantén la forma del equipo. Si te quedas defendiendo una entrada vacía por orgullo, la backline acabará recibiendo la entrada antes de que puedas regresar.',
        vodReview: 'Mira el minimapa mental de la pelea: dónde estaba cada compañero cuando se vio al rival. Si el equipo tardó demasiado en girar, apunta si faltó información o si alguien decidió seguir presionando una ruta vacía.',
      },
      {
        name: 'Sanctum',
        attack: 'Sanctum obliga a respetar el borde, pero esconderse en el pasillo interior tampoco gana la ronda. Usa las columnas para avanzar, localiza las habilidades de empuje y ocupa una esquina que permita disparar al objetivo sin amontonarte. Los héroes móviles pueden tocar la altura y regresar; no deben saltar detrás de varias paredes. Una entrada limpia suele empezar al forzar al rival a mirar hacia dentro, lejos del precipicio que quiere controlar.',
        defense: 'Con el punto capturado, amenaza las entradas desde las columnas y vuelve al interior si el rival acelera. El empujón es una herramienta, no el plan entero. Si sales demasiado para buscarlo, puedes morir sin que nadie haya pisado el objetivo. Conserva una persona capaz de tocar mientras las demás recuperan posiciones: saltar todos al círculo elimina las líneas cruzadas que hacen fuerte a Sanctum.',
        vodReview: 'No te limites a contar caídas. Observa por qué estabas cerca del borde, si conocías la posición del rival y si habías gastado la movilidad que podía salvarte. Ahí aparece el error útil.',
      },
    ],
    attackPlan: [
      { title: 'Elige una esquina cercana', body: 'Avanza hasta una cobertura desde la que el equipo pueda verse. El punto será la siguiente decisión, no el destino automático de la primera habilidad de movilidad.' },
      { title: 'Haz una pregunta', body: 'Asoma un lateral o presiona una puerta para descubrir cómo responde la defensa. En Shrine, esa información evita comprometerse contra su lado más fuerte.' },
      { title: 'Acelera cuando toca', body: 'Lúcio, barreras y movilidad sirven para cruzar la zona peligrosa, no para llegar diez segundos antes que tus supports.' },
      { title: 'Cierra la salida', body: 'Después de una baja, toma la puerta por la que el rival quiere retirarse sin perseguir hasta zona de reaparición. Así conviertes ventaja en captura.' },
    ],
    defensePlan: [
      { title: 'Recibe con retirada', body: 'Toda posición adelantada necesita una segunda esquina. Si la única salida exige cruzar al rival, estabas defendiendo demasiado lejos.' },
      { title: 'Un jugador informa', body: 'No mandes a media composición a vigilar el lateral. Una llamada temprana permite que todo el equipo gire sin perder su estructura.' },
      { title: 'Respeta el interior', body: 'En Sanctum, juega a una distancia del borde que permita reaccionar. La pared interior sigue ofreciendo visión y reduce las jugadas gratuitas.' },
      { title: 'Abandona la pelea perdida', body: 'Morir tarde en Nepal da al rival una defensa cómoda de la siguiente entrada. Sal, agrupa y conserva la definitiva que pueda abrir la recuperación.' },
    ],
    heroPicks: [
      { name: 'Reinhardt', slug: 'reinhardt', role: 'tank', reason: 'Disfruta las esquinas de Village y puede liderar cruces cortos cuando el equipo conserva velocidad.' },
      { name: 'Winston', slug: 'winston', role: 'tank', reason: 'Aporta otra forma de jugar Shrine y Sanctum al disputar plataformas sin entrar siempre por la puerta.' },
      { name: 'Mei', slug: 'mei', role: 'dps', reason: 'Muro castiga cruces desordenados en Village y puede aislar al jugador que se adelanta.' },
      { name: 'Genji', slug: 'genji', role: 'dps', reason: 'Se mueve entre plataformas y aprovecha objetivos separados cuando la defensa gira entre accesos.' },
      { name: 'Lúcio', slug: 'lucio', role: 'support', reason: 'Da velocidad a las entradas y obliga a considerar los bordes de Sanctum.' },
      { name: 'Kiriko', slug: 'kiriko', role: 'support', reason: 'Puede acompañar una rotación agresiva y regresar si una pared o columna rompe la línea del equipo.' },
    ],
    compositions: [
      {
        name: 'Brawl de Village',
        lineup: ['Reinhardt', 'Mei', 'Cassidy', 'Lúcio', 'Kiriko'],
        plan: 'Lúcio acerca al grupo a la primera esquina, Reinhardt sostiene el patio y Mei espera a que alguien cruce de verdad antes de usar Muro. Cassidy protege la casa y Kiriko guarda Suzu para el intercambio comprometido.',
        weakness: 'Pierde mucho si se queda quieta delante de poke o si intenta cruzar Shrine sin usar cobertura. Gastar velocidad y Muro en el primer amago deja la entrada real sin herramientas.',
      },
      {
        name: 'Dive para Shrine',
        lineup: ['Winston', 'Tracer', 'Genji', 'Ana', 'Kiriko'],
        plan: 'Winston salta a una cobertura que corte la visión rival; Tracer y Genji llegan después sobre el mismo sector. Ana mantiene una línea clara y Kiriko decide si acompaña o protege la retirada según la respuesta.',
        weakness: 'Una entrada demasiado profunda desaparece detrás de columnas y edificios. Si los DPS eligen objetivos distintos, Winston recibirá todo el control sin que la presión produzca una baja.',
      },
    ],
    mistakes: [
      'Entrar en Village por la puerta y seguir caminando hasta perder la esquina y la línea de curación.',
      'Abrir tres rutas en Shrine sin que ninguna coincida en tiempo con la presión del Tank.',
      'Gastar movilidad para llegar a Sanctum y quedarse sin respuesta junto al borde.',
      'Perseguir dentro de la casa cuando el objetivo ya está libre para capturar.',
      'Defender una entrada vacía mientras el rival rota y encuentra directamente a los supports.',
    ],
    vodChecklist: [
      '¿La primera cobertura estaba al alcance de todo el equipo?',
      '¿El lateral creó presión al mismo tiempo que la entrada principal?',
      '¿Se comunicó el cambio de ruta en Shrine?',
      '¿La posición en Sanctum tenía una salida lejos del borde?',
      '¿Mei y Lúcio usaron sus recursos antes o durante el cruce real?',
      '¿Las muertes tardías impidieron reagrupar la siguiente pelea?',
    ],
    faq: [
      { question: '¿Cuáles son los escenarios de Nepal?', answer: 'Nepal tiene Village, Shrine y Sanctum. Village favorece peleas cercanas alrededor de casas, Shrine ofrece varias rutas y más espacio, y Sanctum combina columnas, alturas y un borde peligroso junto al objetivo.' },
      { question: '¿Qué héroes son buenos en Nepal?', answer: 'Reinhardt, Mei y Lúcio funcionan bien en Village. Winston, Genji, Ana y Kiriko ofrecen más movilidad y ángulos en Shrine y Sanctum. La mejor elección depende del escenario y de cómo quiera entrar el equipo.' },
      { question: '¿Cómo atacar Sanctum sin caer al vacío?', answer: 'Avanza usando las columnas, localiza a los héroes con empuje y conserva movilidad para el intercambio. Juega desde el lado interior siempre que puedas y abre un ángulo que obligue al rival a mirar lejos del borde.' },
      { question: '¿Cómo recuperar un punto en Nepal?', answer: 'Reagrupa fuera, elige una entrada principal y usa un lateral cercano para obtener información. Fuerza una habilidad, cruza hasta una cobertura y reparte posiciones alrededor del objetivo en vez de apilar a todo el equipo dentro.' },
    ],
    relatedLinks: [
      { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Revisar una partida' },
      { href: '/guides/como-revisar-habilidades-overwatch', label: 'Revisar el uso de habilidades' },
      { href: '/heroes/reinhardt', label: 'Guía de Reinhardt' },
      { href: '/heroes/genji', label: 'Guía de Genji' },
    ],
  },
  {
    slug: 'oasis',
    name: 'Oasis',
    mode: 'Control',
    location: 'Irak',
    image: '/maps/oasis.png',
    imageAlt: 'Arquitectura futurista y jardines elevados de Oasis en Overwatch',
    seoTitle: 'Oasis en Overwatch: guía de City Center, Gardens y University',
    seoDescription: 'Guía de Oasis en Overwatch con rutas para City Center, Gardens y University, héroes recomendados, composiciones, errores habituales y checklist de VOD.',
    updatedAtIso: '2026-07-04',
    updatedAt: '4 de julio de 2026',
    intro: [
      'Oasis es uno de esos mapas donde una mala rotación se nota enseguida. City Center tiene una zona elevada que observa buena parte de la entrada; Gardens separa el punto de las rutas por las que se gana; University encierra la pelea y convierte cada puerta en una decisión. Si el equipo camina directamente al círculo en los tres escenarios, jugará siempre desde la parte menos cómoda del mapa.',
      'La alternativa no consiste en diseñar una ruta complicada. Basta con reconocer la posición que permite al rival disparar sin moverse y quitársela antes de capturar. A veces será la plataforma de City Center, otras el lateral de Gardens o la esquina interior de University. Oasis recompensa a los equipos que llegan a esa conclusión pronto y castiga a quienes gastan dos definitivas solo para descubrir desde dónde les estaban disparando.',
    ],
    quickRead: [
      { title: 'Mira arriba en City Center', body: 'La plataforma elevada condiciona el acceso al punto. Disputarla, bloquear su visión o cruzar fuera de su ángulo debe formar parte del primer plan.' },
      { title: 'Gardens se gana alrededor', body: 'El círculo queda expuesto y no ofrece una defensa completa. Controla pasarelas y coberturas laterales antes de mandar a alguien a capturar.' },
      { title: 'University necesita orden', body: 'Las puertas concentran daño y control. Fuerza una respuesta, cruza con recursos y reparte posiciones dentro en lugar de entrar todos por el mismo metro.' },
    ],
    phases: [
      {
        name: 'City Center',
        attack: 'La plataforma central parece el destino obvio, pero subir por la ruta más visible contra un equipo preparado puede consumir todas las habilidades. Presenta presión desde abajo, usa movilidad para tocar la altura o gira por una entrada que corte su línea. El objetivo es que quien defiende arriba tenga que moverse o mirar a dos sitios. En cuanto ocurra, el Tank puede ocupar una cobertura cerca del punto y el resto deja de disparar desde la calle.',
        defense: 'La altura vale por la información y el ángulo, no porque haya que morir sobre ella. Dispara mientras el ataque cruza y baja antes de quedar rodeado. Un jugador puede conservar la plataforma mientras el núcleo defiende una esquina inferior, siempre que exista ayuda entre ambos. Cuando el rival use movilidad para subir, castiga su aterrizaje o gira al objetivo; perseguirlo por la parte trasera puede dejar el círculo completamente libre.',
        vodReview: 'Cuenta cuánto tiempo pasó el equipo mirando hacia la plataforma sin cambiar de ruta. Después revisa si quien la disputó recibió ayuda o llegó varios segundos antes que la presión de abajo.',
      },
      {
        name: 'Gardens',
        attack: 'En Gardens, tocar primero suele ser una distracción. Las pasarelas y habitaciones laterales permiten disparar al punto con mucha más seguridad que el propio círculo. Acércate por una cobertura, toma uno de esos espacios y obliga a la defensa a ceder. Si mandas a un jugador a capturar, que sea alguien con salida y con apoyo visible. Los saltos sobre el vacío ahorran tiempo, pero no compensan una ruta que deja al equipo dividido.',
        defense: 'Defiende desde los laterales y usa el punto como zona de fuego cruzado. Cuando alguien toque, no todos tienen que bajar: una persona contesta y las demás conservan ángulos. Los bordes hacen valiosos los desplazamientos, aunque buscar una eliminación ambiental no debe sacar al support de cobertura. Si el ataque controla ambos lados, cede el círculo y reagrupa; pelear dentro sin líneas propias solo retrasa una derrota unos segundos.',
        vodReview: 'Observa quién estaba en el punto y quién controlaba las pasarelas. Si cuatro jugadores capturaban mientras el rival recuperaba los laterales, la ventaja se gastó antes de la siguiente pelea.',
      },
      {
        name: 'University',
        attack: 'University es corto y ruidoso. Hay daño en la puerta, habilidades en el suelo y muy poco tiempo para entender qué ha pasado. Evita entrar lentamente por el centro. Asoma para provocar control, utiliza una ruta lateral cercana y cruza cuando el equipo pueda ocupar dos esquinas interiores. Una vez dentro, no persigas por los pasillos: protege la salida de tus supports y haz que la defensa regrese a través de la misma puerta difícil.',
        defense: 'Presiona la entrada sin gastar todo en el primer amago. La defensa que conserva control y supervivencia para cuando el rival cruza es mucho más peligrosa que la que llena la puerta de efectos durante cinco segundos. Si pierdes el acceso, retrocede alrededor del punto y vuelve a formar una primera línea. Morir en el pasillo exterior impide reagruparse y regala porcentaje mientras vuelves desde la zona de reaparición.',
        vodReview: 'Anota el orden de habilidades en cada cruce. Si las herramientas defensivas salieron antes de que el rival entrara o el ataque gastó movilidad sin avanzar, ahí está la ventana que decidió la pelea.',
      },
    ],
    attackPlan: [
      { title: 'Encuentra la posición fuerte', body: 'Localiza la altura, pasarela o puerta que sostiene la defensa. Tu primera acción debe desplazarla o anular su visión, no tocar el círculo.' },
      { title: 'Conecta la movilidad', body: 'Quien salte a City Center necesita presión simultánea desde abajo. Una llegada solitaria a la altura solo entrega un objetivo fácil.' },
      { title: 'Captura con una persona', body: 'En Gardens, deja que el resto controle los laterales. El porcentaje sube igual y la siguiente pelea empieza desde posiciones mejores.' },
      { title: 'Cruza de verdad', body: 'En University, distingue entre asomarse y entrar. Después de forzar el recurso rival, compromete el movimiento antes de que vuelva a estar disponible.' },
    ],
    defensePlan: [
      { title: 'Cede la altura a tiempo', body: 'La plataforma de City Center no merece una muerte tardía. Baja con vida y obliga al rival a gastar más para llegar al punto.' },
      { title: 'Conserva los laterales', body: 'En Gardens, una persona puede tocar mientras el resto mantiene ángulos. Bajar todos elimina la ventaja de haber capturado primero.' },
      { title: 'Espera el cruce', body: 'Guarda al menos una herramienta de control para cuando el ataque atraviese la puerta de University y ya no pueda retroceder con facilidad.' },
      { title: 'No alargues la retirada', body: 'Si la pelea está perdida, sal por la ruta más corta. Oasis castiga mucho reaparecer por turnos y llegar tarde al siguiente acceso.' },
    ],
    heroPicks: [
      { name: 'D.Va', slug: 'dva', role: 'tank', reason: 'Puede disputar City Center, proteger un cruce y volver rápido al punto si la pelea cambia de nivel.' },
      { name: 'Winston', slug: 'winston', role: 'tank', reason: 'Obliga a moverse a quienes ocupan plataformas y abre espacio sin caminar por la línea principal.' },
      { name: 'Tracer', slug: 'tracer', role: 'dps', reason: 'Usa los laterales de Gardens y City Center para crear presión sin abandonar el combate durante demasiado tiempo.' },
      { name: 'Mei', slug: 'mei', role: 'dps', reason: 'En University puede cortar una puerta, aislar al primer jugador y hacer más segura una pelea cercana.' },
      { name: 'Ana', slug: 'ana', role: 'support', reason: 'Encuentra líneas útiles en City Center y Gardens si rota antes de que su equipo desaparezca tras una estructura.' },
      { name: 'Kiriko', slug: 'kiriko', role: 'support', reason: 'Sigue los cambios de altura y ayuda a sobrevivir al intercambio concentrado de University.' },
    ],
    compositions: [
      {
        name: 'Dive vertical',
        lineup: ['Winston', 'Tracer', 'Genji', 'Ana', 'Kiriko'],
        plan: 'Winston desplaza al rival de la plataforma y aterriza donde Ana aún pueda verlo. Tracer y Genji cierran sobre el mismo lado, mientras Kiriko guarda la posibilidad de acompañar el segundo movimiento o salvar la salida.',
        weakness: 'En University puede quedarse sin espacio para organizar el salto. También falla cuando la presión de los DPS llega antes o después de Winston y la defensa recupera sus habilidades entre ambas entradas.',
      },
      {
        name: 'Brawl de University',
        lineup: ['Reinhardt', 'Mei', 'Cassidy', 'Lúcio', 'Kiriko'],
        plan: 'Lúcio acelera el cruce, Reinhardt ocupa una esquina interior y Mei reserva Muro para separar al rival que retrocede. Cassidy controla el espacio cercano y evita que un héroe de flanco entre gratis por el pasillo.',
        weakness: 'Tiene dificultades en Gardens si no encuentra cobertura para acercarse. Si usa velocidad solo para llegar a la puerta y se detiene allí, el poke rival puede vaciar sus recursos antes de la pelea.',
      },
    ],
    mistakes: [
      'Mirar la plataforma de City Center desde abajo durante toda la pelea sin disputarla ni cambiar de ruta.',
      'Mandar a varios jugadores al punto de Gardens y abandonar las pasarelas que permiten defenderlo.',
      'Cruzar la puerta de University de uno en uno después de gastar las habilidades en el amago.',
      'Perseguir a un héroe móvil por detrás de la estructura y dejar a la backline sin primera línea.',
      'Morir tarde en una posición elevada cuando ya existía una ruta segura para regresar al objetivo.',
    ],
    vodChecklist: [
      '¿Quién podía disputar la altura de City Center?',
      '¿La movilidad coincidió con la presión del resto del equipo?',
      '¿Cuántos jugadores capturaron en Gardens y quién tomó los laterales?',
      '¿Qué habilidad rival se forzó antes de cruzar University?',
      '¿Los supports conservaron una línea de visión durante la rotación?',
      '¿El equipo salió a tiempo de las peleas perdidas?',
    ],
    faq: [
      { question: '¿Cuáles son los escenarios de Oasis?', answer: 'Oasis se juega en City Center, Gardens y University. City Center destaca por su plataforma elevada, Gardens por sus pasarelas y espacios abiertos, y University por las peleas cercanas alrededor de puertas e interiores.' },
      { question: '¿Qué héroes funcionan bien en Oasis?', answer: 'D.Va, Winston, Tracer y Genji ayudan a disputar altura y laterales. Mei y Reinhardt son cómodos en University. Ana y Kiriko ofrecen apoyos distintos según la distancia y la movilidad que necesite el equipo.' },
      { question: '¿Cómo atacar City Center?', answer: 'Evita quedarte en la calle mirando hacia arriba. Presiona desde abajo mientras un héroe móvil disputa la plataforma, o rota por una ruta que corte su visión. Entra al punto cuando la defensa ya no pueda mantener ese ángulo gratis.' },
      { question: '¿Cómo defender Gardens?', answer: 'Controla las pasarelas y coberturas laterales. Una persona puede tocar el objetivo cuando sea necesario mientras las demás mantienen líneas cruzadas. Si todo el equipo baja al círculo, el rival recuperará las posiciones desde las que puede disparar con seguridad.' },
    ],
    relatedLinks: [
      { href: '/guides/como-mejorar-posicionamiento-overwatch', label: 'Guía de posicionamiento' },
      { href: '/guides/como-elegir-composicion-dive-poke-brawl', label: 'Elegir dive, poke o brawl' },
      { href: '/heroes/dva', label: 'Guía de D.Va' },
      { href: '/heroes/ana', label: 'Guía de Ana' },
    ],
  },
  {
    slug: 'samoa',
    name: 'Samoa',
    mode: 'Control',
    location: 'Samoa',
    image: '/maps/samoa.png',
    imageAlt: 'Costa tropical, palmeras y edificios de Samoa en Overwatch',
    seoTitle: 'Samoa en Overwatch: guía de Beach, Downtown y Volcano',
    seoDescription: 'Guía de Samoa en Overwatch: cómo jugar Beach, Downtown y Volcano, rutas, mejores héroes, composiciones, errores frecuentes y revisión de VOD.',
    updatedAtIso: '2026-07-19',
    updatedAt: '19 de julio de 2026',
    intro: [
      'Samoa es luminoso, abierto y bastante menos relajado de lo que su playa sugiere. Beach permite rodear el objetivo por varios niveles; Downtown mezcla edificios y balcones; Volcano encierra la pelea alrededor de lava y pasos estrechos. En los tres escenarios hay rutas atractivas que pueden convertirse en una excursión inútil si el equipo principal entra antes de que el flanco llegue.',
      'La forma más estable de jugar Samoa es pensar en parejas de posiciones. ¿Desde qué cobertura avanza el Tank y qué ángulo cercano lo acompaña? ¿Dónde se coloca el support si el equipo gira al otro lado? Cuando esas dos respuestas encajan, el mapa ofrece muchas opciones. Cuando no, cada ruta adicional solo multiplica las paredes que separan a los cinco jugadores.',
    ],
    quickRead: [
      { title: 'El flanco depende del timing', body: 'Una ruta lateral es buena si crea presión durante la entrada principal. Si llegas cuando tus compañeros ya están saliendo de spawn, solo has dado un paseo largo.' },
      { title: 'Volcano exige calma', body: 'El espacio parece pequeño y anima a gastar todo de golpe. Conserva movilidad o protección para el segundo intercambio y respeta la lava incluso con ventaja.' },
      { title: 'Downtown se juega en vertical', body: 'Los balcones cambian quién puede disparar al punto. Antes de capturar, limpia la altura o bloquea al jugador que la mantiene.' },
    ],
    phases: [
      {
        name: 'Beach',
        attack: 'Beach tiene desniveles, habitaciones y rutas junto al agua. Empieza por una cobertura desde la que el equipo pueda ver tanto el punto como la entrada lateral. Un DPS puede rodear por el nivel superior, pero debe anunciar cuándo está listo; el Tank no gana nada absorbiendo daño durante veinte segundos mientras espera. Cuando la defensa gire hacia el flanco, avanza. Si decide ignorarlo, deja que ese ángulo trabaje antes de saltar al círculo.',
        defense: 'La defensa puede jugar adelantada porque hay varias rutas de retirada, aunque tiene que elegir una. Vigila la entrada larga sin enviar a todo el equipo y mantén el núcleo cerca de una cobertura que permita bajar al punto. Los bordes amenazan, pero salir a buscarlos te coloca en el mismo peligro. Después de una baja, cierra rutas hacia el objetivo y deja que el porcentaje haga presión por ti.',
        vodReview: 'Compara el momento del flanco con el de la entrada principal. Si hubo más de tres o cuatro segundos entre ambos, seguramente el rival nunca tuvo que responder a dos amenazas a la vez.',
      },
      {
        name: 'Downtown',
        attack: 'En Downtown, el balcón que domina la zona central puede frenar la entrada sin que parezca estar haciendo gran cosa. Dispútalo con movilidad, bloquéalo mientras cruzas o ataca desde un lado que reduzca su visión. Caminar por abajo y mirar hacia arriba deja al Tank sin presión sobre el objetivo. Una vez dentro, ocupa la esquina del edificio y un ángulo exterior; no hace falta llenar cada balcón para impedir que el rival regrese.',
        defense: 'Usa la altura para cobrar recursos, pero baja antes de que te corten la salida. La defensa debe saber quién toca si el rival entra por abajo y quién mantiene el ángulo sobre los supports. Si todos saltan al punto, Downtown se convierte en una pelea plana y desaparece la ventaja del escenario. Cambia de balcón después de ser localizado para que el siguiente ataque no llegue con el duelo preparado.',
        vodReview: 'Mira dónde estaba la cámara cuando empezaste a recibir daño. Si pasaste la pelea alternando entre el Tank de abajo y un DPS de arriba, faltó decidir qué posición despejar primero.',
      },
      {
        name: 'Volcano',
        attack: 'Volcano castiga las entradas impulsivas. Acércate por una pared, identifica el control y los desplazamientos rivales, y fuerza uno antes de cruzar la zona estrecha. La lava no solo mata: reduce las rutas disponibles y hace más previsible la retirada. Ocupa la cobertura interior y abre un segundo ángulo pequeño. Un flanco profundo cerca del borde es difícil de ayudar y muy fácil de convertir en una eliminación gratuita.',
        defense: 'Amenaza el acceso, no la jugada del año. Mantener al rival preocupado por un empujón ya facilita todo el daño frontal; exponerte para buscarlo puede regalar el punto. Si el ataque consigue entrar, retrocede alrededor del objetivo y conserva una salida que no pase junto a la lava. En overtime, decide quién toca primero. Cinco saltos desesperados por la misma puerta producen una repetición corta y poco instructiva.',
        vodReview: 'Revisa las habilidades de movimiento y desplazamiento como si fueran definitivas pequeñas. ¿Se usaron para ganar posición, para confirmar una baja o simplemente porque estaban disponibles?',
      },
    ],
    attackPlan: [
      { title: 'Sincroniza el flanco', body: 'El lateral debe avisar cuando está listo y esperar la presión frontal. Samoa recompensa los ángulos, pero solo cuando aparecen en la misma ventana.' },
      { title: 'Limpia el balcón', body: 'En Downtown, decide quién sube, quién bloquea y quién cruza. Ignorar la altura mientras todos la miran es la peor combinación posible.' },
      { title: 'Guarda una salida', body: 'No gastes toda la movilidad para entrar en Volcano. El segundo intercambio suele decidirse por quién todavía puede apartarse de la lava o del control.' },
      { title: 'Convierte sin perseguir', body: 'Tras ganar una baja, ocupa el acceso al punto. Las rutas largas hacen muy costosa una persecución que saque al equipo de su estructura.' },
    ],
    defensePlan: [
      { title: 'Elige una retirada', body: 'Puedes defender adelantado en Beach y Downtown si sabes por dónde volverás. Una posición sin salida solo parece fuerte hasta que el rival acelera.' },
      { title: 'Mantén la altura útil', body: 'El jugador del balcón debe poder ayudar al punto y recibir ayuda. Una altura desconectada es un duelo, no control del mapa.' },
      { title: 'Haz respetar la lava', body: 'En Volcano, conserva desplazamientos para el cruce real. La amenaza reduce el espacio rival incluso si no consigues una baja ambiental.' },
      { title: 'Sal después de perder', body: 'Samoa tiene rutas suficientes para escapar. Úsalas antes de morir tarde y llegar a la siguiente pelea con el equipo incompleto.' },
    ],
    heroPicks: [
      { name: 'D.Va', slug: 'dva', role: 'tank', reason: 'Disputa balcones y puede cubrir el cruce de un compañero sin quedarse aislada en la altura.' },
      { name: 'Winston', slug: 'winston', role: 'tank', reason: 'Rompe posiciones elevadas y aprovecha las coberturas para aterrizar sin depender de una entrada frontal.' },
      { name: 'Tracer', slug: 'tracer', role: 'dps', reason: 'Convierte las rutas laterales en presión sincronizada y regresa rápido si el flanco deja de tener valor.' },
      { name: 'Pharah', slug: 'pharah', role: 'dps', reason: 'Aprovecha el espacio vertical de Beach y Downtown, además de amenazar desplazamientos cerca de los bordes.' },
      { name: 'Kiriko', slug: 'kiriko', role: 'support', reason: 'Puede seguir cambios de nivel y rescatar una entrada que quede cortada por edificios o pasos estrechos.' },
      { name: 'Lúcio', slug: 'lucio', role: 'support', reason: 'Acelera el cruce de Volcano y hace que cada borde del mapa requiera un poco más de atención.' },
    ],
    compositions: [
      {
        name: 'Dive de dos tiempos',
        lineup: ['Winston', 'Tracer', 'Genji', 'Ana', 'Kiriko'],
        plan: 'Tracer muestra primero el lateral sin comprometerse. Winston salta a una cobertura que corte la línea rival y Genji entra después sobre el objetivo desplazado. Ana prepara la zona y Kiriko conserva el segundo movimiento.',
        weakness: 'Las paredes de Downtown y Volcano pueden cortar a Ana. Si Winston aterriza fuera de visión o Tracer convierte su amago en un duelo largo, el equipo entra sin presión simultánea.',
      },
      {
        name: 'Brawl para Volcano',
        lineup: ['Reinhardt', 'Mei', 'Cassidy', 'Lúcio', 'Kiriko'],
        plan: 'Lúcio permite atravesar el paso peligroso, Reinhardt ocupa la pared interior y Mei reserva Muro para una retirada rival. Cassidy juega cerca y vigila al DPS que intente rodear por el acceso corto.',
        weakness: 'En Beach puede sufrir contra ángulos amplios y altura. Si el equipo se detiene antes de completar el cruce, gastará sus recursos sin llegar a la distancia en la que realmente amenaza.',
      },
    ],
    mistakes: [
      'Tomar una ruta lateral larga sin avisar y llegar después de que la pelea principal haya terminado.',
      'Mirar al balcón de Downtown desde abajo sin asignar a nadie para disputarlo o bloquearlo.',
      'Gastar movilidad para entrar en Volcano y quedarse sin salida junto a la lava.',
      'Buscar una baja ambiental cuando bastaba con mantener la posición y dejar subir el porcentaje.',
      'Perseguir entre edificios después de capturar y abrir el punto por el acceso contrario.',
    ],
    vodChecklist: [
      '¿El flanco coincidió con la entrada principal?',
      '¿Quién tenía la tarea de disputar el balcón de Downtown?',
      '¿La posición del Tank mantenía una línea con sus supports?',
      '¿Se conservó movilidad para salir de Volcano?',
      '¿Los desplazamientos se usaron en el cruce real?',
      '¿El equipo defendió accesos o esperó apilado sobre el punto?',
    ],
    faq: [
      { question: '¿Cuáles son los escenarios de Samoa?', answer: 'Samoa se juega en Beach, Downtown y Volcano. Beach combina desniveles y rutas costeras, Downtown añade balcones y edificios, y Volcano concentra la acción cerca de pasos estrechos y zonas de lava.' },
      { question: '¿Qué héroes funcionan bien en Samoa?', answer: 'D.Va, Winston, Tracer y Kiriko aprovechan los cambios de altura y las rutas. Pharah encuentra espacio vertical, mientras Lúcio ayuda a cruzar y amenaza los bordes. La composición debe adaptarse al escenario concreto.' },
      { question: '¿Cómo jugar Volcano sin morir en la lava?', answer: 'Acércate usando la pared interior, localiza los desplazamientos rivales y conserva movilidad para el segundo intercambio. Fuerza una habilidad antes de cruzar y evita mandar un flanco profundo por una ruta que el equipo no pueda apoyar.' },
      { question: '¿Cómo aprovechar los flancos de Samoa?', answer: 'Escoge un lateral corto y comunica cuándo estás listo. La presión debe coincidir con la entrada del Tank. Si el rodeo tarda demasiado, vuelve al equipo en vez de insistir en una jugada que ya perdió su momento.' },
    ],
    relatedLinks: [
      { href: '/guides/como-elegir-composicion-dive-poke-brawl', label: 'Elegir composición' },
      { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Analizar una VOD' },
      { href: '/heroes/winston', label: 'Guía de Winston' },
      { href: '/heroes/kiriko', label: 'Guía de Kiriko' },
    ],
  },
]
