export const HERO_PORTRAITS: Record<string, string> = {
  ana: '/heroes/ana.png',
  anran: '/heroes/anran.png',
  ashe: '/heroes/ashe.png',
  baptiste: '/heroes/baptiste.png',
  bastion: '/heroes/bastion.png',
  brigitte: '/heroes/brigitte.png',
  cassidy: '/heroes/cassidy.png',
  domina: '/heroes/domina.png',
  doomfist: '/heroes/doomfist.png',
  dva: '/heroes/dva.png',
  echo: '/heroes/echo.png',
  emre: '/heroes/emre.png',
  freja: '/heroes/freja.png',
  genji: '/heroes/genji.png',
  hanzo: '/heroes/hanzo.png',
  hazard: '/heroes/hazard.png',
  illari: '/heroes/illari.png',
  'jetpack-cat': '/heroes/jetpack-cat.png',
  'junker-queen': '/heroes/junker-queen.png',
  junkrat: '/heroes/junkrat.png',
  juno: '/heroes/juno.png',
  kiriko: '/heroes/kiriko.png',
  lifeweaver: '/heroes/lifeweaver.png',
  lucio: '/heroes/lucio.png',
  mauga: '/heroes/mauga.png',
  mei: '/heroes/mei.png',
  mercy: '/heroes/mercy.png',
  mizuki: '/heroes/mizuki.png',
  moira: '/heroes/moira.png',
  orisa: '/heroes/orisa.png',
  pharah: '/heroes/pharah.png',
  ramattra: '/heroes/ramattra.png',
  reaper: '/heroes/reaper.png',
  reinhardt: '/heroes/reinhardt.png',
  roadhog: '/heroes/roadhog.png',
  shion: '/heroes/shion.png',
  sierra: '/heroes/sierra.png',
  sigma: '/heroes/sigma.png',
  sojourn: '/heroes/sojourn.png',
  'soldier-76': '/heroes/soldier-76.png',
  sombra: '/heroes/sombra.png',
  symmetra: '/heroes/symmetra.png',
  torbjorn: '/heroes/torbjorn.png',
  tracer: '/heroes/tracer.png',
  vendetta: '/heroes/vendetta.png',
  venture: '/heroes/venture.png',
  widowmaker: '/heroes/widowmaker.png',
  winston: '/heroes/winston.png',
  'wrecking-ball': '/heroes/wrecking-ball.png',
  wuyang: '/heroes/wuyang.png',
  zarya: '/heroes/zarya.png',
  zenyatta: '/heroes/zenyatta.png',
}

export function getHeroPortrait(slug: string) {
  return HERO_PORTRAITS[slug] ?? null
}

