import type { HeroPillar } from './hero-pillars'

export const reviewedReinhardtHero: HeroPillar = {
  slug: 'reinhardt', name: 'Reinhardt', role: 'Tank', roleSlug: 'tank',
  publishedAt: '2026-06-26', schemaDate: '2026-10-04', updatedAt: '4 de octubre de 2026',
  seoTitle: 'Reinhardt en Overwatch: barrera, Charge y Earthshatter en ranked',
  seoDescription: 'Cómo acercarte con Reinhardt sin agotar la barrera, cuándo cancelar Charge y cómo preparar Shatter. Perks, matchups y ejemplos de King’s Row y Circuit Royal.',
  h1: 'Reinhardt en Overwatch: barrera, Charge y Shatter',
  kicker: 'Acercarte con el equipo y pelear desde cobertura',
  intro: [
    'Con Reinhardt, decide a qué cobertura quieres llegar antes de levantar la barrera. Necesitas una posición desde la que puedas pegar, recibir ayuda y volver a taparte. Si atraviesas una línea larga hasta quedarte sin escudo, puedes llegar junto al rival pero sin recursos para pelear.',
    'No todo se resuelve avanzando. A veces toca cubrir una retirada, frenar al enemigo que entra en tus Supports o esperar a que ellos recuperen visión después de una esquina. Aquí encontrarás cómo elegir esos momentos, usar Charge sin perder al equipo y preparar Shatter según las defensas que quedan disponibles.',
  ],
  headerTips: [
    'Antes de cruzar, comprueba la siguiente cobertura y si tus compañeros pueden llegar contigo.',
    'Decide dónde cancelar Charge antes de empezar. Un pin posible no siempre merece el trayecto.',
    'Con Shatter, mira qué bloquea la línea y quién puede aprovechar el derribo.',
  ],
  quickAnswers: [
    { title: 'Si llegas sin barrera a todas las peleas', body: 'Revisa el cruce anterior: ¿caminaste por una línea abierta mientras el grupo aún esperaba? Acércate por una pared y reserva la barrera para el tramo expuesto. Si se agota cubriendo una retirada necesaria, no es el mismo error que consumirla esperando quieto delante de cinco enemigos.' },
    { title: 'Si dejas de recibir curación al avanzar', body: 'Mira la cámara de tus Supports al doblar la esquina. Quizá sigan en la cobertura anterior o estén atendiendo un flanco. Esperar un momento a que roten puede permitirte pelear allí; seguir varios metros más puede obligarte a intentar salir sin ayuda.' },
    { title: 'Si Shatter derriba pero no consigue bajas', body: 'Comprueba quién tenía tiro y qué defensas aparecieron después. Un derribo puede dar tiempo para cubrirse o ganar el punto aunque no mate. Si lo tiraste lejos de tus compañeros y luego cargaste a través de toda la defensa, revisa el seguimiento antes de culpar al daño del equipo.' },
  ],
  facts: [
    { title: 'Martillo', body: 'Tu presión más constante llega a corta distancia. Necesitas acercarte sin perder la curación ni ofrecer un flanco fácil al rival.' },
    { title: 'Barrera', body: 'Protege la línea que cubre, no todas las direcciones. Una pared cercana permite bajar el escudo sin seguir recibiendo el mismo focus.' },
    { title: 'Charge', body: 'Puede empotrar a un enemigo contra una pared y se puede cancelar. La posición donde terminas importa aunque aciertes el pin.' },
    { title: 'Shatter', body: 'Derriba a los enemigos alcanzados por delante. Barreras, cobertura y defensas disponibles condicionan el resultado y el daño posterior.' },
  ],
  rankedPlan: [
    'Escoge una cobertura cercana desde la que amenaces a alguien. No tiene que ser la posición más adelantada: debe permitir que tus DPS presionen y que tus Supports vean la pelea sin exponerse por completo.',
    'Prepara el cruce con el grupo. Si tenéis velocidad, pide el momento en que la necesitas, no cuando ya has perdido casi toda la barrera. Si no hay Lúcio, acorta el recorrido y aprovecha que otro compañero haga cubrirse al rival.',
    'Al llegar, alterna la amenaza del martillo con momentos de cobertura o barrera según el daño que viene. No hay una proporción fija de pegar y escudar: un Sleep disponible o un segundo ángulo rival pueden cambiarla.',
    'Antes de Charge, decide el destino y qué harás si no atrapas a nadie. Puedes cancelarla para quedarte junto a una esquina. Si el recorrido te separa de tus Supports, acertar a un enemigo no asegura que sobrevivas después.',
    'Después de ganar, toma una posición que permita preparar la siguiente pelea mientras alguien mueve el objetivo. No persigas hasta la zona de reaparición si la defensa puede volver antes de que tú recuperes barrera y ayuda.',
  ],
  sections: [
    { title: 'Bajar la barrera sin regalarte', body: 'La cobertura sirve para dejar de recibir daño y recuperar recursos, no solo para esconderte cuando estás crítico. Si desde la esquina amenazas con martillo, el rival debe decidir si se acerca. Puedes asomar para pegar y volver a taparte cuando llegue una respuesta que no conviene recibir. En una línea abierta, bajar la barrera tiene otro coste: varios enemigos pueden seguir disparándote aunque ninguno esté a tu alcance.' },
    { title: 'Retirarte también puede proteger al equipo', body: 'Cuando Mei levanta un muro o Ana te deja sin curación, seguir hacia delante puede convertir una mala situación en una muerte sin salida. Retrocede hacia la cobertura que habías preparado y orienta la barrera hacia el daño que amenaza al grupo. No tienes que ceder todo el mapa: si conserváis jugadores y recursos, podéis volver a disputar la esquina cuando cambie la pelea.' },
    { title: 'Charge para llegar, no solo para buscar pin', body: 'Una carga puede servir para alcanzar una cobertura antes de que el rival se instale, siempre que el grupo pueda acompañar el cambio de posición. Decide dónde cancelarla y mira los enemigos que pueden interrumpirte. Si has atrapado a alguien, valora también quién quedará al final del recorrido: llevar al Tank rival detrás de su propia backline puede ser una mala llegada para ti, aunque consigas el daño del impacto.' },
    { title: 'En el mirror, mira la barrera y los ángulos', body: 'Frente a otro Reinhardt, Fire Strike y los swings ofrecen momentos en los que baja su barrera, pero no garantizan una Shatter gratis: puede reaccionar o volver a cubrirse. Cambiar de posición puede hacer que tenga que elegir entre taparte a ti o el daño de tus DPS. Si solo esperas el duelo de reflejos por la misma línea, sus compañeros también pueden preparar Sleep, empujones o defensas para el seguimiento.' },
    { title: 'King’s Row: no dobles la esquina solo', body: 'En calles, después de ganar la primera pelea, es fácil adelantarse mientras los Supports aún rodean la carga. Toma la próxima esquina sin salir varios metros más por un enemigo que se retira. Antes de empezar a pegar allí, comprueba que la curación tiene visión y que un DPS puede contestar el lateral. Si la defensa ha vuelto desde otro acceso, usar toda la barrera mirando al frente no tapa ese ángulo.' },
    { title: 'Circuit Royal: distingue el cruce de la pelea', body: 'En la primera recta, un balcón con tiro libre puede gastar tu barrera antes de que tengas a nadie a rango. Pide presión sobre esa altura y usa las paredes para reducir el tramo que debes cubrir. No hagas Charge hasta debajo del balcón esperando que el resto atraviese la misma línea después. En el interior final hay más opciones de pelear cerca, pero el grupo sigue necesitando llegar por una ruta compatible.' },
  ],
  abilities: [
    { title: 'Rocket Hammer', body: 'El martillo amenaza a los enemigos a tu alcance y puede alcanzar a varios si están agrupados. Busca una posición desde la que puedas pegar sin perseguir cada paso que retrocedan. Si bajan tus recursos o aparece un segundo ángulo, interrumpe la presión para cubrirte. El daño alto al Tank rival no demuestra por sí solo que estuvieras protegiendo lo que necesitaba tu equipo.' },
    { title: 'Barrier Field', body: 'Despliega una barrera frontal mientras la mantienes activa. Puedes orientarla para cubrir un cruce, un disparo importante o a compañeros que se retiran, pero no sustituye la cobertura ni bloquea cualquier ataque. El martillo y Fire Strike dejan de mantener esa protección durante su uso: comprueba qué puede llegar cuando bajas el escudo. Que la barrera termine rota exige revisar para qué se gastó, no condenar el uso automáticamente.' },
    { title: 'Charge', body: 'Avanzas, atrapas a un enemigo y puedes empotrarlo contra una pared; también puedes cancelar la carga antes del final. Practica el punto de parada y comprueba la visión que tendrá tu equipo desde allí. Cancelar evita seguir un recorrido que ya no interesa, pero no devuelve el cooldown ni elimina el daño recibido. Contra una Orisa con Fortify, no cuentes con conseguir el pin.' },
    { title: 'Fire Strike', body: 'Lanza un proyectil de fuego para presionar una línea o a enemigos que no están a rango del martillo. Mira cuántas cargas tienes antes de gastar la siguiente por costumbre. Puedes buscar una rotación previsible o un objetivo tocado; lanzarlo mientras varios rivales esperan a que bajes la barrera puede costar más de lo que aporta. Tras Shatter, elige una línea alcanzable antes de correr hacia el derribo.' },
    { title: 'Earthshatter', body: 'Golpeas el suelo para derribar enemigos por delante. Una barrera entre tú y el objetivo puede impedirlo; no confundas tener a varios en pantalla con una línea que vaya a alcanzarlos. Prepara también lo que ocurre después: Fire Strike, martillo o el tiro de tus DPS, según la distancia. Suzu puede proteger del daño posterior, pero no levanta a un enemigo que ya está derribado por Shatter.' },
  ],
  perksIntro: 'Eliges una opción Minor y una Major. Estas mejoras pertenecen al kit normal: los poderes de Stadium que añaden curación a aliados con la barrera o efectos extra a Charge son opciones distintas.',
  perks: [
    { title: 'Minor · Crusader’s Fire', body: 'Aturdir a un enemigo recupera una carga de Fire Strike y permite superar las cargas habituales hasta el límite del perk. Puede darte seguimiento después de un control acertado. Comprueba la línea de tiro antes de gastar lo recuperado: el enemigo puede seguir teniendo ayuda aunque esté derribado.' },
    { title: 'Minor · Crusader’s Resolve', body: 'Mientras usas Barrier Field, la regeneración pasiva de tu salud se activa antes. Es alternativa a Crusader’s Fire. No es curación inmediata ni regeneración de barrera al hacer Charge; necesitas dejar de recibir daño y encontrar un momento en el que esa recuperación pueda empezar.' },
    { title: 'Major · Shield Slam', body: 'Con la barrera activa puedes realizar un golpe que daña y empuja al enemigo. Puede ayudarte a apartar una amenaza cercana sin tratar cada contacto como un pin. No lo confundas con un poder de Stadium que cambia Charge ni des por hecho que el empujón resolverá un focus de varios lados.' },
    { title: 'Major · Ignited Fury', body: 'Los enemigos alcanzados por Fire Strike te dan un aumento temporal de velocidad de ataque. Es alternativa a Shield Slam. Puedes aprovecharlo si ya estás cerca para pegar; acertar un proyectil desde muy lejos no significa que puedas cruzar a salvo antes de que termine la mejora.' },
  ],
  mistakes: [
    'Quedarte quieto bajo focus mientras esperas que todos se coloquen detrás del escudo. Mira si el grupo podía empezar el cruce o si necesitabas otra ruta. Consumir la barrera sin cambiar la posición puede dejaros el mismo problema y menos recursos.',
    'Darle un swing más al Tank después de perder la visión de curación. Revisa cuándo doblaste la esquina y qué estaban haciendo tus Supports. La retirada podía empezar antes de que tu vida obligara al equipo a gastar varias defensas.',
    'Mantener Charge solo porque has atrapado a alguien. Si el destino te deja entre otros enemigos, piensa en la cancelación que podía conservar una posición jugable. Un pin no compensa automáticamente abandonar a tu grupo.',
    'Bajar la barrera para Fire Strike ante una habilidad que estabas esperando. Comprueba si Ana seguía con Sleep o si el Reinhardt rival tenía una línea de Shatter. Que hubiera varios objetivos alineados no hacía gratuito el lanzamiento.',
    'Cargar después de Shatter sin mirar la distancia. Puedes dejar atrás a varios enemigos derribados que tus compañeros sí alcanzaban. Decide si necesitas desplazarte o si martillo y Fire Strike permiten seguir desde donde estás.',
    'Seguir peleando delante mientras un flanco presiona la backline. No siempre debes dar media vuelta: mira quién puede atenderlo. Si nadie tiene ayuda allí, cubrir una retirada o recortar la distancia al grupo puede ser más útil que continuar el duelo frontal.',
  ],
  counters: [
    { title: 'Orisa', body: 'Fortify impide que cuentes con un pin, y la jabalina puede cortar tu intento de acercarte. Busca una esquina desde la que amenaces sin tener que gastarlo todo sobre ella. Si consume recursos para mantenerse delante, mira si tu equipo puede presionar a sus compañeros en lugar de insistir en el mismo duelo.' },
    { title: 'Ramattra', body: 'Pummel en Nemesis atraviesa barreras: levantar el escudo a su lado no detiene esos golpes. Usa cobertura para cortar el contacto y mira cuándo puedes volver a pelear con ayuda. La barrera aún puede servir contra el daño que viene de sus compañeros, pero no resuelve sola el intercambio cercano.' },
    { title: 'Mei', body: 'Un muro detrás de ti puede cortar curación y retirada. No cruces un choke separado del grupo solo porque la esquina siguiente esté cerca. Si te aísla, avisa qué parte del muro impide ayudar y deja de perseguir mientras buscáis recuperar contacto.' },
    { title: 'Ana', body: 'Sleep y granada castigan el momento en que bajas la barrera o terminas una carga expuesto. No esperes bloquearlos siempre por reflejos a corta distancia. Desde cobertura puedes presionar sin ofrecer toda tu silueta; si recibes anti, distingue una salida posible de una pelea que aún puedes sostener con ayuda defensiva.' },
    { title: 'Zenyatta', body: 'Discord vuelve más caro permanecer expuesto al focus. No intentes atravesar una recta solo para alcanzarlo mientras el resto tiene tiro sobre ti. Corta la exposición con cobertura y coordina otra amenaza que le haga dejar de disparar desde su posición cómoda.' },
    { title: 'Pharah y Echo', body: 'Pueden atacar desde un ángulo que no cubres al orientar la barrera hacia el frente. Mira si tus DPS tienen una posición para contestarlas y si tus Supports pueden taparse. Mantener una esquina o cubrir el cruce hacia otro techo puede ayudar más que gastar todos tus recursos mirando arriba sin acercarte a nadie.' },
  ],
  counterplay: [
    'Si no llegáis al contacto, revisa la ruta y el momento del cruce antes de repetirlo con más prisa. Esperar a que un DPS presione la altura o a que los Supports roten puede cambiar la entrada; una Charge larga no reemplaza esas condiciones.',
    'Si la defensa rival responde siempre al bajar la barrera, cambia la exposición. Puedes amagar presión desde una esquina y volver a taparte, o dejar que otro ángulo obligue al enemigo a atender a alguien más. No necesitas ganar todos los duelos de reacción de frente.',
    'Si el mapa exige disputar alturas que tu grupo no puede contestar y sigues sin llegar tras ajustar el recorrido, valora otro Tank que conozcas. El swap debe resolver esa necesidad concreta, no responder automáticamente a que aparezca Orisa en el marcador.',
  ],
  compositions: [
    { title: 'Lúcio y Kiriko para cruzar y seguir peleando', body: 'La velocidad puede ayudaros a llegar juntos y Suzu puede responder a una amenaza durante el contacto. Acordad el cruce antes de entrar. Si Lúcio ya ha gastado Amp para otra cosa o Kiriko está fuera de visión, no puedes esperar la misma ayuda. Tras consumir esos recursos, la siguiente cobertura sigue importando.' },
    { title: 'Mei y Cassidy alrededor de una esquina', body: 'Mei puede separar a quien cruza y Cassidy contestar el acceso cercano mientras tú amenazas con martillo. No persigas al enemigo que sale por un lateral si eso deja sin frente al grupo. En calles de King’s Row, ocupar juntos la esquina permite que el daño siga el intento en lugar de recibir un pin anunciado desde varios metros atrás.' },
    { title: 'Ana o Baptiste desde una línea que puedan mantener', body: 'Ambos pueden ayudarte si conservan visión mientras avanzas. Prepara dónde jugarán antes de doblar una esquina. Con Baptiste, no des por hecho que Lamp cubrirá un Charge que termina detrás de otra pared; con Ana, Nano no sustituye la curación ni la llegada del resto del equipo. Si un flanco los obliga a moverse, cambia el ritmo antes de quedarte solo.' },
  ],
  vodReview: [
    'Elige un cruce en el que agotaste la barrera. Cuenta quién podía dispararte y qué cobertura buscabas. Comprueba si la gastaste moviendo al grupo, esperando sin avanzar o cubriendo una retirada necesaria: son decisiones distintas.',
    'Pausa una muerte justo después de doblar una esquina. Mira la posición de tus Supports y el momento en que dejaron de verte. Prueba una pausa o una cobertura anterior como alternativa al último swing.',
    'Revisa una Charge acertada y una fallada. En ambas, señala dónde podías cancelar y quién podía ayudarte al terminar. Separar el daño del pin de la posición final evita dar por buena cualquier carga que atrapó a alguien.',
    'Antes de Shatter, marca qué bloqueaba la línea y dónde estaban tus DPS. Después mira las defensas gastadas, el daño posible y el progreso del objetivo. Una ultimate sin bajas puede haber dado una retirada; una con bajas puede haberos costado demasiados recursos para continuar.',
    'Busca una pelea en la que ignoraste un lateral. Mira si alguien del grupo tenía recursos para atenderlo o si todos esperaban ayuda de otra persona. Decide qué posición te permitía amenazar al frente y permanecer cerca del equipo.',
  ],
  checklist: [
    '¿Qué cobertura quiero alcanzar y cuánto tramo debo cruzar expuesto?',
    '¿Los Supports tienen visión ahora y la conservarán cuando avance?',
    '¿Qué me pueden tirar al bajar la barrera para pegar o lanzar Fire Strike?',
    '¿Dónde cancelaré Charge si no aparece un pin que merezca el recorrido?',
    '¿Qué puede bloquear Shatter y quién tiene seguimiento desde aquí?',
    'Si el grupo necesita retirarse, ¿qué línea debo cubrir?',
  ],
  faqs: [
    { question: '¿Es un error que se rompa la barrera de Reinhardt?', answer: 'No siempre. Puede haberse gastado cubriendo una retirada o dando tiempo para ganar una pelea. Revisa si cambió algo útil para el equipo. Es distinto perderla cruzando con apoyo que consumirla quieto frente al rival y empezar después el mismo recorrido sin protección.' },
    { question: '¿Cuándo conviene cancelar Charge?', answer: 'Cuando continuar te deja en peor posición: no has atrapado a nadie, el destino está rodeado o tus Supports no podrán ayudarte. También puedes usarla para alcanzar una cobertura y parar allí. Cancelar no recupera el cooldown ni convierte en seguro un cruce mal preparado.' },
    { question: '¿Qué hay que mirar antes de Earthshatter?', answer: 'La línea hacia el objetivo, las barreras que pueden bloquearla y los compañeros que pueden seguir. Después del derribo aún pueden aparecer defensas. Elige si necesitas martillo, Fire Strike o cubrir al grupo; no hagas Charge automáticamente al ver enemigos en el suelo.' },
    { question: '¿Suzu levanta a los enemigos derribados por Shatter?', answer: 'No elimina un derribo de Earthshatter ya aplicado. Sí puede proteger del daño posterior, así que acertar Shatter no garantiza el remate. Mira dónde está Kiriko y qué pueden aprovechar tus compañeros mientras los objetivos están en el suelo.' },
    { question: '¿Necesito Lúcio para jugar Reinhardt?', answer: 'No, aunque la velocidad puede facilitar ciertos cruces. Sin ella necesitas una ruta más corta o presión que obligue al rival a cubrirse mientras avanzáis. No intentes el mismo recorrido abierto esperando que levantar la barrera reproduzca la ayuda de un Amp disponible.' },
    { question: '¿Debo cambiar de Reinhardt contra Orisa o Ramattra?', answer: 'No automáticamente. Prueba otra posición, acorta el cruce y coordina la presión antes de decidir. Si sigues sin disputar lo que necesita el grupo, cambia a un Tank que conozcas y que resuelva ese problema. No mantengas el pick por orgullo ni hagas swap solo por el nombre del rival.' },
  ],
  conclusion: 'En tu siguiente replay, elige un cruce y una Charge para revisar. Señala la cobertura que buscabas, la visión de curación y el punto donde podías parar. Así puedes cambiar una decisión concreta en la próxima partida, sin reducir todo tu trabajo como Tank al daño bloqueado o a cuántos rivales cayeron con Shatter.',
  links: [
    { href: '/guides/como-jugar-reinhardt-ranked-overwatch', label: 'Practicar los cruces y entradas de Reinhardt en ranked' },
    { href: '/counters/reinhardt', label: 'Matchups y respuestas frente a Reinhardt' },
    { href: '/team-comps/reinhardt', label: 'Preparar una composición con Reinhardt' },
    { href: '/maps/kings-row', label: 'Esquinas y avance de la carga en King’s Row' },
    { href: '/maps/circuit-royal', label: 'Cruces, balcones y curvas de Circuit Royal' },
    { href: '/heroes/ana', label: 'Entender la visión y las ayudas de Ana' },
    { href: '/heroes/kiriko', label: 'Cuándo Kiriko puede ayudar con Suzu y teleport' },
    { href: '/heroes/dva', label: 'Disputar alturas con D.Va' },
    { href: '/heroes/winston', label: 'Preparar una entrada con Winston' },
    { href: '/roles/tank', label: 'Elegir la posición del equipo como Tank' },
    { href: '/guides/como-mejorar-como-tank-overwatch', label: 'Revisar el espacio y las retiradas del Tank' },
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Mirar las respuestas disponibles antes de avanzar' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Revisar una pelea paso a paso' },
    { href: '/experts', label: 'Pedir una revisión de tus cruces y decisiones de Tank' },
  ],
}
