import type { HeroPillar } from './hero-pillars'

export const reviewedCassidyHero: HeroPillar = {
  slug: 'cassidy', name: 'Cassidy', role: 'DPS', roleSlug: 'dps',
  publishedAt: '2026-06-26', schemaDate: '2026-10-04', updatedAt: '4 de octubre de 2026',
  seoTitle: 'Cassidy en Overwatch: Flashbang, ángulos y Deadeye',
  seoDescription: 'Elige posiciones con Cassidy, ayuda contra el dive y usa Flashbang, Roll y Deadeye con seguimiento. Perks y ejemplos de King’s Row y la estación de Midtown.',
  h1: 'Cassidy en Overwatch: ángulos, Flashbang y Deadeye',
  kicker: 'Disparar desde cobertura y ayudar sin perseguir',
  intro: [
    'Cassidy puede acertar varios tiros y aun así quedarse fuera de la pelea: el rival se tapa, tu Tank avanza por otra esquina y tú sigues solo en la anterior. Antes de pedirte más headshots, comprueba qué posición estabas defendiendo y quién podía ayudarte cuando llegaron a por ti.',
    'Su revólver funciona mejor cuando no tienes que elegir entre disparar y sobrevivir en medio de la calle. Una esquina cercana permite asomarte, recargar y volver a ayudar. Flashbang complica una entrada de movilidad y Roll ofrece una recarga y un desplazamiento corto; ninguna de las dos convierte a Cassidy en un counter automático del dive. Aquí explicamos cómo elegir esa posición, cuándo atender la backline y qué buscar con Deadeye.',
  ],
  headerTips: [
    'Elige una esquina que deje ver la pelea y una ruta corta hacia quien puede curarte.',
    'Si llega un flanker, ayuda a expulsarlo antes de decidir si merece la pena perseguirlo.',
    'Prepara Deadeye con una línea de tiro y una respuesta al enemigo que puede alcanzarte.',
  ],
  quickAnswers: [
    { title: 'Si haces daño pero nadie cae', body: 'Sigue a uno de los objetivos en el replay. ¿Tenía curación constante, una barrera delante o una esquina a la que volver? Puedes buscar otro ángulo, concentrar tiros con un compañero o presionar una defensa que vuestro Tank necesita quitar. Cambia algo concreto; disparar a un Support desde demasiado lejos tampoco asegura más impacto.' },
    { title: 'Si te matan mientras ayudas al Support', body: 'Mira dónde acabaste después de girarte. Ayudar a Ana no exige plantarte junto a ella dentro de la burbuja de Winston. Puedes disparar desde otra esquina y mantener una separación que obligue al rival a elegir. Si ya gastaste Roll al llegar, tendrás menos opciones para salir cuando el segundo enemigo entre.' },
    { title: 'Si mueres usando Deadeye', body: 'Revisa la activación, no solo el disparo final. Puede que nadie tuviera que cruzar tu línea, que D.Va llegara antes de disparar o que Ana siguiera viéndote desde el lateral. Busca una posición menos expuesta y un momento en el que el equipo pueda presionar esa misma zona. Una buena vista del mapa no basta para una buena ultimate.' },
  ],
  facts: [
    { title: 'Alcance', body: 'Acertar a mucha distancia no significa hacer el mismo daño. Busca una distancia que puedas sostener desde cobertura, sin competir siempre en la línea de Widowmaker.' },
    { title: 'Roll', body: 'Recarga y reduce daño durante el desplazamiento. Es una salida corta, no una forma de volver desde un flanco profundo.' },
    { title: 'Flashbang', body: 'Hinder limita la movilidad del enemigo, pero no lo deja sin disparar como un stun completo. Necesitas seguimiento y una posición que puedas mantener.' },
    { title: 'Deadeye', body: 'Fijar objetivos no elimina sus barreras, curación ni rutas de retirada. Mira qué pueden hacer antes de esperar el disparo.' },
  ],
  rankedPlan: [
    'Antes del primer intercambio, elige qué entrada vas a vigilar y desde dónde te verá un Support. No tiene que ser la misma puerta que mira vuestro Tank. Un lateral cercano puede abrir tiro sobre el rival sin obligarte a volver cruzando toda la pelea.',
    'Acompaña el cambio de esquina del equipo. Si Reinhardt ya ha doblado la siguiente calle, revisa si tu posición aún ayuda o si solo te deja disparar a un enemigo que nadie más puede alcanzar. Recarga a cubierto durante esa rotación cuando sea posible.',
    'Cuenta la munición antes de comprometer un duelo cercano. Fan the Hammer gasta las balas que quedan; Roll puede recargar, pero también decide dónde terminas. No combines ambos por costumbre si el desplazamiento te lleva delante del Tank rival.',
    'Al oír una entrada sobre la backline, identifica quién llegó y quién puede seguirlo. Mantén tiro sobre ese enemigo o su salida sin abandonar la cobertura que te protege del resto. Si se retira, comprueba si el objetivo sigue en peligro antes de continuar detrás.',
    'Antes de Deadeye, mira la ruta del rival, las defensas que aún tiene y quién podrá ayudarte. Puedes intentar negar un cruce o rematar objetivos presionados, pero la ultimate no garantiza que nadie tenga que asomarse. Si la línea deja de servir, no esperes por inercia.',
  ],
  sections: [
    { title: 'Un ángulo lateral necesita una vuelta corta', body: 'Si Baptiste puede verte desde la esquina principal, un paso al lateral puede daros dos líneas sobre el mismo enemigo. Si sigues doblando puertas, quizá dejes de tener curación justo cuando Winston se gire hacia ti. Antes de abrir más el ángulo, señala por dónde volverías. Si necesitas Roll y un cruce abierto para llegar al grupo, has asumido un riesgo distinto al de asomarte desde una cobertura cercana.' },
    { title: 'Disparar al Tank también puede ser la decisión correcta', body: 'Si Reinhardt rival ha perdido barrera y vuestro equipo puede seguir el daño, tus tiros pueden impedirle sostener la esquina. No cambies de objetivo solo por una regla de no disparar nunca al Tank. El problema aparece cuando mantienes el mismo intercambio contra defensas y curación mientras un enemigo accesible presiona a tus Supports. Mira qué hace retroceder tu daño y qué amenaza sigues dejando libre.' },
    { title: 'El peel termina cuando el compañero puede volver a jugar', body: 'Si Tracer gasta Recall y se retira, quizá hayas conseguido lo necesario para que Ana vuelva a curar. Perseguirla hasta un health pack puede sacarte de la pelea principal y dejar a Ana sin esa ayuda en la entrada siguiente. Sigue vigilando el acceso mientras recuperas munición; no hace falta conseguir la baja para haber frenado la amenaza. Si otro enemigo ya está entrando, el trabajo de peel aún no ha terminado.' },
    { title: 'King’s Row: vigilar hotel sin perder la estatua', body: 'En defensa del primer punto, hotel puede permitir que un flanker llegue al lateral de tus Supports. Puedes vigilar su salida desde una cobertura cercana a la zona de estatua, con tiro sobre el acceso y una ruta hacia el equipo. Si el atacante retrocede al interior, no entres detrás sin mirar qué ocurre por la entrada principal. Cuando vuestro Tank cede hacia el punto, esa posición también necesita moverse; quedarte defendiendo la puerta anterior puede dejarte solo.' },
    { title: 'Midtown: cambiar de lado alrededor de los vagones', body: 'En la estación del tramo final, una puerta o un vagón puede cortar la curación justo después de un Roll. Mira a tu Support antes de cambiar de lado y comprueba si ambos podéis sostener la siguiente entrada. Un lateral sirve si presiona al mismo grupo que disputa la carga; recorrer el interior para buscar Deadeye mientras tus compañeros defienden otra puerta puede dejar dos peleas separadas. Usa esas coberturas para recargar y reposicionarte, no para desaparecer del combate que necesita el equipo.' },
    { title: 'Deadeye no obliga al enemigo a salir de cobertura', body: 'Si el rival puede taparse y esperar sin perder el objetivo, la ultimate quizá no cambie nada. Una activación sobre una rotación necesaria puede exigir otra respuesta, siempre que conserves la línea y el grupo presione detrás. Mira a D.Va, las barreras y el control que puede alcanzarte antes de empezar. Si esas respuestas cambian durante la carga, vuelve a evaluar: esperar más no borra Matrix ni convierte una pared en un objetivo disponible.' },
  ],
  abilities: [
    { title: 'Peacekeeper: disparo principal', body: 'El disparo principal permite presionar con precisión. Asómate desde cobertura para disparar y vuelve a taparte si el rival tiene una línea peligrosa sobre ti. El daño pierde eficacia con la distancia: acertar varios tiros lejanos no justifica seguir compitiendo con una sniper bien colocada. Acerca la pelea mediante una ruta protegida o atiende un objetivo que el grupo ya pueda presionar.' },
    { title: 'Fan the Hammer: disparo secundario', body: 'Dispara rápidamente la munición restante con menos precisión. Puede servir sobre un objetivo cercano y grande, pero gastarlo sobre alguien que ya cruza la puerta puede dejarte sin balas para la amenaza siguiente. No es el secundario disponible si eliges Silver Bullet: ese perk lo sustituye. Comprueba también la defensa rival antes de vaciar el cargador sobre Matrix o una barrera.' },
    { title: 'Flashbang', body: 'La granada aplica Hinder: ralentiza y limita habilidades de movilidad, sin el stun completo de la Flashbang antigua. El enemigo todavía puede responder con daño. Lánzala cuando el enemigo esté a su alcance y puedas seguir el impacto desde una cobertura; iniciar una persecución lejana con ella no garantiza que llegues a rematar. Si has gastado control, vuelve a mirar quién puede entrar ahora sobre ti o tus Supports.' },
    { title: 'Combat Roll', body: 'Ruedas en la dirección de movimiento, recargas y recibes menos daño durante ese desplazamiento. Usarlo para recargar puede tener sentido si necesitas continuar el daño y acabas en una cobertura útil. El riesgo es gastarlo sin mirar la entrada rival o rodar hacia una zona donde ya no pueden curarte. La reducción de daño no es invulnerabilidad; no cuentes con reglas de un evento para atravesar una amenaza en ranked.' },
    { title: 'Deadeye', body: 'Activas la ultimate para fijar objetivos y decides cuándo disparar. Necesitas una línea útil en ese momento, no solo al comenzar: una barrera, Matrix o la retirada del enemigo pueden cambiar el disparo. También pueden presionarte mientras esperas. No busques siempre una altura espectacular; una esquina conectada con el equipo puede darte una activación más segura y seguimiento sobre quien intenta cruzar.' },
    { title: 'Sharpshooter', body: 'Los golpes críticos reducen el cooldown de la habilidad de movimiento. Puede ayudarte a recuperar Roll antes, pero no planifiques una salida suponiendo que conectarás los críticos necesarios. Mira el cooldown real después del intercambio. Si fallas los tiros o el objetivo se tapa, seguirás necesitando la cobertura que elegiste antes de rodar.' },
  ],
  perksIntro: 'Eliges una Minor y una Major. Estas opciones pertenecen al kit normal; el autoaim, la granada magnética y otras mejoras de Stadium no forman parte de estas elecciones. Tampoco cuentas con la invulnerabilidad de Roll de un evento anterior.',
  perks: [
    { title: 'Minor · Bang Bang', body: 'Lanzas una segunda Flashbang que llega más lejos, a cambio de que ambas hagan menos daño. Puede ampliar la zona donde condicionas la movilidad, pero no es una segunda granada con el daño completo de la original. Piensa qué entrada quieres cubrir y si puedes seguir los impactos; alcanzar al enemigo más lejos no te da automáticamente una posición desde la que rematarlo.' },
    { title: 'Minor · Giddy Up', body: 'Ganas velocidad después de Roll y el aumento decae. Es alternativa a Bang Bang y puede ayudar a recuperar una esquina o acompañar una rotación cercana. Elige antes la ruta: moverte más rápido no te protege de una línea abierta ni permite seguir indefinidamente a un flanker. Tampoco aumenta por sí solo la distancia del Roll.' },
    { title: 'Major · Rollin’ Round-Up', body: 'Roll te cura según las balas que recarga. Si el cargador está lleno, no lo trates como una cura fija que recibirás igualmente. Es una opción para intercambios donde puedes disparar y volver a cobertura con la recarga; no sustituye la ayuda de un Support ni hace segura cualquier entrada hacia delante. Mira tanto la munición como la posición de llegada.' },
    { title: 'Major · Silver Bullet', body: 'Sustituye Fan the Hammer por un disparo perforador que aplica sangrado. Roll y Deadeye reinician su cooldown. Es alternativa a Rollin’ Round-Up: cambia tu secundario, no añade otro tiro al vaciado de cargador. Puedes aprovechar un objetivo o varios rivales alineados, pero no presupongas una baja por acertar; todavía importan su vida, curación y defensas. Prepara la línea antes de gastar Roll buscando otro tiro.' },
  ],
  mistakes: [
    'Quedarte en la esquina anterior mientras el equipo avanza. En el replay, mira cuándo tu Tank dejó de tener tiro sobre el objetivo al que seguías disparando y por dónde podías acompañarlo sin cruzar al descubierto.',
    'Rodar hacia delante para recargar sin comprobar la llegada. Pausa al terminar Roll: ¿quién podía verte, qué pared tenías y qué enemigo conservaba una entrada sobre ti? La recarga puede ser útil; terminar aislado es otro problema.',
    'Girar a ayudar al Support y acercarte hasta compartir todo el daño del dive. Comprueba si había una segunda cobertura desde la que podías disparar al atacante sin darle dos objetivos juntos.',
    'Seguir a Tracer después de Recall mientras el resto disputa el punto. Mira si Ana ya podía volver a curar y qué dejó de cubrir tu posición al entrar en la siguiente puerta. Expulsar al flanker puede haber sido suficiente.',
    'Vaciar el cargador sobre una defensa y empezar la recarga justo cuando el objetivo queda accesible. Revisa si podías esperar a que Matrix se retirara, cambiar de ángulo o guardar balas para la entrada de vuestro Tank.',
    'Activar Deadeye mirando solo los objetivos marcados. Sigue también a quien podía cancelarte o negar el disparo. Que aparezca una marca no asegura el remate: comprueba si puedes disparar a tiempo y si el equipo podrá continuar la pelea.',
  ],
  counters: [
    { title: 'Widowmaker', body: 'Su línea larga obliga a exponerte antes de entrar en una distancia favorable. No repitas el mismo peek intentando ganar por puntería. Cambia de ruta, acompaña una presión sobre su posición o juega desde una esquina que atienda otra amenaza. Acertar un tiro no elimina el riesgo del siguiente asomo.' },
    { title: 'Hanzo', body: 'Puede esperar un asomo previsible o añadir mucho daño cercano cuando ya has rodado hacia él. Usa distintas salidas de cobertura y mira qué presión tiene de tus compañeros. Si se retira, no lo sigas hacia un interior sin saber qué apoyo conserva ni dónde podrás curarte.' },
    { title: 'Winston', body: 'Puede llegar sobre tu posición y poner una burbuja entre tú y la ayuda. Mira dónde queda el borde y busca una cobertura desde la que tu Support vuelva a verte. Dispararle puede ser necesario para expulsarlo, pero no te quedes dentro del mismo duelo mientras su DPS llega por otro lado.' },
    { title: 'D.Va', body: 'Matrix puede negar tus tiros importantes y el disparo de Deadeye. Si se queda delante, puedes cambiar de ángulo con el grupo o esperar desde cobertura a que deje de usarla. No te acerques a vaciar el cargador solo por estar dentro de rango: también debes poder sobrevivir a sus cañones y misiles.' },
    { title: 'Sigma', body: 'Barrera y Grasp pueden cortar la presión de una línea única. Busca un lateral conectado que le obligue a decidir qué protege, sin entrar solo en su rango para rodearlo. Si vuestro equipo está rompiendo barrera para cruzar, ayudar a ese objetivo puede ser más útil que desaparecer buscando un flanco.' },
    { title: 'Tracer y Genji', body: 'Pueden forzar que mires atrás y atacar cuando has gastado Roll o Flashbang. Ayuda desde una posición con apoyo; guardar habilidades no basta si llegan dos enemigos a la vez. Contra Deflect, no sigas disparando por costumbre: espera a poder presionar otra vez o atiende una amenaza distinta sin regalarle los tiros.' },
  ],
  counterplay: [
    'Antes de cambiar por recibir dive, revisa una llegada completa. ¿Estabas separado, Roll ya estaba gastado o el Support perdió visión al rodear una puerta? Prueba una esquina más cercana y una respuesta compartida. No hace falta ganar un duelo aislado para ayudar a expulsar al atacante.',
    'Contra alcance largo, acerca el combate mediante cobertura en lugar de repetir un intercambio lejano. Si no hay una ruta que el grupo pueda sostener, el equipo quizá necesite disputar primero esa altura. No puedes resolverlo solo rodando unos metros hacia delante.',
    'Valora otro DPS que conozcas si, después de ajustar ruta y posición, seguís necesitando movilidad o alcance que no puedes aportar. Cambiar tiene que resolver esa necesidad, no castigar un fallo de aim. La siguiente elección también necesitará curación y un lugar desde el que jugar.',
  ],
  compositions: [
    { title: 'Reinhardt y Mei abriendo una esquina', body: 'Mantén tiro sobre el enemigo al que vuestro Tank alcanza sin ponerte delante de su protección. Una pared de Mei puede limitar la salida, pero también puede cortarte el disparo o separar a tu Support. Mira por dónde va a continuar el equipo antes de usar Roll para entrar; que la comp sea brawl no obliga a Cassidy a acabar dentro del grupo rival.' },
    { title: 'Ayuda defensiva con D.Va y un Support conectado', body: 'Cuando D.Va vuelve a proteger a Ana, puedes disparar al atacante desde una cobertura distinta en lugar de seguir al mech hasta la misma esquina. Conserva visión de la amenaza y evita que un segundo ángulo te obligue a retirarte solo. D.Va no tiene que quedarse permanentemente en la backline: cuando la entrada termine, ambos necesitáis volver a atender el mapa.' },
    { title: 'Sigma y un DPS que cubra más alcance', body: 'Con Ashe o Sojourn puedes ocuparte de una entrada cercana mientras el otro DPS presiona más lejos. Si nadie amenaza tus Supports, busca un ángulo útil sobre la pelea principal; no te quedes esperando un flanker que aún no aparece. Coordinad la siguiente cobertura cuando Sigma avance para no perder esa separación al rotar.' },
  ],
  vodReview: [
    'Elige una pelea con muchos impactos y pocas bajas. Sigue a un objetivo durante tus tiros: anota su curación, su retirada y si algún compañero podía añadir daño. Así distingues presión sobre una posición de un intercambio que no cambió nada.',
    'Pausa un Roll al comenzar y al terminar. Compara munición, salud, cobertura y visión del Support. No marques la habilidad como mal usada solo por recargar; mira qué permitió hacer y qué amenaza te dejó sin respuesta.',
    'Revisa un peel desde la cámara del Support. ¿Pudo volver a curar después de tu ayuda o seguía con otro enemigo encima? Después sigue tu ruta: quizá el error llegó al perseguir a quien ya se había retirado.',
    'Con Flashbang, mira si el impacto tuvo seguimiento y si tú podías mantener esa distancia. Distingue un fallo de lanzamiento de una granada acertada que no permitía rematar. Son correcciones distintas.',
    'Revisa Deadeye desde la cámara de quien te negó el disparo. Mira cuándo tenía Matrix, barrera, control o una pared disponible y qué presión recibió del resto del equipo. Después decide qué debías preparar antes de activar.',
  ],
  checklist: [
    '¿Qué entrada cubro y quién puede curarme desde aquí?',
    '¿Mi ángulo sigue ayudando después de la rotación del Tank?',
    '¿Dónde terminaré si uso Roll para recargar?',
    '¿Puedo seguir Flashbang sin abandonar mi cobertura?',
    '¿El flanker sigue amenazando al Support o ya puedo volver al frente?',
    '¿Qué respuesta rival puede negar Deadeye y quién la está presionando?',
  ],
  faqs: [
    { question: '¿Está mal disparar al Tank con Cassidy?', answer: 'No siempre. Puedes ayudar a romper una defensa, impedir que mantenga una esquina o rematarlo cuando el grupo puede seguir el daño. Revisa si ese intercambio cambia la posición rival. Si tiene toda la ayuda y tú ignoras una amenaza accesible sobre la backline, quizá necesites otro objetivo o ángulo, no simplemente más tiros.' },
    { question: '¿Puedo usar Combat Roll para recargar?', answer: 'Sí, si esa recarga permite continuar un intercambio útil y terminas en una posición segura. Antes de rodar, mira la munición, la entrada rival y quién podrá curarte al llegar. El problema no es recargar con la habilidad por definición, sino gastarla sin una salida o rodar hacia delante cuando el rival aún puede alcanzarte.' },
    { question: '¿Flashbang deja al enemigo completamente aturdido?', answer: 'No. Aplica Hinder, que limita movilidad y ralentiza, pero no el stun completo de la granada antigua. El enemigo puede seguir haciendo daño. Prepara el seguimiento desde cobertura y no des por ganado el duelo solo por acertar; también importa la ayuda que conserva y si otro enemigo puede entrar sobre ti.' },
    { question: '¿Cassidy es un counter automático de Tracer o Genji?', answer: 'No. Puede complicar una entrada con Flashbang y tiros de revólver, pero necesita acertar, conservar una posición con ayuda y atender el seguimiento rival. Si estás aislado o gastaste Roll para llegar, el flanker puede aprovecharlo. Expulsarlo del Support puede ser suficiente; perseguir una baja por todo el mapa suele dejar otra entrada libre.' },
    { question: '¿Qué hago si no consigo bajas con Deadeye?', answer: 'Mira si negó un cruce necesario, facilitó el avance del equipo o solo permitió al rival esperar a cubierto. No todas las activaciones necesitan una baja, pero necesitan cambiar algo útil en la pelea. Revisa también quién podía negar el disparo y si el equipo lo presionó. Esperar más tiempo no elimina barreras ni hace que un objetivo oculto quede disponible.' },
    { question: '¿Qué perks tiene Cassidy en el kit normal?', answer: 'Las Minor son Bang Bang, que añade una segunda Flashbang con menos daño por granada, y Giddy Up, que da velocidad después de Roll. Las Major son Rollin’ Round-Up, que cura por las balas recargadas con Roll, y Silver Bullet, que sustituye el secundario por un tiro perforador con sangrado. Eliges una de cada nivel; los poderes de Stadium son diferentes.' },
  ],
  conclusion: 'En tu próxima VOD, sigue una sola rotación: la esquina desde la que disparabas, el lugar donde terminó Roll y la posición del Support que debía ayudarte. Si puedes señalar cuándo dejaste de tener cobertura o seguimiento, tendrás una corrección concreta que practicar. Acertar más ayuda, pero también necesitas seguir en una posición desde la que esos tiros importen.',
  links: [
    { href: '/guides/como-jugar-cassidy-ranked-overwatch', label: 'Practicar posición y duelos con Cassidy' },
    { href: '/counters/cassidy', label: 'Cómo puede el rival disputar la posición de Cassidy' },
    { href: '/team-comps/cassidy', label: 'Coordinar brawl y protección de la backline' },
    { href: '/maps/kings-row', label: 'Entradas por hotel y esquina de King’s Row' },
    { href: '/maps/midtown', label: 'Puertas y rotaciones de la estación de Midtown' },
    { href: '/heroes/genji', label: 'Entender las entradas y la salida de Genji' },
    { href: '/heroes/winston', label: 'Leer la preparación del dive de Winston' },
    { href: '/heroes/dva', label: 'Seguir Matrix y el peel de D.Va' },
    { href: '/heroes/reinhardt', label: 'Acompañar el avance de Reinhardt' },
    { href: '/roles/dps', label: 'Elegir qué amenaza atender como DPS' },
    { href: '/guides/como-mejorar-como-dps-overwatch', label: 'Revisar posición y prioridades de daño' },
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Comparar cooldowns antes de comprometer el duelo' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Revisar una rotación desde varias cámaras' },
    { href: '/experts', label: 'Pedir una revisión de tus posiciones y duelos' },
  ],
}
