import type { HeroPillar } from './hero-pillars'

export const reviewedAnaHero: HeroPillar = {
  slug: 'ana', name: 'Ana', role: 'Support', roleSlug: 'support',
  publishedAt: '2026-06-26', schemaDate: '2026-10-09', updatedAt: '9 de octubre de 2026',
  seoTitle: 'Ana en Overwatch: posición, Sleep, granada y Nano para ranked',
  seoDescription: 'Cómo jugar Ana en Overwatch: curar sin quedarte aislada, preparar Sleep y anti-nade, elegir el Nano y sobrevivir al dive. Ejemplos por mapa y revisión de VOD.',
  h1: 'Ana en Overwatch: cómo jugar con granada, Sleep y Nano',
  kicker: 'Curar desde cobertura y preparar la siguiente pelea',
  intro: [
    'Con Ana, empieza por una posición desde la que puedas curar y cubrirte sin perder a tu equipo de vista. Después decide qué amenaza necesita Sleep y qué enemigo podrá recibir daño si aciertas la granada. Nano no tiene que esperar siempre a Dragonblade: busca un compañero que pueda aprovecharlo en la pelea que está ocurriendo.',
    'Tener buen aim ayuda, pero no arregla una línea de curación cortada ni una entrada rival que no viste llegar. En Season 5, Local Anesthetic sustituye a Groggy y añade una explosión al impacto de Sleep, no al despertar. Más abajo tienes los perks actuales y ejemplos para acompañar una rotación, sobrevivir al dive y revisar por qué una granada no tuvo seguimiento.',
  ],
  headerTips: [
    'Posición: conserva una esquina y una línea hacia el compañero que va a recibir presión.',
    'Granada: mira quién puede disparar al objetivo después del anti, no solo cuántos enemigos alcanzas.',
    'Nano: elige a alguien que pueda alcanzar al rival o necesite protección para seguir peleando.',
  ],
  quickAnswers: [
    { title: 'Si estás muriendo al dive', body: 'Mira la ruta de entrada antes de abrir la mira. Acércate a una cobertura y a un compañero que pueda ayudar; dormir al primer enemigo no resuelve que el segundo llegue mientras sigues sola.' },
    { title: 'Si la granada no consigue bajas', body: 'Comprueba el seguimiento. Un Tank morado detrás de una esquina puede esperar a que termine el efecto sin recibir daño. Lanza la granada cuando tus DPS también puedan dispararle.' },
    { title: 'Si no sabes a quién dar Nano', body: 'Mira posición, recursos y estado de la pelea. Un Genji con Blade disponible pero sin acceso al rival puede aprovecharlo peor que un Winston que ya está disputando una altura con ayuda.' },
  ],
  facts: [
    { title: 'Tu trabajo', body: 'Mantener vivos a quienes están peleando y ayudar a conseguir una baja con Sleep, granada o Nano.' },
    { title: 'Posición inicial', body: 'Cobertura cercana, visión del siguiente cruce y una retirada que no atraviese la línea rival.' },
    { title: 'Daño del rifle', body: 'Una opción cuando el compañero expuesto está atendido; no una obligación entre cada cura.' },
    { title: 'Contra un flanker', body: 'Vigilar su ruta y tener ayuda cerca antes de que llegue, no depender de un Sleep cuando ya estás rodeada.' },
  ],
  rankedPlan: [
    'Antes de la pelea, mira dónde terminará tu Tank, no solo dónde está ahora. Si Winston va a saltar una plataforma en Gibraltar, busca desde dónde podrás curarlo al aterrizar sin exponerte tú a la defensa. No hace falta seguirlo a la misma altura.',
    'Identifica a quien puede llegar hasta ti. Una Tracer que desaparece por un lateral cambia lo que puedes permitirte con la mira abierta. Comprueba esa ruta, conserva una cobertura y avisa del lado por el que esperas presión antes de necesitar ayuda urgente.',
    'Decide para qué necesitas la granada. Puede salvar a un aliado bajo focus, cortar la curación de un enemigo o ayudarte a escapar. Si tus compañeros no pueden disparar al objetivo, espera a que salga de cobertura: ponerlo morado no asegura la baja.',
    'Cuando el equipo avance, muévete de una cobertura a la siguiente mientras aún puedes verlo. Si esperas hasta perder toda visión, quizá tengas que cruzar a campo abierto y gastar Sleep o granada solo para llegar a la nueva posición.',
    'Antes de Nano, comprueba que aún podéis ganar la pelea y que el aliado puede hacer algo con él. No esperes un combo perfecto si Winston ya tiene una buena entrada, pero tampoco lo gastes por reflejo sobre el único jugador que queda cuando el resto está volviendo del spawn.',
  ],
  sections: [
    { title: 'Distancia sin aislarte', body: 'Una posición de Ana es buena mientras permite ayudar y responder a lo que viene. Estar al fondo no garantiza seguridad: un flanker puede llegar sin que tus compañeros lo vean. Busca una esquina desde la que puedas acortar la distancia hacia tu otro Support sin cruzar el frente rival. Si tu Tank gira una esquina y deja de recibir curación, distingue si debes acompañar el giro o si ha avanzado solo hasta una zona que el equipo todavía no puede disputar.' },
    { title: 'Abrir la mira sin perder los laterales', body: 'La mira facilita seguir un objetivo lejano, pero también concentra tu atención en una parte de la pelea. Usa las pausas entre exposiciones para mirar la ruta de entrada y la posición del otro Support. Si siempre detectas a Genji cuando ya está pegado a ti, revisa qué estabas mirando antes de su llegada. El problema puede empezar mucho antes del flick que fallaste. Cerca de una puerta amenazada, conservar información importa más que mantener la mira abierta por comodidad.' },
    { title: 'La granada necesita un objetivo alcanzable', body: 'Antes del anti, mira dónde puede cubrirse el enemigo y quién podrá dispararle. Si el Tank rival asoma una esquina en King’s Row, espera a que salga lo suficiente para que varios compañeros lo vean; lanzarla demasiado pronto le permite volver a cubrirse. Una granada defensiva también puede ser la decisión correcta si salva a quienes están peleando. No la juzgues como mala solo porque no consiguió bajas: comprueba qué habría pasado con los aliados alcanzados sin esa ayuda.' },
    { title: 'Sleep: decide qué haces después de acertar', body: 'Si duermes a un enemigo que llegó a tu posición, comunica dónde está y usa el margen para cubrirte o reunirte con un compañero. No conviertas el acierto en una obligación de quedarte a rematarlo. Si viene acompañado, el segundo rival todavía puede presionarte. Por otro lado, reservar Sleep toda la partida no aporta nada: puede abrir una ocasión ofensiva cuando el objetivo está expuesto y el equipo tiene seguimiento. La amenaza que esperas y la ayuda disponible deciden cuánto riesgo puedes aceptar.' },
    { title: 'Gibraltar: preparar la curación antes del salto', body: 'Imagina que Winston y Genji van a entrar en una plataforma y hay una Widow en otra altura que te obliga a cubrirte. Antes del salto, busca desde qué esquina podrás verlos al aterrizar. Si después se alejan para perseguir una baja, no cruces el espacio abierto intentando curarlos a cualquier precio. Pídeles que vuelvan hacia el borde que puedes ver y atiende al compañero que sigue a tu alcance. Colócate antes de la entrada; correr detrás del dive suele dejarte expuesta y llegar tarde.' },
    { title: 'King’s Row: avanzar sin regalar la siguiente esquina', body: 'Después de ganar la pelea, no te quedes clavada en la posición anterior mientras el equipo sigue avanzando. Muévete hacia la siguiente esquina, pero mira también el lateral por el que podría volver un flanker. Si Reinhardt se gira para ayudar a vuestra backline, gira la cámara con él: seguir mirando al frente puede dejarte sin ver al compañero que necesita la cura. No des por hecho que la próxima pelea empezará delante de la carga.' },
  ],
  abilities: [
    { title: 'Biotic Rifle', body: 'El rifle cura aliados y daña enemigos; la mira permite apuntar a distancia. Elige el objetivo por la presión inmediata: un DPS que está expuesto puede necesitar ayuda antes que un Tank que se acaba de cubrir. Busca daño cuando puedas volver a la curación a tiempo, no porque un enemigo aparezca en el centro de la pantalla.' },
    { title: 'Sleep Dart', body: 'Duerme al enemigo alcanzado. Puedes usarlo para frenar a quien ha entrado en vuestra backline, ayudar a un compañero o dejar un rival expuesto al focus del equipo. Acertarlo no elimina a los demás enemigos de la pelea. Avisa y decide si podéis rematar o conviene retirarse, en lugar de gastar automáticamente el resto del kit sobre el objetivo dormido.' },
    { title: 'Biotic Grenade', body: 'Cura y aumenta la curación recibida por aliados; daña y bloquea curación en enemigos alcanzados. Úsala según lo que esté pasando: salvar al Tank que pelea por una esquina puede ser más urgente que buscar un anti. Y alcanzar a varios enemigos no aporta necesariamente más que salvar a un compañero si nadie puede seguir el daño.' },
    { title: 'Nano Boost', body: 'Aumenta el daño del aliado y reduce el daño que recibe. Comprueba si puede llegar al objetivo y qué recursos le quedan. Blade es una posibilidad, no el requisito de Nano. También puede acompañar la entrada de Winston o permitir a Reinhardt aguantar mientras pelea cerca del rival. Si el enemigo se retira, no lo persigas solo para justificar una ultimate que ya has gastado.' },
  ],
  perksIntro: 'Estas elecciones pertenecen al kit normal y se desbloquean durante la partida. Los poderes de Stadium son distintos: no conviertas una mejora de ese modo en una capacidad que Ana tenga siempre.',
  perks: [
    { title: 'Minor · Local Anesthetic', body: 'Sleep Dart explota al impactar, ralentiza y causa 45 de daño durante 3 segundos. Sustituye a Groggy desde Season 5: el efecto no espera a que el objetivo se despierte. Puede afectar a enemigos cercanos al impacto, pero no significa que todos queden dormidos. Si entra Winston con otro rival, usa ese margen para buscar ayuda; no te quedes sola esperando que el daño termine la pelea.' },
    { title: 'Minor · Speed Serum', body: 'Nano aporta también velocidad de movimiento a Ana y al objetivo. Esa movilidad puede ayudar a acompañar o recolocarte. No des por incluida esta mejora en cualquier Nano: es una elección alternativa a Local Anesthetic.' },
    { title: 'Major · Biotic Bounce', body: 'La granada rebota y produce una segunda explosión. Mira qué zona quedará al alcance de esa segunda aplicación; no prepares todo el seguimiento suponiendo que golpeará al mismo enemigo que la primera.' },
    { title: 'Major · Headhunter', body: 'Permite críticos del rifle sobre enemigos. Es una mejora ofensiva alternativa a Biotic Bounce; no añade críticos a tus curas. Aprovecha los tiros a la cabeza cuando haya margen, sin dejar de atender a un aliado que puede morir.' },
  ],
  balanceReview: [
    { title: '6 de octubre: Sleep con Local Anesthetic', body: 'Groggy salió del kit y la nueva Minor aplica su explosión al impacto. En una entrada rival con varios enemigos cerca, mira a quién alcanzó el dardo y quién sigue pudiendo atacarte: ralentizar alrededor no equivale a dormir al grupo. En la VOD, separa el acierto de Sleep de lo que hiciste después. Reunirte con tu otro Support puede aportar más que gastar granada para rematar mientras el segundo flanker continúa disparando.' },
  ],
  mistakes: [
    'Juzgar la posición solo por cuánto pudiste curar. Revisa si tenías una salida cuando entró el flanker y si otro compañero podía ayudarte sin abandonar todo el frente.',
    'Llamar «granada de pánico» a cualquier autocuración. Usarla para sobrevivir puede ser correcto. Revisa por qué te alcanzó el rival, qué cobertura tenías y si sobrevivir te permitió seguir ayudando en la pelea.',
    'Gastar Sleep y granada sobre el mismo primer rival sin mirar al segundo. A veces necesitas ambos para sobrevivir; otras, el objetivo dormido ya dejó de ser la amenaza inmediata y puedes conservar una respuesta.',
    'Esperar siempre Nano-Blade. Una ultimate disponible no asegura que Genji tenga ruta o ayuda. Mira también qué puede hacer vuestro Tank en el contacto actual antes de decidir que debes guardar Nano para otro momento.',
    'Seguir apuntando hacia delante mientras el equipo cambia de dirección. Cuando el Tank se cubre o vuelve a ayudar, cambia también tu prioridad. No cruces sola una línea rival para recuperar un objetivo que ya no está disputando allí.',
  ],
  counters: [
    { title: 'Winston', body: 'Puede llegar a tu posición y alterar las líneas con su burbuja. Prepara una cobertura y una zona de ayuda antes del salto. Si la burbuja separa al equipo, busca una línea exterior razonable sin caminar hacia el centro del rival solo para recuperar una cura.' },
    { title: 'Tracer', body: 'Un lateral corto le permite repartir tu atención entre curar y defenderte. Avisa de la ruta, acorta la distancia hacia un compañero y no persigas el Recall dejando de atender el frente. El siguiente objetivo puede ser otro aliado, no tú.' },
    { title: 'Genji', body: 'Puede entrar desde otra altura y devolver Sleep con Deflect. No tires el dardo de frente mientras está desviando. Frente a Blade, prepara ayuda y retirada; no dejes toda la defensa pendiente de acertar un Sleep cuando ya lo tienes encima.' },
    { title: 'Widowmaker', body: 'Su línea larga limita desde dónde puedes curar con seguridad. Acorta la exposición desde una esquina o cambia de ruta. Tener visión del Tank no basta si para cada disparo tienes que atravesar la misma línea que ella está esperando.' },
  ],
  counterplay: [
    'Contra dive, prepara el punto de ayuda con tu otro Support. Si solo os reunís después de la primera muerte, revisad las posiciones iniciales y no únicamente los cooldowns fallados.',
    'Contra una línea de sniper, comprueba una ruta más corta y qué parte del avance puedes curar sin exponerte. Pedir al Tank que espere un cruce puede ser más útil que intentar acertar un tiro difícil desde campo abierto.',
    'Si varias entradas comparables siguen dejándote sin visión o sin ayuda, valora otra opción que conozcas. Cambiar a Kiriko añade movilidad, pero no arregla un teleport hacia un compañero rodeado. Explica qué problema intentas resolver con el swap.',
  ],
  compositions: [
    { title: 'Winston y un DPS que siga el salto', body: 'Puedes curar a Winston desde otra posición y darle Nano cuando ya pueda alcanzar al rival. En Gibraltar, elegid una plataforma a la que vuestro Genji o Tracer también pueda llegar y comprueba desde dónde vas a curarlos. Si saltan antes de colocaros, quizá pierdas visión nada más entrar. Acordad también por dónde volver: perseguir una baja hasta otra habitación puede dejar el dive sin curación.' },
    { title: 'Reinhardt y avance de grupo', body: 'Cura a Reinhardt mientras cruza y prepara la granada para cuando el rival salga a pelear a corta distancia. Si lleváis Lúcio, su velocidad puede ayudar a llegar; Nano no convierte cualquier cruce abierto en una entrada segura. Acércate por cobertura antes de perder al grupo de vista y vigila quién puede entrar por detrás mientras todos miran hacia la esquina.' },
    { title: 'Sigma y presión desde dos líneas', body: 'Mientras Sigma aguanta el frente, un DPS puede disparar desde otro ángulo. Comprueba si puedes curar a ese compañero cuando lo contesten; mirar solo al Tank puede dejar sin ayuda a quien estaba obligando al rival a girarse. No necesitas seguir al DPS a su esquina, pero sí saber cuándo va a asomar y dónde puede volver a recibir curación.' },
  ],
  vodReview: [
    'Escoge una primera muerte y retrocede hasta antes de la pelea. Mira dónde estaban el Tank y el otro Support, y por dónde llegó quien te mató. Comprueba si tenías cobertura y una ruta hacia ayuda antes de centrar toda la revisión en el Sleep fallado.',
    'Revisa una granada ofensiva: qué objetivo alcanzó, quién tenía tiro y qué cobertura usó el enemigo después. Si nadie pudo seguirla, busca un momento posterior de exposición o una posición distinta, no solo un lanzamiento más preciso.',
    'Revisa una granada defensiva sin llamarla mala de entrada. ¿Qué aliado recibió el efecto y qué pudo seguir haciendo? Después mira si conservar una esquina habría evitado necesitarla. Son dos preguntas diferentes.',
    'Pausa un Nano antes de lanzarlo. Mira ruta, recursos del aliado y jugadores vivos. Compara el plan disponible con lo que ocurrió; una baja conseguida no prueba que todas las siguientes ultimates deban darse al mismo jugador.',
    'En una rotación, busca el momento en que dejaste de ver al equipo. Comprueba si giró una esquina mientras tú seguías en la posición anterior. Trabaja primero cómo acompañar ese avance desde cobertura, en vez de intentar arreglarlo con un flick más rápido.',
  ],
  checklist: [
    '¿Desde aquí podré curar a mi Tank cuando entre?',
    '¿Por qué ruta puede llegar la amenaza a mi posición?',
    '¿Quién puede ayudarme si gasto Sleep?',
    '¿Qué compañero puede seguir mi granada ofensiva?',
    '¿El objetivo de Nano tiene ruta y recursos?',
    '¿Puedo acompañar el avance sin cruzar una línea abierta?',
  ],
  faqs: [
    { question: '¿Dónde debería colocarme con Ana?', answer: 'En una cobertura desde la que veas el siguiente contacto y puedas acercarte a ayuda si llega presión lateral. No hay una distancia fija correcta: cambia con el avance del Tank, los ángulos rivales y la posición del otro Support.' },
    { question: '¿Está mal usar la granada para curarme?', answer: 'No. Puede darte el margen necesario para sobrevivir y seguir ayudando. Revisa por separado si hacía falta gastarla y si una posición previa distinta habría evitado la presión; no la clasifiques como mala solo por ser defensiva.' },
    { question: '¿Debo reservar siempre Nano para Genji?', answer: 'No. Valora qué aliado tiene acceso al rival, recursos y una acción útil en la pelea actual. Genji con Blade es una opción, pero Winston o Reinhardt pueden aprovechar otra oportunidad antes. Guardarlo sin un plan también puede desperdiciar una pelea disputable.' },
    { question: '¿Por qué mi anti-nade no consigue bajas?', answer: 'Puede faltar seguimiento o el objetivo puede cubrirse antes de recibir daño. Mira quién tenía tiro al acertarla y qué ruta usó el rival. Preparar la granada para una exposición común suele importar más que alcanzar a muchos enemigos protegidos.' },
    { question: '¿Qué hace Local Anesthetic y sigue existiendo Groggy?', answer: 'Local Anesthetic es la Minor que sustituyó a Groggy el 6 de octubre. Sleep Dart explota al impactar, ralentiza enemigos y causa 45 de daño durante 3 segundos. No es el antiguo efecto al despertar ni convierte la ralentización de los enemigos cercanos en un Sleep para todos. Speed Serum es la otra opción Minor.' },
    { question: '¿Cuándo conviene cambiar de Ana?', answer: 'Cuando una limitación se repite en peleas comparables pese a ajustar posición, ruta y ayuda, y conoces otra opción que pueda resolverla. Una muerte aislada no demuestra que el pick sea el problema; explica qué cambiará con el nuevo héroe.' },
  ],
  conclusion: 'En tu próxima VOD, escoge un Sleep acertado y una granada sin baja. Mira quién seguía amenazándote tras el dardo y qué compañero podía disparar después del anti. Así sabrás si necesitas cambiar de posición, avisar antes o esperar otro momento; practicar más aim no resuelve por sí solo esas tres decisiones.',
  links: [
    { href: '/guides/como-jugar-ana-ranked-overwatch', label: 'Practicar las decisiones de Ana en ranked' },
    { href: '/counters/ana', label: 'Adaptarte a las amenazas de Ana' },
    { href: '/team-comps/ana', label: 'Preparar el equipo alrededor de Ana' },
    { href: '/roles/support', label: 'Posiciones y prioridades de Support' },
    { href: '/heroes/kiriko', label: 'Valorar una alternativa con Kiriko' },
    { href: '/heroes/genji', label: 'Entender el timing de Genji' },
    { href: '/maps/watchpoint-gibraltar', label: 'Preparar las líneas de Gibraltar' },
    { href: '/maps/kings-row', label: 'Acompañar los cruces de King’s Row' },
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Seguir Sleep y granada en el replay' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Comparar decisiones en una VOD' },
    { href: '/doctrine-support-sombra-roadhog-rework-overwatch', label: 'Qué ha cambiado con Season 5' },
    { href: '/experts', label: 'Pedir ayuda con una partida de Ana' },
  ],
}
