import type { HeroPillar } from './hero-pillars'

export const reviewedDmonHero: HeroPillar = {
  slug: 'dmon', name: 'D.Mon', role: 'Tank', roleSlug: 'tank',
  publishedAt: '2026-08-06', schemaDate: '2026-10-04', updatedAt: '4 de octubre de 2026',
  seoTitle: 'D.Mon en Overwatch: barrera, Propulsors, perks y counters',
  seoDescription: 'Acércate con Beast sin agotar barrera y combustible. Cómo usar Plasma Saber, Fusion Repeater y Limit Break, jugar como piloto y responder a sus counters.',
  h1: 'D.Mon en Overwatch: acercarte con Beast sin quedarte aislada',
  kicker: 'MEKA · espada, barrera frontal y movilidad horizontal',
  intro: [
    'Con D.Mon, llegar hasta el enemigo no basta. Si vacías el combustible y la barrera para alcanzar a un Cassidy que se retira, puedes acabar frente a todo su equipo sin una esquina a la que volver. Antes de usar Propulsors, elige dónde quieres parar y comprueba que tus Supports pueden curarte allí.',
    'Beast combina la presión cercana de Plasma Saber con Power Barrier y Fusion Repeater. No tiene el vuelo de D.Va: para responder a una altura necesitas un acceso, ayuda de otro compañero o una pelea en otra zona. Esta guía explica cómo elegir esos cruces, qué cambia con los perks y qué hacer si pierdes el mech. También recoge los ajustes de septiembre, para no jugar con los valores del lanzamiento en mente.',
  ],
  headerTips: [
    'Cruza hasta una cobertura que tus compañeros puedan alcanzar, no hasta el enemigo más lejano.',
    'Usa una pared para cerrar el ángulo que Power Barrier no está cubriendo.',
    'Antes de Limit Break, mira quién tiene tiro y munición sobre los objetivos del corte.',
  ],
  quickAnswers: [
    { title: 'Si pierdes la barrera antes de acercarte', body: 'Revisa dónde la desplegaste. Mantenerla mientras el grupo sigue detrás puede consumirla sin permitir ningún avance. Espera en cobertura hasta que estén preparados y protégeles durante el tramo que sí necesitan cruzar. Si hay dos ángulos, cambia de ruta o tapa uno con el escenario; girar la barrera no elimina ambos.' },
    { title: 'Si llegas sin combustible para volver', body: 'Mira la primera posición donde ya podías presionar. Quizá te bastaba con esa esquina y gastaste el resto siguiendo una retirada. Puedes detenerte, usar Fusion Repeater y dejar que el equipo llegue. No necesitas terminar cada uso de Propulsors junto al objetivo ni perseguirlo hasta su backline.' },
    { title: 'Si te destruyen Beast', body: 'Como piloto ya no puedes sostener el mismo frente. Tápate, dispara desde una posición con ayuda y busca un lugar protegido para Call Mech cuando esté disponible. Si la pelea está perdida y el grupo se retira, salir con él puede ser más útil que reensamblar el mech en medio del rival y perderlo otra vez.' },
  ],
  facts: [
    { title: 'Quién pilota Beast', body: 'Yuna Lee, D.Mon, lidera el escuadrón MEKA de Busan. Comparte escuadrón e historia con D.Va, pero sus herramientas de movimiento y defensa son distintas.' },
    { title: 'Disponible desde Season 4', body: 'Se incorporó como Tank el 11 de agosto de 2026, con Heroes of Busan. Puedes jugarla en el roster de Tanks; los ajustes posteriores cambiaron la armadura y el ritmo de algunos recursos.' },
    { title: 'La barrera tiene frente', body: 'Importa hacia dónde la orientas y desde dónde dispara el rival. La cobertura del mapa permite protegerte de una dirección sin gastar barrera en ella.' },
    { title: 'Último parche de balance revisado', body: '17 de septiembre de 2026. Los ajustes anteriores del 8 de septiembre se distinguen en la sección de balance; las cifras de 5v5 y 6v6 no son intercambiables.' },
  ],
  rankedPlan: [
    'Desde cobertura, identifica el próximo tramo abierto, quién os dispara y dónde podrá detenerse el grupo. No elijas una llegada que obligue a tus Supports a cruzar otra línea peligrosa para ayudarte.',
    'Cuando el equipo esté cerca, protege el cruce necesario y utiliza Propulsors con un destino corto. Mira cuánto combustible y barrera conservas al llegar antes de iniciar otra persecución.',
    'Si el enemigo sigue a rango, puedes presionar con Plasma Saber. Si retrocede, decide entre mantener la esquina, usar Fusion Repeater o continuar con ayuda. Que aún puedas moverte no significa que debas seguir.',
    'Frente a un flanco, usa el escenario para cerrar una dirección y avisa del otro atacante. Si te giras del todo, revisa qué línea queda abierta hacia los compañeros que estaban detrás de ti.',
    'Después del intercambio, recupera recursos junto al equipo. Prepara Limit Break para objetivos a los que tus DPS puedan disparar, no para un corte espectacular mientras todavía están volviendo del spawn.',
  ],
  sections: [
    { title: 'Ganar una esquina puede ser suficiente', body: 'Imagina que el rival retrocede al verte entrar y tus compañeros ya pueden cruzar hasta la cobertura que ocupabas. Has conseguido una posición mejor aunque no mates a nadie. Si continúas detrás del Tank hasta otra habitación, puedes perder las curas y dejar al equipo frente a un flanco. Mira qué permite la nueva esquina: avanzar el objetivo, cambiar el ángulo de Cassidy o reunir al grupo. No conviertas toda retirada rival en una orden de perseguir.' },
    { title: 'Surging Strike: mira dónde dejas al enemigo', body: 'El desplazamiento puede sacar al objetivo de una cobertura o apartarlo de un compañero, pero también puede empujarlo fuera del tiro aliado. Antes del golpe, mira por dónde dispara tu DPS. Si Cassidy tiene visión junto a ti, dejar al enemigo expuesto puede facilitar el remate; si lo mandas detrás de otra pared, quizá lo ayudes a salir. Después comprueba tu posición: acertar no resuelve el duelo si tú terminas recibiendo focus sin apoyo.' },
    { title: 'Lijiang, Control Center: no entres mientras el grupo sigue fuera', body: 'El interior favorece intercambios cercanos, pero varias entradas pueden dividir vuestra atención. Si avanzas hacia el punto y Ana sigue cubriéndose antes de la puerta, la espada no compensa perder sus curas. Detente donde el grupo pueda reunirse y mira por qué acceso está entrando el otro DPS. Con el punto capturado, presiona una llegada cercana sin perseguir a alguien por los pasillos mientras otro enemigo ocupa el objetivo.' },
    { title: 'Busan, MEKA Base: no respondas a cada altura mirando arriba', body: 'Si un rival tiene tiro desde una plataforma y el otro Tank se acerca por el suelo, decide qué amenaza podéis disputar ahora. Otro compañero puede presionar al ocupante mientras tú proteges un cruce; también podéis buscar un acceso cubierto para cambiar de posición. Gastar Propulsors contra la base de la altura no te coloca arriba. Mira desde dónde se puede seguir el daño y conserva barrera para el tramo expuesto, en lugar de quedarte bajo dos líneas de tiro.' },
    { title: 'Perder el mech no obliga a regalar también a la piloto', body: 'Tras Eject!, vuelve a una posición desde la que puedas disparar sin mantener el frente de Beast. Comprueba si los compañeros están ganando o intentando salir: eso cambia dónde te conviene reensamblar el mech. Call Mech más rápido no equivale a una vuelta instantánea y segura. Si lo usas delante de varios enemigos con el equipo lejos, puedes recuperar Beast y perderlo sin conseguir un nuevo intercambio.' },
    { title: 'Limit Break necesita seguimiento, no cinco objetivos', body: 'Un enemigo accesible puede ser más útil que varios situados detrás de una esquina que tus DPS no ven. El corte amplifica el daño que reciben: comprueba qué pueden aportar los compañeros durante esa oportunidad. No tienes que añadir otra ultimate por costumbre si el daño normal basta. Si una defensa rival permite aguantar, decide si podéis seguir, cambiar de objetivo o conservar el resto de recursos; haber acertado el corte no garantiza las bajas.' },
  ],
  abilityKit: { src: '/heroes/dmon-ability-kit.png', alt: 'Beast y el kit de D.Mon: espada, barrera, Propulsors, armas, ultimates y perks', width: 1920, height: 1080, caption: 'Las habilidades de Beast y de la piloto, con las alternativas Minor y Major.' },
  abilities: [
    { title: 'Plasma Saber', body: 'La espada de energía presiona a corta distancia. Úsala sobre el enemigo que puedes mantener a rango sin salir de las curas. Si retrocede hacia sus compañeros, valora quedarte en la esquina que deja; no necesitas vaciar el combustible para conseguir otro golpe.' },
    { title: 'Power Barrier', body: 'Mantienes una barrera frontal. Orientarla hacia el rival del frente no tapa automáticamente al atacante del lateral. Antes de gastarla contra poke, comprueba si estás protegiendo un cruce real. Si todos seguís en cobertura, puedes conservarla para el momento en que salgáis.' },
    { title: 'Propulsors', body: 'Consume combustible para desplazarte en horizontal. Permite cerrar una distancia o volver a cobertura, pero no funciona como el vuelo de Boosters de D.Va. Elige dónde parar mirando también el camino de vuelta; un desplazamiento largo que termina sin reserva puede dejarte expuesta al siguiente focus.' },
    { title: 'Fusion Repeater', body: 'La ametralladora del mech permite presionar cuando la espada no llega. Dispara desde una línea que puedas sostener con el equipo y aprovecha la cobertura entre usos. No resuelve por sí sola una altura si otro ángulo te obliga a taparte antes de poder mantener el tiro.' },
    { title: 'Surging Strike', body: 'Con Power Barrier desplegada, golpeas hacia delante para hacer daño y empujar. Decide si buscas apartar una amenaza de un aliado o dejar a un enemigo expuesto al daño del grupo. No son el mismo destino: mira dónde terminará antes de golpear.' },
    { title: 'Limit Break', body: 'El corte amplio aporta overhealth propio y amplifica el daño recibido por los enemigos alcanzados. Avisa al equipo y comprueba su visión antes de usarlo. El overhealth es un margen defensivo; no permite ignorar un flanco ni obliga a los compañeros que están lejos a llegar a tiempo.' },
    { title: 'Eject!', body: 'Sales de Beast cuando lo destruyen. La fase de piloto requiere otra posición: tápate y utiliza el daño desde un lugar con ayuda. Seguir ocupando el mismo frente sin el mech puede regalar la segunda baja.' },
    { title: 'Portable Fusion Repeater', body: 'Es el arma de la piloto, no la ametralladora activable de Beast. Puedes añadir daño desde cobertura mientras buscas recuperar el mech. No mantengas una línea larga solo porque el arma dispara: también importa si el enemigo puede contestarte y cuánto se reduce el daño a distancia.' },
    { title: 'Call Mech', body: 'Reensambla Beast. Mira qué enemigos tienen tiro sobre el lugar y si tus compañeros pueden ayudarte al volver. Si el grupo ya está saliendo, reentrar en el centro de la pelea puede dejarte aislada de nuevo. La transformación tiene su tiempo; no la confundas con una defensa instantánea.' },
    { title: 'Stalwart', body: 'El subrol reduce los empujes y las ralentizaciones recibidas. No es inmunidad a todo el control ni una forma de recuperar combustible. Sigue preparando cobertura y seguimiento, aunque un boop te desplace menos.' },
  ],
  perksIntro: 'En las partidas con perks eliges una Minor al nivel 2 y una Major al nivel 3. Las opciones de cada nivel son alternativas, no cuatro mejoras simultáneas. Estas elecciones pertenecen al kit normal de D.Mon; no añaden poderes de Stadium de otros héroes MEKA.',
  perks: [
    { title: 'Minor · Beast Within', body: 'Los golpes de Plasma Saber recuperan 40 de salud de Power Barrier. Recuperas la barrera, no tu propia vida. Puede ayudar si mantienes un objetivo cerca, pero perseguirlo sin curas para reparar el escudo puede costarte el mech.' },
    { title: 'Minor · MEKA Mobility', body: 'Reduce un 30% el consumo de Propulsors mientras mantienes Power Barrier y es alternativa a Beast Within. Puede dejar más combustible tras un cruce protegido. Aun así, mira la reserva al llegar: el descuento no convierte un trayecto largo en una retirada garantizada.' },
    { title: 'Major · Overstrike', body: 'Surging Strike gana un 150% de lifesteal. La recuperación depende del daño de ese golpe, no de todos los ataques de Beast. Busca una amenaza cercana a la que puedas acertar sin abandonar al grupo; el perk no justifica recibir focus esperando curarte después.' },
    { title: 'Major · Focused Fusion', body: 'Fusion Repeater dispara golpes más fuertes, sin dispersión y a menor cadencia. Es alternativa a Overstrike. Puede ayudarte a seguir un objetivo desde una línea útil, pero ahora necesitas aprovechar cada disparo; no es una solución automática para pelear por una calle abierta sin cobertura.' },
  ],
  balanceReview: [
    { title: '8 de septiembre: espada, barrera y piloto', body: 'Plasma Saber pasó de 65 a 60 de daño. Power Barrier despliega más rápido y Call Mech redujo su transformación de 1,95 a 0,95 segundos, añadiendo una animación de arranque de un segundo. El arma de piloto ganó precisión, pero el falloff empieza a 20 metros en vez de 30. Si comparas un replay antiguo, separa el tiempo de transformación de la animación y la precisión del daño a distancia.' },
    { title: '17 de septiembre: menos margen al cruzar', body: 'La armadura bajó de 325 a 275 en 5v5 y de 300 a 250 en 6v6. Propulsors aumentó su consumo de 25 a 30; Fusion Repeater bajó de 16 a 15 de daño y pasó de 4 a 5 segundos de cooldown. Focused Fusion redujo el daño por bala de 45 a 36. Revisa la distancia del cruce y qué conservas al llegar: no copies las reservas ni el ritmo de disparo de una guía del lanzamiento.' },
  ],
  mistakes: [
    'Mantener la barrera mientras los compañeros siguen preparándose detrás. Sigue cuándo empieza a cruzar cada uno: quizá consumiste la protección antes de que pudieran aprovecharla.',
    'Seguir a un enemigo que retrocede después de ganar una esquina. Mira el primer lugar desde el que ya podías presionar y cuánto combustible gastaste después; puede que la persecución te sacara de las curas.',
    'Girar la barrera hacia un flanco sin mirar al frente. Comprueba qué compañeros quedaron expuestos mientras contestabas al lateral y si una pared permitía cerrar esa dirección.',
    'Empujar al objetivo detrás de una cobertura. Revisa la cámara del DPS que intentaba rematarlo: acertar Surging Strike puede haber cortado su tiro.',
    'Tratar Beast Within como una cura propia. Mira la salud del mech por separado de la barrera; reparar el escudo no devuelve la vida que ya perdiste.',
    'Reensamblar Beast cuando el equipo ya ha perdido la pelea. Comprueba si había ayuda a tu llegada y qué habría ocurrido saliendo con los compañeros, sin regalar otra entrada aislada.',
  ],
  counters: [
    { title: 'Ana', body: 'Mira desde dónde puede lanzar Sleep y granada antes del cruce. Una barrera hacia el frente no evita que te amenace desde un lateral. Si recibes anticuración, busca cobertura y deja pasar esa amenaza; pedir más curas no resuelve el bloqueo mientras siga activo. Cuando veas un recurso gastado, comprueba también quién puede seguirte antes de avanzar.' },
    { title: 'Zarya y Symmetra', body: 'Pueden presionar en intercambios cercanos sostenidos. Frente a Zarya, mira si su burbuja está absorbiendo el daño que intentas añadir y si tienes otro objetivo accesible; contra Symmetra, atiende a las torretas que dificultan el cruce. No prolongues el duelo solo porque ambos estén cerca de la espada. La salud, la ayuda y la posibilidad de taparte importan más que el nombre del matchup.' },
    { title: 'Reaper', body: 'Si entra por un lateral mientras miras al Tank, puede atacarte de cerca sin quedar delante de la barrera. Avisa y reúne el daño del grupo en vez de perseguirlo hasta otra habitación. Cuando se retire con Wraith, recupera tu posición y mira al frente; no necesitas gastar el combustible restante siguiendo una retirada que su equipo puede cubrir.' },
    { title: 'Pharah, Echo y snipers', body: 'Su alcance o posición vertical puede obligarte a exponerte antes de poder contestar. Puedes presionar con Fusion Repeater cuando hay tiro, pero Propulsors no te sube automáticamente a su plataforma. Busca otro acceso o coordina qué compañero disputa esa línea. Si miras arriba todo el tiempo, el otro Tank puede avanzar mientras tu equipo sigue bajo el mismo ángulo.' },
    { title: 'Zenyatta', body: 'Discord hace más peligroso el focus durante el tramo abierto. Comprueba quién más te está disparando y vuelve a cobertura si el cruce dejó de ser sostenible. No sigas hasta Zen solo porque lo veas: llegar a él sin combustible ni curas puede exponer a todo el grupo a otra dirección.' },
    { title: 'Sombra', body: 'En su kit actual de DPS, la presión lateral y Hack pueden complicar el momento de moverte. Mira dónde están tus Supports y qué esquina puedes alcanzar si interrumpe tu plan. Esto no describe su futuro rework de Support anunciado para Season 5: no presupongas que todas las interacciones serán iguales después de ese cambio.' },
  ],
  counterplay: [
    'Si el rival os dispara desde dos direcciones, cambia la cobertura o el recorrido antes de consumir toda la barrera. El objetivo es llegar con recursos para pelear, no demostrar que puedes aguantar cada tiro en main.',
    'Si el enemigo espera tu entrada para gastar una defensa, presiona desde la esquina y observa qué utiliza contra el equipo. No tienes que comprometer toda la movilidad para conseguir información; entra cuando haya una oportunidad que tus compañeros puedan seguir.',
    'Si necesitáis disputar alturas repetidamente y ninguna ruta permite llegar con ayuda, considera un Tank que sepas jugar allí. Antes del swap, comprueba si el problema fue el acceso o salir mientras el equipo todavía estaba reuniéndose; el segundo se repetirá con otro héroe.',
  ],
  compositions: [
    { title: 'Brawl 5v5 con Mei o Cassidy', body: 'D.Mon ocupa el puesto de Tank y prepara una llegada que ambos puedan seguir. Mei puede limitar una salida y Cassidy añadir daño sobre el enemigo que queda expuesto. Comprobad que la pared no corta las curas ni separa al grupo. Ganar la esquina juntos permite sostener el intercambio; cruzar cada uno por una puerta distinta puede dejar Beast recibiendo daño solo.' },
    { title: 'Rush con Lucio y Kiriko', body: 'La velocidad ayuda a recorrer el tramo abierto, pero decidid antes dónde vais a parar. Kiriko puede responder a anticuración con Suzu; no la tratéis como una limpieza universal de cualquier derribo ya aplicado. Si llegáis sin sus recursos defensivos, reducid la persecución y mantened una cobertura desde la que los Supports puedan seguir participando.' },
    { title: 'Doble MEKA solo en formatos con dos Tanks', body: 'Con D.Va aliada, una puede disputar una altura mientras D.Mon mantiene el acceso cercano. Esa pareja no cabe en la cola por roles 5v5, que tiene un único puesto de Tank. En 6v6 o un formato que lo permita, repartid primero quién ayuda a los Supports y quién avanza; no mandéis ambos mechs lejos suponiendo que el otro protege al grupo.' },
  ],
  vodReview: [
    'Elige un cruce con Propulsors. Pausa al salir y al llegar: anota cobertura, combustible, barrera y posición de los Supports. Después mira si podrías haber parado antes manteniendo presión.',
    'Sigue una barrera que se agotó pronto. Comprueba cuándo empezaron a pasar los compañeros y qué ángulos disparaban. Separa proteger un movimiento de mantener el escudo mientras todos esperan.',
    'Mira Surging Strike desde la cámara del DPS que estaba siguiendo. Anota si el objetivo quedó expuesto o desapareció detrás de una pared y dónde terminaste tú.',
    'Revisa Limit Break desde el momento previo al corte. Comprueba munición, tiro y defensas rivales. Un corte acertado sin ayuda necesita otro ajuste distinto de uno que no alcanzó al objetivo.',
    'Sigue una pérdida de Beast hasta la siguiente decisión como piloto. Mira dónde te tapaste, si el grupo podía ayudarte y si Call Mech permitió volver a una pelea viva o solo retrasó la retirada.',
  ],
  checklist: [
    '¿En qué cobertura termina este uso de Propulsors?',
    '¿Mis Supports pueden verme en la llegada?',
    '¿Qué dirección estoy dejando abierta con la barrera?',
    '¿Tengo combustible para corregir la posición después?',
    '¿Quién puede seguir el daño de Limit Break?',
    '¿Dónde me tapo como piloto si perdemos Beast?',
  ],
  faqs: [
    { question: '¿Quién es D.Mon y cuándo salió?', answer: 'D.Mon es Yuna Lee, la líder de MEKA que pilota Beast. Es Tank y está disponible desde el 11 de agosto de 2026, con Season 4: Heroes of Busan. Comparte escuadrón con D.Va, pero no sus herramientas de vuelo y Matrix.' },
    { question: '¿Propulsors permite subir como los Boosters de D.Va?', answer: 'No: consume combustible para desplazarte en horizontal. Para disputar una altura necesitas un acceso que puedas recorrer o ayuda de otro compañero. Si no podéis acercaros con recursos, cambiar la zona de pelea puede ser mejor que quedarte debajo mirando arriba.' },
    { question: '¿Cuáles son las habilidades de Beast y de la piloto?', answer: 'Beast utiliza Plasma Saber, Power Barrier, Propulsors, Fusion Repeater, Surging Strike y Limit Break. Eject! te saca cuando destruyen el mech; fuera usas Portable Fusion Repeater y Call Mech para reensamblarlo. El arma de piloto no es la ametralladora activable de Beast.' },
    { question: '¿Beast Within cura a D.Mon?', answer: 'Recupera 40 de salud de Power Barrier al acertar Plasma Saber. Repara la barrera, no la vida del mech. Mira ambas barras por separado y no persigas un objetivo sin curas esperando que ese perk recupere tu salud.' },
    { question: '¿Overstrike da lifesteal a todos los ataques?', answer: 'No: añade un 150% de lifesteal a Surging Strike. No se aplica automáticamente a la espada o a Fusion Repeater. La recuperación depende del golpe; no lo uses como excusa para recibir focus lejos del equipo.' },
    { question: '¿Qué hace Limit Break y cuándo conviene usarlo?', answer: 'El corte aporta overhealth propio y amplifica el daño recibido por los enemigos alcanzados. Úsalo sobre objetivos a los que tus compañeros puedan disparar con recursos preparados. No necesitas alcanzar a cinco si una baja importante puede resolver la pelea.' },
    { question: '¿D.Mon con D.Va es una composición de 5v5?', answer: 'No en cola por roles 5v5: ambas ocupan el único puesto de Tank. La pareja se puede plantear en 6v6 o un formato que permita dos Tanks. Revisad también el balance de ese modo, incluida la armadura de Beast, antes de copiar un plan de otra cola.' },
    { question: '¿Qué hago si no puedo acercarme al equipo rival?', answer: 'Comprueba la ruta, la llegada y el momento del grupo antes del swap. Una cobertura distinta puede reducir el poke; otro compañero puede disputar una altura mientras cruzáis. Si aun así el mapa exige acceso vertical constante, considera un Tank que pueda hacerlo y que sepas jugar, sin esperar que el cambio arregle entrar solo.' },
  ],
  conclusion: 'En la próxima VOD, sigue un cruce y una pérdida de Beast. Mira qué recursos conservabas al llegar y si el equipo podía ayudarte cuando pasaste a piloto. Así sabrás si necesitas acortar el recorrido, esperar a tus Supports o elegir otra cobertura; no basta con culpar al matchup después de cada muerte.',
  links: [
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Seguir barrera y combustible durante una pelea' },
    { href: '/counters/dmon', label: 'Matchups y respuestas frente a D.Mon' },
    { href: '/team-comps/dmon', label: 'Organizar el equipo alrededor de Beast' },
    { href: '/maps/lijiang-tower', label: 'Entradas y posiciones en Lijiang Tower' },
    { href: '/maps/busan', label: 'Las distintas zonas de Busan' },
    { href: '/heroes/dva', label: 'Cuándo la movilidad de D.Va resuelve otra tarea' },
    { href: '/heroes/ana', label: 'El posicionamiento y las curas de Ana' },
    { href: '/heroes/kiriko', label: 'Preparar Suzu y el seguimiento con Kiriko' },
    { href: '/heroes/cassidy', label: 'Seguir el daño de cerca con Cassidy' },
    { href: '/roles/tank', label: 'Decisiones del rol de Tank' },
    { href: '/guides/como-mejorar-como-tank-overwatch', label: 'Crear espacio sin perder la ayuda del equipo' },
    { href: '/guides/como-usar-ultimates-overwatch', label: 'Preparar el seguimiento de una ultimate' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Revisar secuencias concretas en el replay' },
    { href: '/overwatch-temporada-4-heroes-of-busan', label: 'Las novedades de Heroes of Busan' },
    { href: '/dmon-nuevo-heroe-tank-overwatch', label: 'El anuncio de D.Mon' },
    { href: '/busan-eichenwalde-paraiso-reworks-overwatch', label: 'Los cambios de Busan, Eichenwalde y Paraíso' },
    { href: '/experts', label: 'Pedir una revisión de tus entradas con Beast' },
  ],
}
