import type { HeroPillar } from './hero-pillars'

export const reviewedDvaHero: HeroPillar = {
  slug: 'dva', name: 'D.Va', role: 'Tank', roleSlug: 'tank',
  publishedAt: '2026-06-26', schemaDate: '2026-10-04', updatedAt: '4 de octubre de 2026',
  seoTitle: 'D.Va en Overwatch: Matrix, Boosters y peel en ranked',
  seoDescription: 'Cuándo subir con D.Va, volver a ayudar a tus Supports y guardar Matrix. Perks, Self-Destruct y decisiones al perder el mech, con ejemplos de Gibraltar y Dorado.',
  h1: 'D.Va en Overwatch: cuándo entrar y cuándo volver',
  kicker: 'Disputar alturas sin dejar al equipo sin ayuda',
  intro: [
    'Con D.Va puedes subir a por un DPS, volver a proteger a Ana o cubrir la entrada de Genji. El problema es querer hacerlo todo en la misma pelea. Antes de usar Boosters, elige qué amenaza necesitas atender y una posición desde la que puedas seguir ayudando cuando termine el vuelo.',
    'Matrix permite negar disparos y habilidades importantes, pero no sustituye una pared ni protege en todas las direcciones. Esta guía explica cómo repartir ese recurso, cuándo dejar una persecución y qué hacer si pierdes el mech. La bomba también tiene su apartado: importa dónde obliga a moverse al rival y qué podéis hacer después, no solo el número de bajas.',
  ],
  headerTips: [
    'Antes de volar, mira la cobertura de llegada y quién podrá ayudarte allí.',
    'Con Matrix, identifica el disparo que amenaza al compañero; no basta con mirar hacia el atacante.',
    'Tras expulsar a un DPS de una altura, comprueba si necesitas quedarte o volver al grupo.',
  ],
  quickAnswers: [
    { title: 'Si pierdes el mech al llegar', body: 'Pausa el final de Boosters: ¿tenías cobertura, curación y Matrix disponible? Quizá el objetivo parecía aislado porque solo mirabas hacia él. Si otro enemigo tenía tiro desde un lateral, acertar los misiles no arreglaba esa llegada.' },
    { title: 'Si tus Supports mueren mientras persigues', body: 'Mira cuándo empezó la entrada rival y dónde estabas entonces. No todas esas muertes son culpa tuya, pero un vuelo extra detrás de un DPS puede haberte alejado del sitio donde podías cubrir los disparos. Revisa si bastaba con quitarlo de la altura y volver.' },
    { title: 'Si absorbes mucho daño pero el equipo no avanza', body: 'Pregunta qué permitió hacer Matrix: cruzar una línea, sobrevivir a un burst o mantener un ángulo. Si la consumiste desde lejos y nadie estaba listo para moverse, podéis seguir ante el mismo problema con menos protección.' },
  ],
  facts: [
    { title: 'Mech', body: 'Cañones, misiles, movilidad y Matrix permiten disputar posiciones cercanas. Perderlo cambia por completo lo que puedes ofrecer al grupo.' },
    { title: 'Matrix', body: 'Actúa sobre una zona delante de ti y tiene un recurso limitado. Protege según la trayectoria de los disparos, no por la proximidad a un aliado.' },
    { title: 'Boosters', body: 'Te acercan a una altura o a un compañero, pero después necesitas una posición jugable mientras vuelve el cooldown.' },
    { title: 'Piloto', body: 'Sin mech tienes la pistola, no Matrix ni Boosters. Conservar la vida y recuperar el mech exige otro ritmo.' },
  ],
  rankedPlan: [
    'Localiza al enemigo que tiene tiro libre sobre tu equipo. Puede ser un DPS en altura o alguien que acaba de entrar en tus Supports. Elige una respuesta que tus compañeros puedan aprovechar, no el objetivo más lejano que ves tocado.',
    'Acércate por cobertura antes de gastar Boosters si el mapa lo permite. Así el vuelo sirve para salvar el último tramo o alcanzar la plataforma, no para cruzar sola toda la línea de fuego.',
    'Al llegar, usa Matrix para la amenaza que realmente viene y decide cuándo puedes disparar. Si el rival se cubre o recibe ayuda, no tienes que seguir detrás: mantener la altura puede darle a tus DPS el ángulo que necesitaban.',
    'Vuelve cuando el grupo necesite tu ayuda, pero no abandones una posición ganada por cada disparo que recibe un Support. Mira si puede taparse, si otro compañero lo atiende y qué perderíais al dejar libre la altura.',
    'Antes de Self-Destruct, decide qué quieres conseguir y dónde quedará la piloto. Si buscas volver al mech, necesitas sobrevivir al intervalo; si buscas despejar el objetivo, alguien aún tendrá que disputarlo.',
  ],
  sections: [
    { title: 'Matrix: mira el disparo, no solo al enemigo', body: 'Para ayudar a un compañero, orienta la zona de Matrix hacia el recorrido del daño que lo amenaza. Estar a su lado no garantiza que lo estés cubriendo: un segundo rival puede disparar desde otro ángulo. Si ese compañero retrocede detrás de una pared, puedes dejar de gastar el recurso y acompañar su salida en lugar de seguir mirando al primer atacante.' },
    { title: 'El peel termina cuando el compañero puede salir', body: 'Si Tracer entra sobre Ana, puedes cubrir parte de sus disparos y presionarla de cerca. Eso no obliga a perseguirla hasta el lugar donde vuelve con Recall. Mira si Ana ha recuperado una cobertura o si aún necesita ayuda. Perseguir al atacante mientras otro enemigo mantiene tiro sobre ella puede dar una baja y perder igualmente a tu Support.' },
    { title: 'Una altura despejada no siempre hay que abandonarla', body: 'Expulsar a Ashe de una plataforma puede ser suficiente para que tus DPS crucen o tomen otro ángulo. Si bajas inmediatamente a perseguirla, quizá le permitas volver al mismo sitio. Quédate si desde allí puedes amenazar su regreso y ayudar al grupo; vuelve si la pelea se ha movido fuera de tu alcance o tu backline necesita una respuesta que nadie más puede dar.' },
    { title: 'Gibraltar: primera altura antes de empujar la carga', body: 'En la primera zona, disparar al Tank desde la carga no quita la presión de los enemigos instalados arriba. Si tus Supports están cruzando por abajo, prepara una llegada a la plataforma desde la que puedas obligar al DPS a cubrirse. No lo persigas por cada puerta: conservar ese espacio puede permitir que el grupo avance. Si te separas hasta perder curación y Matrix, puedes acabar eyectada mientras la carga sigue sin pasar.' },
    { title: 'Dorado: volver desde los tejados de la segunda zona', body: 'Después de la plaza del primer punto, las alturas de la segunda zona pueden darte un buen ángulo, pero también alejarte de tus Supports. Antes de subir, mira por dónde vienen ellos y a qué cobertura puedes volver. Si un flanker los obliga a retroceder, puede convenirte bajar a cortar los disparos en lugar de intentar matar al DPS que tienes arriba. Cuando recuperen posición, podrás volver a disputar el tejado con ayuda.' },
    { title: 'Perder el mech no significa que debas regalar la piloto', body: 'Primero mira si la pelea aún se puede disputar. Con compañeros vivos y una pared cercana, puedes buscar disparos para recuperar Call Mech sin ofrecerte en mitad de la línea. Si el grupo ya ha caído, sobrevivir durante demasiado tiempo lejos de él puede retrasar el siguiente ataque. Revisa la posibilidad de reagruparte; no conviertas la búsqueda del remech en otra pelea sola.' },
  ],
  abilities: [
    { title: 'Fusion Cannons', body: 'Los cañones funcionan mejor cerca. Disparar desde muy lejos puede parecer actividad sin quitar al rival de su posición. Usa cobertura y movilidad para alcanzar una distancia útil, pero deja de disparar si necesitas moverte o levantar Matrix para un burst. El daño que haces al Tank no compensa perder el mech antes de atender el ángulo peligroso.' },
    { title: 'Boosters', body: 'Vuelas hacia donde miras y puedes cancelar para parar antes. Practica llegar a una esquina o plataforma sin pasarte; tocar al enemigo no obliga a continuar hasta su backline. Al terminar, elige entre presionar, cubrir con Matrix o taparte. No cuentes con un reset por conseguir una baja: los poderes de Stadium que alteran Boosters no pertenecen al kit normal.' },
    { title: 'Defense Matrix', body: 'Niega disparos en un área frontal mientras gastas su recurso. Puedes cubrir un Sleep o una granada de Ana si interceptas su trayectoria a tiempo, además del daño que sigue a una entrada. No bloquea todo: los beams de Zarya y Symmetra y los golpes cuerpo a cuerpo requieren otra respuesta. Si varios enemigos atacan desde lados distintos, prioriza una línea y busca cobertura para la otra.' },
    { title: 'Micro Missiles', body: 'Lanzas una ráfaga de misiles explosivos. Acompañan la presión sobre un enemigo cercano o una posición que necesitas disputar. Antes de soltarlos, mira la cobertura a la que puede retirarse y si una burbuja de Zarya hará que el daño refuerce al rival. No prometen una baja por combinarse con Boosters: acertar, recibir ayuda y poder continuar son cosas distintas.' },
    { title: 'Self-Destruct', body: 'Abandonas el mech y lo haces explotar tras una espera. Puede forzar al rival a buscar cobertura y abrir una oportunidad para el grupo, aunque no mate. Mira también quién podrá aprovechar ese movimiento y cómo sobrevivirá la piloto. En overtime, la bomba no captura ni mantiene el objetivo por sí sola: necesitas conservar a alguien capaz de disputarlo.' },
    { title: 'Light Gun', body: 'Es la pistola que usas fuera del mech. Busca disparos desde una pared y acompaña lo que puedan sostener tus compañeros. No tienes la protección ni la movilidad de antes; asomar a por un remate puede costarte una carga de Call Mech casi recuperada. Si no puedes disparar sin exponerte a varios rivales, cambia de cobertura antes de insistir.' },
    { title: 'Call Mech', body: 'Solicitas un nuevo mech cuando está disponible. La llegada puede dañar a enemigos cercanos, pero intentar caer encima de ellos no es la única forma de usarla. Busca un lugar donde puedas completar la vuelta y ayudar después. Recuperar el mech detrás de una pared puede valer más que retrasarlo para intentar una baja mientras tus compañeros siguen sin Tank.' },
    { title: 'Eject!', body: 'Sales del mech cuando lo destruyen. Durante la pelea, ve identificando la cobertura que necesitarías como piloto si ocurre. Eyectar no borra el daño de los enemigos ni hace segura la posición donde estabas. Avisa al grupo de que ya no puedes cubrir con Matrix, especialmente si estaba preparando un cruce contando contigo.' },
  ],
  perksIntro: 'Eliges una Minor y una Major. Son mejoras del kit normal; los poderes de Stadium que permiten disparar los cañones con Matrix o añaden resets a Boosters son distintos.',
  perks: [
    { title: 'Minor · Bunny Power', body: 'Te da exceso de salud temporal al eyectar y amplía el radio de daño de Call Mech. Ayuda a la transición de piloto, no evita perder el mech ni asegura una baja al volver. Usa la protección para alcanzar una cobertura, en lugar de asumir que puedes quedarte expuesta hasta recuperar la ultimate.' },
    { title: 'Minor · Extended Boosters', body: 'Boosters dura más y hace más daño al golpear a un enemigo. Es alternativa a Bunny Power. Esa duración extra exige controlar dónde terminas: puedes cancelar cuando ya has llegado a la posición que buscabas. No te da por sí sola recuperación de Matrix ni un nuevo Boosters después de una eliminación.' },
    { title: 'Major · Shield System', body: 'Convierte parte de tu salud en escudo y Matrix recupera ese escudo según el daño absorbido. No rellena toda la vida ni cura a tus compañeros. Puede ayudarte cuando realmente tienes proyectiles que negar, pero no justifica exponerte para absorber más mientras un beam sigue dañándote por otra línea.' },
    { title: 'Major · Precision Fusion', body: 'Puedes activar una reducción temporal de la dispersión de los cañones. Es alternativa a Shield System y te ayuda a concentrar el disparo, no convierte cualquier distancia en un duelo favorable. Mira si tendrás tiro durante ese intervalo; activarlo antes de que el rival se esconda tras una pared puede desperdiciar la oportunidad.' },
  ],
  mistakes: [
    'Gastar Matrix durante un vuelo sin mirar qué viene. Puedes consumirla antes del Sleep o el burst que necesitabas cubrir al llegar. En el replay, separa el daño recibido durante el trayecto del que llega al terminar.',
    'Bajar de una altura solo porque el enemigo huye tocado. Revisa si esa plataforma daba tiro a tus DPS y si perseguirlo permitió al rival recuperarla. No necesitas una baja para que la subida haya servido.',
    'Hacer peel con una persecución demasiado larga. Si el compañero ya está a salvo, seguir detrás de Tracer puede alejarte del siguiente problema. Si aún recibe daño, mira qué línea dejaste sin cubrir al moverte.',
    'Disparar todos los misiles a una burbuja sin comprobar el contexto. A veces romperla con el equipo permite rematar; hacerlo sola desde lejos puede darle recursos a Zarya sin abrir ninguna oportunidad.',
    'Mantener Matrix frente a un beam esperando que haga de barrera. Cambia de ruta, corta la distancia o usa una pared. La animación activa no significa que el daño que recibes sea absorbible.',
    'Tirar Self-Destruct y esperar que el grupo gane mientras buscas Call Mech. Mira si quedaste protegida y si tus compañeros podían sostener el objetivo durante tu ausencia. La vuelta al mech no arregla una pelea ya perdida.',
  ],
  counters: [
    { title: 'Zarya', body: 'Su beam no entra en la protección de Matrix y las burbujas cambian a quién conviene presionar. Busca una altura o un lateral que puedas disputar sin pasar todo el tiempo a su alcance. Si tus DPS quieren romper una burbuja para rematar, acompaña esa decisión; no confundas evitar disparos por inercia con no disparar nunca a una barrera.' },
    { title: 'Symmetra', body: 'El beam y las torretas castigan que te quedes dentro de su zona. Antes de volar a una habitación, mira la entrada y si puedes limpiar los dispositivos desde una posición menos expuesta. Contestar una altura puede ser mejor que seguir al Tank dentro de un espacio preparado para frenarte.' },
    { title: 'Mei', body: 'El muro puede cortar la visión de curación o la ruta por la que pensabas volver. Si está esperando una entrada estrecha, no gastes Boosters hacia el interior sin una cobertura alternativa. Si te separa del grupo, prioriza recuperar contacto en vez de seguir pegando mientras el mech pierde vida.' },
    { title: 'Winston', body: 'Su entrada sobre los Supports puede pedir que vuelvas, pero no cualquier salto exige abandonar lo que hacías. Mira si tus compañeros pueden retirarse y desde dónde llega el daño que lo acompaña. Matrix puede negar disparos de sus aliados, no el daño principal de Tesla; presionar cerca o cortar el follow-up son respuestas diferentes.' },
    { title: 'Brigitte', body: 'Puede frenar tu entrada sobre otro Support: empujones, cobertura y curación dificultan que te quedes junto al objetivo. No gastes todo por verlo tocado si Brigitte ya está cubriéndolo. Busca otra línea con tus DPS o espera a que deba atender un acceso distinto.' },
    { title: 'Zenyatta', body: 'Discord hace más caro seguir expuesta mientras varios enemigos tienen tiro sobre el mech. Busca cobertura antes de tener que volar de emergencia. Si quieres acercarte a él, comprueba los compañeros que lo protegen: que no tenga una salida rápida no convierte en segura cualquier entrada.' },
  ],
  counterplay: [
    'Si pierdes el mech en la misma puerta, cambia la llegada antes de cambiar de héroe. Puede bastar una altura cercana, un cruce con ayuda o esperar a que otro ángulo obligue al rival a cubrirse. Volar más deprisa por la misma línea no arregla la falta de cobertura.',
    'Si la amenaza es un beam, Matrix aún puede ayudar contra sus compañeros, pero no debes quedarte delante del beam para intentar absorberlo. Decide qué espacio puede disputar el grupo desde otra posición y quién necesita que cubras el cambio.',
    'Si sigues sin poder mantener una posición útil ni proteger las entradas tras ajustar la ruta, valora un Tank que conozcas y resuelva ese problema. Ver Zarya en el marcador no obliga a cambiar, pero tampoco justifica repetir un duelo que no podéis sostener.',
  ],
  compositions: [
    { title: 'Genji o Tracer con una entrada compartida', body: 'Puedes ayudar a que lleguen al objetivo cubriendo parte de los disparos y presionando cerca. Acordad quién entra primero y por dónde se vuelve. Si Genji ya ha gastado Dash o Tracer ha usado Recall, no cuentan con la misma salida aunque el objetivo siga tocado.' },
    { title: 'Ana y Brigitte para disputar sin perder la backline', body: 'Ana necesita conservar visión de tu llegada; Brigitte puede atender una primera amenaza cerca, pero no protege a ambas para siempre. Si un flanco las obliga a retroceder, mira si debes volver o recortar tu distancia. Dar por hecho que tienen peel suficiente puede dejarte sin ayuda en una plataforma lejana.' },
    { title: 'Ashe o Soldier aprovechando una altura', body: 'No tienes que hacer dive hasta el fondo para ayudarles. Sacar al enemigo que les niega tiro, cubrir un cruce o frenar a quien sube por otro acceso puede permitirles mantener el ángulo. Comprueba quién ocupa el espacio al despejarlo: si todos siguen abajo, quizá el grupo aún no estuviera preparado para ese movimiento.' },
  ],
  vodReview: [
    'Pausa justo antes de Boosters y marca llegada, cobertura y visión de tus Supports. Después comprueba dónde terminaste y qué cambió durante el vuelo. Evalúa la ruta aunque hayas conseguido una baja.',
    'Elige una Matrix con la que salvaste a alguien y otra tras la que murió. Sigue la trayectoria de los disparos y los laterales que no cubrías. No uses solo el contador de daño absorbido para juzgarlas.',
    'Revisa la primera pérdida de mech de una pelea. Retrocede hasta el momento en que podías taparte, parar la persecución o conservar Matrix. La eyección es el resultado; la decisión suele estar antes.',
    'Mira una subida que expulsó a un DPS. ¿Quién aprovechó la altura después? ¿Te quedaste demasiado o la dejaste libre antes de que el grupo pudiera cruzar? Busca una razón concreta para mantenerla o volver.',
    'Con Self-Destruct, sigue también a la piloto y al objetivo. Señala a quién obligó a moverse, qué hizo el grupo con ese espacio y si pudiste regresar al mech. Tres bajas no demuestran que la pelea se ganara si nadie pudo disputarla después.',
  ],
  checklist: [
    '¿Qué amenaza necesita mi ayuda ahora: altura, cruce o backline?',
    '¿Dónde puedo parar Boosters y qué cobertura tendré allí?',
    '¿Qué disparo debo negar y desde qué otro ángulo me pueden atacar?',
    '¿Mi equipo puede aprovechar que quite al rival de esta posición?',
    '¿Necesito seguir persiguiendo o el compañero ya puede salir?',
    'Si pierdo el mech o tiro la bomba, ¿dónde quedará la piloto?',
  ],
  faqs: [
    { question: '¿Defense Matrix bloquea los beams?', answer: 'No. Matrix no absorbe los beams de Zarya y Symmetra. Usa cobertura y movilidad para cortar esa exposición. Aún puede ayudarte contra disparos de otros enemigos, pero no convierte el duelo cercano con el beam en seguro.' },
    { question: '¿Cuándo vuelvo a proteger a mis Supports con D.Va?', answer: 'Cuando tienen una amenaza que puedes atender y no pueden salir con la ayuda disponible. Mira su cobertura, recursos y el daño que acompaña al atacante. Si ya se han tapado o alguien está cubriéndolos, quizá puedas mantener la altura que acabas de ganar en vez de volver por costumbre.' },
    { question: '¿Debo perseguir al DPS que saco de una altura?', answer: 'No siempre. Si al expulsarlo permites cruzar al grupo, puedes quedarte para impedir que vuelva. Persíguelo cuando la llegada siguiente siga siendo jugable y no abandones otra necesidad más importante. Que esté tocado no explica por sí solo por qué merece otro vuelo.' },
    { question: '¿Self-Destruct tiene que conseguir bajas?', answer: 'No. Puede obligar al rival a cubrirse y permitir otro movimiento, pero el equipo debe aprovecharlo. Comprueba también la posición de la piloto y quién disputa el objetivo. La bomba no mantiene overtime por sí sola ni gana una pelea solo porque luego recuperes el mech.' },
    { question: '¿Qué hago cuando pierdo el mech de D.Va?', answer: 'Busca cobertura y comprueba si aún hay una pelea que tus compañeros puedan sostener. Con la pistola puedes recuperar Call Mech desde una línea protegida. Si el grupo ya ha caído, intenta reagruparte; vivir mucho tiempo sola detrás del rival puede retrasar el siguiente ataque.' },
    { question: '¿Qué perks tiene D.Va y cuándo conviene cada uno?', answer: 'Bunny Power ayuda al eyectar y amplía el radio de Call Mech; Extended Boosters mejora el contacto y prolonga el vuelo. Son alternativas Minor. Entre las Major, Shield System permite recuperar la parte convertida en escudo con Matrix y Precision Fusion concentra temporalmente los cañones. Elige según qué situaciones puedes aprovechar, sin confundirlas con los poderes de Stadium.' },
  ],
  conclusion: 'En el siguiente replay, sigue una subida y una vuelta a la backline. Mira la posición antes de Boosters, el final del vuelo y quién aprovechó tu movimiento. Así puedes distinguir una buena presión de una persecución que te alejó de la pelea, incluso si ambas terminaron con una baja.',
  links: [
    { href: '/guides/como-jugar-dva-ranked-overwatch', label: 'Practicar entradas y salidas con D.Va en ranked' },
    { href: '/counters/dva', label: 'Matchups que cambian tus decisiones con D.Va' },
    { href: '/team-comps/dva', label: 'Coordinar el equipo alrededor de D.Va' },
    { href: '/maps/watchpoint-gibraltar', label: 'Alturas y cruces de Gibraltar' },
    { href: '/maps/dorado', label: 'Rotaciones y tejados de Dorado' },
    { href: '/heroes/ana', label: 'La visión que necesita Ana para ayudarte' },
    { href: '/heroes/genji', label: 'Preparar una entrada con Genji' },
    { href: '/heroes/winston', label: 'Otro enfoque para las entradas de Tank con Winston' },
    { href: '/heroes/reinhardt', label: 'Acercarte por cobertura con Reinhardt' },
    { href: '/roles/tank', label: 'Decidir qué posición necesita tu equipo como Tank' },
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Revisar Matrix y Boosters en contexto' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Seguir una pelea completa en el replay' },
    { href: '/experts', label: 'Pedir una revisión de tus entradas y decisiones de peel' },
  ],
}
