import type { HeroPillar } from './hero-pillars'

export const reviewedGenjiHero: HeroPillar = {
  slug: 'genji', name: 'Genji', role: 'DPS', roleSlug: 'dps',
  publishedAt: '2026-06-26', schemaDate: '2026-10-09', updatedAt: '9 de octubre de 2026',
  seoTitle: 'Genji en Overwatch: Dash, Deflect y Dragonblade para ranked',
  seoDescription: 'Cuándo entrar con Genji, cómo aprovechar los resets de Dash y cómo preparar Dragonblade. Combos, perks, matchups y ejemplos para revisar tus partidas.',
  h1: 'Genji en Overwatch: cuándo entrar y cómo usar Dragonblade',
  kicker: 'Llegar al objetivo cuando tu equipo puede seguirte',
  intro: [
    'Con Genji, una barra de vida baja no basta para justificar un Dash. Antes de entrar, mira quién puede ayudar a ese enemigo, dónde acabarás y qué están haciendo tus compañeros. Puedes acertar el combo y aun así morir si llegas solo o terminas demasiado lejos de la curación.',
    'En Season 5, Dash gana daño y Blade golpea más rápido, aunque cada corte hace menos daño. Eso cambia el ritmo de los remates, no la necesidad de llegar con ayuda. Aquí encontrarás cómo preparar un off-angle, cuándo buscar un reset y cómo acercarte antes de Blade para no gastar la ultimate persiguiendo.',
  ],
  headerTips: [
    'Antes del Dash, elige dónde quieres terminar. No des por hecho que llegará un reset.',
    'Con Deflect, mira hacia la amenaza y busca cobertura mientras dura. No protege de cualquier daño.',
    'Para Blade, acuerda cuándo entra el equipo y quién puede ayudarte. Nano es una opción, no un requisito.',
  ],
  quickAnswers: [
    { title: 'Si mueres después del primer Dash', body: 'Pausa al aterrizar y mira quién tenía tiro sobre ti. Si atravesaste al objetivo y acabaste delante de sus compañeros, el problema puede ser la dirección del Dash, aunque el enemigo estuviera a poca vida. Busca una entrada que termine junto a una pared o cerca de tu equipo.' },
    { title: 'Si solo disparas al Tank', body: 'Comprueba si había otro ángulo accesible sin Dash. Trepar a una altura puede permitirte presionar a quien cura al Tank. No necesitas lanzarte sobre él de inmediato: obligarlo a cubrirse mientras vuestro frente avanza ya puede cambiar la pelea.' },
    { title: 'Si Blade acaba sin un solo golpe', body: 'Revisa cómo llegaste a rango antes de desenvainar. Si empezaste lejos y perseguiste a un objetivo con movilidad disponible, gastaste la ultimate durante el trayecto. Acércate desde cobertura y mira qué recurso puede separaros antes de activarla.' },
  ],
  facts: [
    { title: 'Disparos', body: 'El primario lanza tres shurikens en una ráfaga precisa; el secundario los abre en abanico. La distancia y el movimiento del rival condicionan cuántos aciertas.' },
    { title: 'Movilidad', body: 'Trepar y usar el doble salto permite cambiar de altura sin gastar Dash. Saltar repetidamente en la misma línea también puede hacerte previsible.' },
    { title: 'Resets', body: 'Las eliminaciones reinician Swift Strike. Tener de nuevo la habilidad no te obliga a gastarla para seguir atacando.' },
    { title: 'Defensa', body: 'Deflect devuelve proyectiles y bloquea ataques cuerpo a cuerpo. No es una protección completa frente a daño de cualquier dirección o tipo.' },
  ],
  rankedPlan: [
    'Busca una cobertura desde la que puedas presionar y una ruta para volver. Usa trepar para acercarte a una altura antes de gastar Dash. Si el camino te deja fuera de la ayuda del equipo, necesitas una retirada que no dependa de conseguir una eliminación.',
    'Mira cuándo vuestro Tank va a llamar la atención. Puedes empezar a disparar desde un lateral antes de su entrada, pero comprometerte cuando él todavía está esperando permite que toda la defensa se gire hacia ti.',
    'Elige un objetivo por su posición y sus recursos, no solo por el héroe. Una Ana separada y sin Sleep ofrece una situación distinta de la misma Ana junto a Brigitte, con cobertura y el resto del equipo pendiente de tu entrada.',
    'Decide qué hará el primer Dash: cerrar distancia, rematar o salir. Si lo usas para acercarte, mira la dirección y qué superficie encontrarás al terminar. Apuntar hacia el suelo o una pared cercana puede evitar que acabes demasiado lejos; no cuentes con detenerlo libremente a mitad del recorrido.',
    'Después de una baja, mira de nuevo la pelea. El reset puede servir para volver junto a tus Supports o tomar una altura. Si el rival ya se ha reagrupado, perseguir al siguiente enemigo puede perder la ventaja que acabáis de conseguir.',
  ],
  sections: [
    { title: 'Presionar desde un lateral sin quedarte fuera', body: 'Un off-angle funciona cuando el rival tiene que atenderlo mientras tu equipo amenaza por otro lado. Si tus compañeros aún no han llegado, puedes disparar desde cobertura, pero no necesitas pelear hasta que alguien muera. Cuando dos enemigos se giren, vuelve a taparte y comprueba si vuestro frente ha avanzado. Mantener el mismo duelo mientras el resto del equipo pelea en otra habitación no ayuda por sí solo.' },
    { title: 'El combo empieza por la distancia', body: 'A corta distancia puedes combinar el abanico de shurikens, melee y Dash para aprovechar un objetivo tocado. No lo conviertas en una secuencia fija que deba matar a cualquiera: puedes fallar parte del abanico, encontrarte armadura o recibir una respuesta defensiva. Practica primero el seguimiento de la mira y dónde acabas tras el Dash. En partida, si ya estás a rango, quizá sea mejor conservarlo hasta ver si necesitas rematar o retirarte.' },
    { title: 'Deflect: cubrirte mientras buscas una salida', body: 'Si Cassidy te contesta desde delante, Deflect puede dar margen para alcanzar una esquina. Mira hacia él durante ese movimiento y comprueba si hay otro enemigo disparándote por el lateral. No te quedes en medio esperando que devuelva una bala decisiva: el rival puede dejar de disparar. Si has entrado en una zona con daño de área o ataques que no puedes reflejar, necesitas salir de esa zona, no prolongar el duelo confiando en el botón.' },
    { title: 'Preparar Blade antes de pedir Nano', body: 'Elige un primer objetivo al que puedas llegar y avisa cuándo vas a entrar. Comprueba si Ana tiene visión de ti y si el Tank puede presionar al mismo tiempo. Si vas a doblar una esquina y salir de su línea, acuerda cuándo recibirás Nano antes de hacerlo. Mira también qué queda disponible para detenerte: Sleep, Suzu, una burbuja o un desplazamiento pueden cambiar el primer duelo aunque vayas con el aumento de daño.' },
    { title: 'Blade sin Nano: busca una pelea alcanzable', body: 'Puedes aprovechar a un enemigo que acaba de gastar movilidad, un grupo ocupado con vuestro Tank o una pelea donde ya hay objetivos tocados. No hace falta empezar contra toda la backline junta. Si activas Blade lejos de alguien que puede escapar, dedicarás buena parte de la ultimate a acercarte. Si el primer objetivo sale de tu alcance, mira si tienes otro cerca o si conviene cubrirte. Perseguirlo hasta sus compañeros puede dejarte sin ningún duelo que puedas ganar.' },
    { title: 'Gibraltar: disputar la altura sin perseguir por el hangar', body: 'En el hangar de Watchpoint: Gibraltar, trepar permite preparar un ángulo antes de que Winston salte. Mira desde qué borde puede ayudarte Ana y dónde aterrizará vuestro Tank. Si el Support rival abandona la altura, no tienes que seguirlo hasta el otro extremo: quedaros con esa posición puede abrir el avance de la carga. Persigue solo si puedes mantener el contacto sin separarte de toda la ayuda.' },
    { title: 'King’s Row: entrar por hotel con el frente', body: 'En el punto A, hotel puede darte otro acceso mientras vuestro Tank presiona la entrada. Comprueba qué ocurre junto a la estatua antes de salir: si la defensa os está esperando y el resto aún no cruza, el lateral no se ha convertido en una entrada segura. Puedes volver a cubrirte y repetir la presión. Gastar Dash para aparecer detrás de toda la defensa te obliga a resolver solo una pelea que el grupo todavía no ha empezado.' },
  ],
  abilities: [
    { title: 'Shuriken', body: 'El primario concentra tres proyectiles en una ráfaga y permite presionar a distancia. El secundario lanza un abanico que puedes aprovechar cuando estás cerca. No elijas solo por costumbre: mira cuánto ocupa el objetivo en pantalla y por dónde se mueve. Si los enemigos ya te están esperando, disparar desde una exposición corta puede aportar más que intentar cerrar distancia a cualquier precio.' },
    { title: 'Swift Strike', body: 'Dash atraviesa hacia delante y hace daño a los enemigos que alcanzas; las eliminaciones reinician su cooldown. Desde el 6 de octubre, su daño base es 60, antes 50. Planifica el destino antes de pulsarlo: más daño no evita la armadura, una defensa rival o el focus al aterrizar. Un reset da otra decisión, no una segunda entrada obligatoria. Si no llega, busca la cobertura que habías preparado.' },
    { title: 'Deflect', body: 'Devuelve los proyectiles hacia donde apuntas y bloquea ataques cuerpo a cuerpo, sin devolver el daño de esos golpes. Orientarte importa: no cubre automáticamente la espalda. Puedes cancelarlo antes de que termine si necesitas volver a disparar, pero cancelar delante de alguien que esperaba ese momento vuelve a exponerte. No lo trates como una invulnerabilidad ni como respuesta universal frente a beams o daño de área.' },
    { title: 'Dragonblade', body: 'Desenvainas una espada para atacar cuerpo a cuerpo. Season 5 baja el daño base del corte de 110 a 100 y aumenta la velocidad de los golpes un 15%. Necesitas llegar a rango y mantener el contacto para aprovechar ese ritmo. Antes de activarla, mira el primer objetivo, qué defensa conserva y quién puede seguir. Si sale de tu alcance, la mayor velocidad no recupera el tiempo que pasas corriendo detrás.' },
    { title: 'Cyber-Agility', body: 'Trepar y usar el doble salto permite acceder a alturas, cambiar de ruta y evitar depender siempre de Dash para acercarte. No es una razón para estar saltando sin parar: una trayectoria repetida puede facilitar que te sigan la mira. Usa la pared para llegar a una posición útil y comprueba qué enemigos ven el borde antes de asomar.' },
  ],
  perksIntro: 'Eliges una alternativa Minor y otra Major a medida que avanzas en la partida. Estas son las opciones del kit normal; los poderes y objetos de Stadium tienen efectos distintos y no forman parte de estas elecciones.',
  perks: [
    { title: 'Minor · Swift Cuts', body: 'El melee reduce el cooldown de Swift Strike. Puede ayudarte después de haber gastado Dash, pero no necesitas quedarte cuerpo a cuerpo contra un enemigo que te está ganando para intentar recuperarlo. Si puedes salir hacia cobertura, no conviertas esa mejora en una obligación de seguir pegando.' },
    { title: 'Minor · Dragon’s Thirst', body: 'Los golpes de Dragonblade recuperan vida mediante robo de vida. Es alternativa a Swift Cuts. La ayuda depende de acertar golpes; no compensa el trayecto hasta un objetivo que se ha alejado ni hace segura una Blade contra todo el focus rival.' },
    { title: 'Major · Blade Twisting', body: 'Swift Strike añade daño en el tiempo contra enemigos por debajo de media vida. Puede reforzar un remate, pero ese daño no es una eliminación garantizada ni exige haber conseguido una baja anterior para aplicarse. Mira si el objetivo aún tiene una defensa o puede recibir ayuda.' },
    { title: 'Major · Meditation', body: 'Regeneras vida mientras Deflect está activo. Es alternativa a Blade Twisting y no depende de haber reflejado daño. Puedes ganar margen para cubrirte, pero sigues teniendo que orientar Deflect y evitar amenazas que no bloquea. No confundas esta regeneración con los poderes de Stadium que curan según el daño prevenido.' },
  ],
  balanceReview: [
    { title: '6 de octubre: más daño de Dash y otro ritmo para Blade', body: 'Swift Strike pasa de 50 a 60 de daño; Dragonblade, de 110 a 100 por corte, con un 15% más de velocidad de ataque. No juzgues todo el ajuste solo por uno de esos números. Para practicar un remate, comprueba la vida del objetivo, armadura y ayudas defensivas con el parche actual. En el replay, distingue fallar un golpe de perder contacto: el segundo caso requiere preparar mejor la llegada, no atacar más rápido desde lejos.' },
  ],
  mistakes: [
    'Atravesar al objetivo con Dash y acabar expuesto a sus compañeros. Mira dónde apareces en la cámara del rival y prueba otra dirección o un aterrizaje junto al suelo o una pared. No basta con que el Dash alcance al enemigo: también tienes que poder jugar desde donde termina.',
    'Entrar porque has visto Sleep gastado sin mirar el resto. Esa Ana puede seguir teniendo granada y ayuda de Brigitte. Cuenta las respuestas que afectan a ese duelo, no todos los cooldowns del equipo por igual.',
    'Mantener Deflect quieto esperando que el enemigo dispare. Si ha dejado de hacerlo, aprovecha para moverte hacia cobertura. El botón no obliga al rival a regalarte daño reflejado.',
    'Encadenar el reset después de ganar la pelea. Si el siguiente objetivo está rodeado y tus compañeros se han quedado atrás, volver con ellos mantiene la ventaja y evita una muerte tardía.',
    'Pedir Nano cuando Ana no tiene visión o está defendiéndose de un flanco. Acuerda la entrada antes de cruzar. Una ultimate disponible no significa que el compañero pueda usarla sobre ti en ese momento.',
    'Valorar Blade solo por las eliminaciones. Revisa si forzó una defensa que el equipo aprovechó o si gastaste la ultimate persiguiendo sin apoyo. Ninguna de esas conclusiones se ve únicamente en el contador de bajas.',
  ],
  counters: [
    { title: 'Brigitte', body: 'Su presencia junto al objetivo puede impedir un duelo aislado. Mira si conserva el empujón y qué espacio tienes para volver a acercarte. No gastes Dash solo para entrar en el alcance de los dos Supports cuando tu equipo aún no amenaza por otro lado.' },
    { title: 'Moira', body: 'Fade puede romper el contacto cuando empiezas el combo o Blade. Si lo conserva, no presupongas que se quedará delante para recibir los golpes. Puedes presionarla para que lo use y decidir después si es alcanzable, en lugar de perseguir cada desaparición.' },
    { title: 'Winston', body: 'Puede ocupar la zona donde estabas preparando un lateral y separarte de tus Supports. Busca una pared o ruta que te permita volver junto al grupo. Deflect no es una razón para permanecer a su lado esperando ganar el intercambio.' },
    { title: 'Zarya', body: 'Una burbuja sobre tu objetivo cambia el remate. Si aparece, no sigas el combo automáticamente: puedes cubrirte, cambiar de amenaza o esperar a que termine si la posición lo permite. Una barra baja antes de la burbuja no asegura el reset que habías planeado.' },
    { title: 'Ana y Kiriko', body: 'Sleep, granada y Suzu pueden cambiar tu primera entrada. No basta con saber que Suzu se usó hace un momento: mira si la otra Support aún puede responder. Si empiezas Blade de frente por el único acceso visible, les das una oportunidad más clara de prepararse.' },
    { title: 'Cassidy', body: 'Te castiga si aterrizas expuesto a su rango. Acércate por cobertura y comprueba si tiene el control que puede detener tu salida. Deflect puede responder a sus disparos, pero no protege de un segundo enemigo que ya te haya tomado el lateral.' },
  ],
  counterplay: [
    'Si los Supports rivales juegan juntos, no busques el mismo duelo por la misma puerta cada intento. Presiona desde otra posición mientras vuestro Tank entra y observa cuál se separa o gasta ayuda. Si ambos siguen cubiertos y disponibles, quizá el objetivo alcanzable sea otro.',
    'Cuando una respuesta defensiva aparece después del Dash, cambia el plan. Que hayas empezado un combo no obliga a completarlo. Busca cobertura, mantén presión con shurikens o vuelve junto al equipo si ya no puedes seguir el contacto.',
    'Valora el swap cuando el problema persista pese a cambiar de ruta y de timing. Si no puedes disputar las posiciones que el equipo necesita y otro DPS que conoces lo haría mejor, explica esa necesidad. Una Blade fallada o un héroe rival concreto no bastan por sí solos para decidir.',
  ],
  compositions: [
    { title: 'Winston y Tracer para entrar sobre la misma zona', body: 'Winston puede llamar la atención y Tracer presionar desde otro lado. Genji aprovecha el objetivo que quede alcanzable, sin tener que empezar con Dash desde muy lejos. Acordad también cuándo salir: si Winston vuelve a una cobertura, seguir tú hasta la siguiente habitación puede romper el seguimiento aunque aún tengas reset.' },
    { title: 'Ana para preparar Nano y mantener visión', body: 'Antes de Blade, comprueba si Ana puede verte sin abandonar su cobertura. Nano puede reforzar el intento, pero no sustituye el acceso al objetivo. En Gibraltar, una entrada desde la altura puede cortarle la visión al caer detrás de una pared; prepara el momento de recibir la ayuda antes de empezar esa ruta.' },
    { title: 'Reinhardt y un lateral corto', body: 'No necesitas convertir el grupo entero en dive para aportar con Genji. Mientras Reinhardt disputa una esquina, puedes contestar otro acceso cercano y volver cuando te presionen. En King’s Row, hotel puede servir a ese plan. Si te alejas varias calles, vuestro frente pierde una amenaza que ya no puede coordinar con su entrada.' },
  ],
  vodReview: [
    'Elige una muerte justo después de Dash. Retrocede hasta antes de pulsarlo y señala el destino, el objetivo y los enemigos que tenían tiro al llegar. Distingue una mala dirección de una entrada demasiado temprana; no lo reduzcas todo a haber fallado el remate.',
    'Busca una entrada que hiciste al ver un cooldown gastado. Mira qué otra defensa seguía disponible y qué estaban haciendo tus compañeros. La información era útil, pero comprueba si realmente bastaba para entrar en ese instante.',
    'Revisa un Deflect sin daño reflejado. ¿Te permitió cubrirte o lo mantuviste quieto mientras el rival esperaba? Si te mataron durante su uso, mira dirección, ángulos y tipo de amenaza antes de concluir que el botón falló.',
    'Pausa una Blade antes de activarla. Señala a la primera víctima, su escape, las ayudas defensivas y la posición de quien debía seguirte. Después comprueba cuánto tiempo pasaste acercándote y cuánto pudiste atacar. Practica el acceso que faltaba, no solo la velocidad de los golpes.',
    'Busca una baja con reset seguida de tu muerte. Mira si el siguiente Dash tenía apoyo o si podías volver a una altura y mantener la ventaja. Separa ese caso de una persecución útil que el equipo sí podía seguir.',
  ],
  checklist: [
    '¿Puedo preparar este ángulo sin gastar Dash?',
    '¿Mi equipo va a presionar cuando yo llegue?',
    '¿Quién puede ayudar al objetivo que estoy eligiendo?',
    '¿Dónde terminaré si no consigo el reset?',
    '¿Deflect me permite alcanzar cobertura o solo retrasa el mismo duelo?',
    'Con Blade, ¿estoy ya cerca de alguien alcanzable y he acordado la ayuda?',
  ],
  faqs: [
    { question: '¿Cuándo conviene entrar con Genji?', answer: 'Cuando puedas llegar a un objetivo y tu equipo amenace al mismo tiempo, con una posición de llegada que no dependa de conseguir una baja inmediata. Mira sus defensas y quién puede ayudarlo. Ver poca vida o un cooldown gastado es información útil, pero no convierte por sí sola cualquier Dash en una buena entrada.' },
    { question: '¿Qué combo debo practicar con Genji?', answer: 'Practica el abanico de shurikens a corta distancia, el melee y un Dash que termine donde quieres. Después varía el orden según la distancia y los recursos disponibles. No existe una secuencia que garantice la baja contra cualquier objetivo; acertar los proyectiles y elegir bien el destino importa más que repetirla a toda velocidad.' },
    { question: '¿Qué cambió en Dash y Dragonblade con Season 5?', answer: 'El 6 de octubre, Swift Strike subió de 50 a 60 de daño. Dragonblade bajó de 110 a 100 por corte y ganó un 15% de velocidad de ataque. Son valores base: armadura, aumentos de daño y defensas cambian el resultado del duelo. Practica los remates con el parche actual en lugar de dar por válido cualquier combo de un vídeo anterior.' },
    { question: '¿Deflect devuelve los ataques cuerpo a cuerpo?', answer: 'No. Bloquea ataques cuerpo a cuerpo, pero devuelve los proyectiles hacia donde apuntas. Tampoco es una invulnerabilidad: la dirección y el tipo de ataque importan. Si recibes presión por varios lados o daño que no puede reflejar, necesitas cobertura y una salida, no confiar en quedarte quieto durante toda la habilidad.' },
    { question: '¿Hay que usar Dragonblade siempre con Nano Boost?', answer: 'No. Nano puede mejorar una entrada coordinada, pero Blade también puede aprovechar enemigos tocados, movilidad gastada o una pelea en la que tu Tank ya esté presionando. Con o sin Nano necesitas llegar a rango. Acuerda la ayuda con Ana y comprueba su visión antes de cruzar fuera de su alcance visual.' },
    { question: '¿Qué hago después de conseguir un reset de Dash?', answer: 'Mira el siguiente objetivo y dónde está tu equipo antes de volver a usarlo. Puedes seguir una eliminación alcanzable, retirarte o tomar una altura. Si para continuar tienes que entrar solo entre varios enemigos, conservar la ventaja que ya has conseguido suele valer más que intentar encadenar otra baja.' },
    { question: '¿Debo cambiar de Genji si el rival lleva Brigitte o Moira?', answer: 'No automáticamente. Comprueba si puedes cambiar el ángulo, entrar junto a tu Tank o elegir otra amenaza. Si después de esos ajustes sigues sin disputar lo que necesita el equipo, valora un DPS que conozcas y que resuelva ese problema. Haz el cambio por lo que aporta a la partida, no por una sola muerte o una lista de counters.' },
  ],
  conclusion: 'Para la próxima partida, elige un cambio que puedas comprobar en el replay: terminar el Dash junto a cobertura, cortar un duelo cuando tu equipo aún no entra o acercarte antes de Blade. Revisar esa decisión con la posición de los diez jugadores aporta más que juzgar toda la partida por una ultimate o por el número de resets.',
  links: [
    { href: '/guides/como-jugar-genji-ranked-overwatch', label: 'Practicar las entradas de Genji en ranked' },
    { href: '/counters/genji', label: 'Matchups de Genji y respuestas defensivas' },
    { href: '/team-comps/genji', label: 'Coordinar el dive y las ayudas para Blade' },
    { href: '/maps/watchpoint-gibraltar', label: 'Alturas y recorridos de Watchpoint: Gibraltar' },
    { href: '/maps/kings-row', label: 'Hotel, estatua y esquinas de King’s Row' },
    { href: '/heroes/ana', label: 'Preparar Nano y mantener visión con Ana' },
    { href: '/heroes/kiriko', label: 'Entender las decisiones de Suzu y teleport' },
    { href: '/roles/dps', label: 'Elegir la presión que necesita tu equipo como DPS' },
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Revisar las respuestas disponibles antes de entrar' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Elegir una pelea y revisarla paso a paso' },
    { href: '/doctrine-support-sombra-roadhog-rework-overwatch', label: 'Las novedades y el balance de Season 5' },
    { href: '/experts', label: 'Pedir una revisión de tus decisiones de entrada' },
  ],
}
