import type { HeroPillar } from './hero-pillars'

export const reviewedWinstonHero: HeroPillar = {
  slug: 'winston', name: 'Winston', role: 'Tank', roleSlug: 'tank',
  publishedAt: '2026-06-26', schemaDate: '2026-10-04', updatedAt: '4 de octubre de 2026',
  seoTitle: 'Winston en Overwatch: salto, burbuja y Primal en ranked',
  seoDescription: 'Cómo preparar el dive con Winston, colocar la burbuja y salir sin regalar la pelea. Disparo secundario, perks y Primal con ejemplos de Numbani y Lijiang.',
  h1: 'Winston en Overwatch: prepara el dive antes de saltar',
  kicker: 'Llegar con ayuda y dejar una salida disponible',
  intro: [
    'Si aterrizas encima de Ana y ella sobrevive, no mires solo los disparos que fallaste. Mira dónde estaban tus DPS, quién pudo curarla y cuánto tardaste en encontrar una salida. Winston puede llegar muy lejos con Jump Pack; el resto del equipo no siempre puede acompañarlo a esa distancia.',
    'El dive empieza antes del salto: acercarte por una ruta menos expuesta, esperar a que un compañero tenga ángulo y elegir dónde quedará la burbuja. Aquí encontrarás cómo preparar esa entrada, cuándo abandonar una persecución y qué intentar con Primal. También explicamos el disparo secundario y los perks, que cambian tus opciones sin resolver por sí solos una mala llegada.',
  ],
  headerTips: [
    'Antes de saltar, comprueba quién tendrá tiro sobre el objetivo cuando aterrices.',
    'Coloca la burbuja pensando en el atacante y en el Support que está detrás, no solo bajo tus pies.',
    'Con Primal, elige hacia dónde quieres mover al rival antes de empezar a golpear.',
  ],
  quickAnswers: [
    { title: 'Si mueres antes de volver a saltar', body: 'Revisa desde dónde empezaste y qué cobertura tenías al aterrizar. Quizá necesitabas acercarte a pie o caer desde una altura para conservar Jump Pack. También mira si la burbuja recibió daño desde varios lados: esperar el cooldown dentro de una cúpula que ya está rota no es una salida.' },
    { title: 'Si el objetivo siempre recibe ayuda', body: 'Sigue al segundo Support en el replay. Si puede entrar en la burbuja o seguir curando desde el mismo lado, no has separado al objetivo de esa ayuda. Cambia la posición de llegada o coordina presión sobre quien lo sostiene; repetir el salto al mismo sitio no convierte a ese enemigo en aislado.' },
    { title: 'Si fuerzas Suzu pero no ganáis la pelea', body: 'Comprueba el coste de la entrada: tu salud, la burbuja, los recursos que gastó Ana en ayudarte y el espacio que cedió el grupo. Forzar Suzu puede preparar un ataque siguiente, pero no compensa automáticamente morir lejos mientras tus compañeros siguen cruzando.' },
  ],
  facts: [
    { title: 'Llegada', body: 'Un objetivo accesible no es necesariamente un buen objetivo. Importan la cobertura, sus compañeros y el seguimiento de tus DPS.' },
    { title: 'Burbuja', body: 'Separa líneas de disparo según dónde la pongas. Puede romperse o dejar de protegerte si el rival cruza su borde.' },
    { title: 'Secundario', body: 'El disparo cargado permite presionar sin gastar el salto. No sustituye una entrada cuando el grupo ya necesita disputar la posición.' },
    { title: 'Primal', body: 'Te da más salud y cambia el ataque a golpes y saltos. Empujar en la dirección equivocada puede salvar al enemigo al que intentabas rematar.' },
  ],
  rankedPlan: [
    'Mira la posición del equipo antes de elegir a quién saltar. Si Genji está volviendo de spawn o Ana acaba de perder visión al rodear una esquina, tu llegada aún no tiene la misma ayuda. Puedes preparar una altura o usar el secundario mientras recuperan posición.',
    'Elige una cobertura de aterrizaje y otra de retirada. Desde una altura cercana puedes bajar sin gastar Jump Pack y guardarlo para volver; desde main quizá necesites saltar, pero no hasta el rincón más lejano de la backline.',
    'Decide qué línea necesita cortar la burbuja. Si Ana enemiga cura desde detrás, intenta que el borde quede entre ella y el objetivo. Si los dos Supports ya están juntos dentro, tendrás que contar con esa ayuda en lugar de asumir que la cúpula la elimina.',
    'Después de forzar movilidad o una defensa, vuelve a mirar el objetivo. Si se ha reunido con su equipo y el tuyo no puede continuar, no sigas solo por haberlo dejado tocado. Una retirada a cobertura puede permitir una segunda entrada con la siguiente burbuja.',
    'Antes de Primal, elige entre sostener el objetivo, separar a alguien de su ayuda o retirarte de una situación peligrosa. Comprueba también dónde terminarás: sobrevivir a la ultimate en medio de cinco enemigos no deja preparada la pelea siguiente.',
  ],
  sections: [
    { title: 'Bajar desde una altura conserva el salto para salir', body: 'Si ya estás encima de la ruta rival, no necesitas gastar Jump Pack para cada entrada. Puedes caer cerca del objetivo, colocar la burbuja y reservar el salto para una cobertura conocida. Tiene un límite: si te empujan lejos o el grupo cambia de lado, quizá ya no puedas volver a la misma plataforma. Mira la posición al caer, no solo el hecho de tener el cooldown disponible.' },
    { title: 'El borde de la burbuja importa más que su centro', body: 'Contra disparos de un enemigo situado fuera, cruzar el borde puede hacer que la barrera quede entre él y tú. Si te persigue hacia dentro, cambia el lado desde el que juegas o busca una pared. No te quedes quieto porque la animación siga visible. Para separar a un objetivo de Ana, importa por dónde pasan sus disparos de curación; una burbuja con ambos Supports dentro no corta esa línea.' },
    { title: 'El DPS tiene que poder seguir la entrada', body: 'Si Tracer aún está recorriendo el flanco, puede llegar después de que ya hayas gastado burbuja y recibido todo el daño. Espera a que tenga una posición desde la que amenazar al mismo objetivo o elige otro que el grupo ya pueda presionar. No necesitas una cuenta atrás perfecta en voz: mirar las posiciones de tus compañeros evita muchas entradas a destiempo.' },
    { title: 'Numbani: disputar las alturas del primer punto', body: 'En ataque, saltar desde la calle hasta el fondo del punto puede dejar a tus Supports fuera de visión mientras te disparan desde las plataformas. Prepara primero una altura cercana y mira qué DPS rival mantiene tiro sobre el cruce. Si lo obligas a retirarse, puedes quedarte a facilitar el avance o caer después sobre otro objetivo con Jump Pack disponible. Perseguirlo por el interior mientras todos siguen abajo puede devolverle al rival el control de la entrada.' },
    { title: 'Lijiang Garden: entrar sin regalar el puente', body: 'Al acercarte por el puente, no gastes el salto hacia una puerta sin mirar quién puede seguirte y dónde está el empujón rival. Cerca del borde, una llegada que parecía buena puede terminar fuera del mapa. Usa la cobertura del edificio para preparar la presión y no persigas a un Support alrededor del exterior si el equipo aún intenta entrar. Con Primal puedes buscar desplazamientos, pero también necesitas conservar una posición desde la que disputar el punto.' },
    { title: 'Primal: empujar hacia una pared o lejos del objetivo', body: 'Para rematar, intenta mantener al enemigo en un lugar donde puedas volver a alcanzarlo. Si lo mandas hacia sus Supports, quizá acabes ayudándolo a escapar. Si necesitas despejar el punto, la dirección puede ser otra: apartarlo del área que disputa el grupo, sin alejarte tú tanto que nadie mantenga contacto. Revisa cada salto entre golpes; perseguir a quien ya salió del objetivo puede ser innecesario en overtime.' },
  ],
  abilities: [
    { title: 'Tesla Cannon: disparo principal', body: 'La electricidad alcanza a enemigos cercanos dentro del cono frontal. Mantén una distancia desde la que puedas seguir al objetivo sin perder la cobertura de la burbuja. Si varios rivales se agrupan delante, puedes presionarlos juntos, pero acercarte a Reaper solo para incluirlo en el daño puede costarte mucho más de lo que ganas. Cambia de lado o de objetivo cuando el duelo deja de ser sostenible.' },
    { title: 'Tesla Cannon: disparo secundario', body: 'Mantienes la carga y la sueltas como un disparo de electricidad concentrada. Sirve para presionar a alguien desde una cobertura o añadir daño antes de acercarte. No saltes al fondo solo porque hayas acertado uno: vuelve a mirar su salud, la ayuda que recibe y la distancia de tus compañeros. Cargar desde una línea abierta también te expone; una pared sigue siendo parte de la preparación.' },
    { title: 'Jump Pack', body: 'Saltas y haces daño al aterrizar cerca del enemigo. Decide antes de pulsarlo dónde quieres terminar y desde qué lugar volverás a recibir curación. Practica llegadas a plataformas y saltos cortos, no solo el vuelo más largo posible. En el kit normal no cuentas con un segundo impulso durante el mismo salto ni con un reset por cada baja; no planifiques la retirada con mejoras de un modo distinto.' },
    { title: 'Barrier Projector', body: 'Despliegas una cúpula que puede protegerte de disparos y cortar ciertas líneas de curación, como los disparos de Ana desde fuera. No anula toda la curación ni vuelve invulnerable al grupo: el rival puede cruzar, disparar desde dentro o romperla. Sitúala para una amenaza concreta y conserva una pared cercana. Si esperas a estar a punto de morir, quizá los disparos o el Sleep que querías detener ya hayan llegado.' },
    { title: 'Primal Rage', body: 'Obtienes más salud y atacas con golpes y saltos, no con Tesla Cannon. Úsala con tiempo para elegir qué rival quieres desplazar y hacia dónde, o qué posición necesitas sostener. No crea una burbuja automáticamente en el kit normal. Si tu objetivo solo es salir, no tienes que perseguir una baja antes de regresar a cobertura. La pelea puede seguir después de Primal: mira dónde te deja el último salto.' },
  ],
  perksIntro: 'Eliges una Minor y una Major. Estas son mejoras del kit normal. Los poderes de Stadium que añaden barreras, curación al aterrizar o resets de Jump Pack son opciones de otro modo.',
  perks: [
    { title: 'Minor · Electric Charge', body: 'Ganas velocidad de movimiento mientras dañas enemigos con el disparo principal de Tesla. Puede ayudar a seguir a quien se mueve cerca o a cambiar de lado en la burbuja. No es velocidad por cargar el secundario ni te garantiza una salida: si para mantenerla necesitas seguir dentro de un duelo malo, busca cobertura en vez de perseguir el efecto.' },
    { title: 'Minor · Heavy Landing', body: 'Mejora el daño y el área del aterrizaje de Jump Pack durante Primal según el tiempo en el aire. Es alternativa a Electric Charge; no mejora todos tus saltos fuera de la ultimate. Un vuelo más largo tampoco es siempre mejor: puede apartarte del enemigo que intentabas mantener contra una pared o sacarte del objetivo.' },
    { title: 'Major · Chain Lightning', body: 'Los impactos del secundario completamente cargado pueden rebotar a otros objetivos. Es una opción cuando puedes presionar a rivales agrupados desde una línea protegida. No se aplica al cono del disparo principal ni convierte un disparo fallado en presión sobre el grupo. Si el enemigo se separa o se tapa, no te quedes expuesto esperando un rebote.' },
    { title: 'Major · Revitalizing Barrier', body: 'La burbuja cura a los aliados que están dentro. Es alternativa a Chain Lightning y puede ayudar cuando tus compañeros juegan esa zona contigo. No compensa dejar a Ana sin visión ni convierte la cúpula en refugio permanente: si se rompe o el grupo tiene que salir, necesitaréis otra cobertura y curación. Valora dónde la usarás, no solo la posibilidad de recibir salud.' },
  ],
  mistakes: [
    'Saltar sobre el Support más lejano mientras tus DPS aún cruzan. En el replay, mira su cámara antes de tu llegada: si no podían disparar al mismo objetivo, no era una entrada compartida aunque todos estuvieran vivos.',
    'Poner la burbuja sobre dos Supports y dar por hecho que has cortado las curas. Sigue los disparos de Ana y la posición de ambos. Si siguen en el mismo lado del borde, esa separación no ha ocurrido.',
    'Esperar Jump Pack en el centro de una burbuja rota. Revisa la pared que tenías al aterrizar y cuándo podías acercarte a ella. La cúpula es un recurso temporal, no la cobertura de toda la pelea.',
    'Tratar cualquier cooldown forzado como una entrada buena. Si has gastado burbuja, recibido Nano para sobrevivir y muerto lejos, forzar Suzu quizá no deje al equipo preparado para continuar. Compara lo que habéis ganado con lo que habéis perdido.',
    'Perseguir al objetivo que salió con Fade o Swift Step hasta el resto de su equipo. Mira si podías dejarlo retirarse y mantener una posición que tus DPS aprovecharan. La siguiente puerta puede ser un duelo distinto del que empezaste.',
    'Encadenar golpes de Primal sin mirar hacia dónde desplazas. Si el enemigo termina con sus Supports o fuera del alcance del equipo, quizá has dificultado el remate. Revisa la dirección del primer golpe y la llegada del salto siguiente.',
  ],
  counters: [
    { title: 'Reaper', body: 'Su daño cercano castiga que te quedes intercambiando golpes y electricidad delante de él. Si se mueve para proteger a un Support, no persigas a ambos por el mismo interior. Busca una altura desde la que puedas caer sobre otra línea o espera a que tus DPS lo obliguen a taparse. Wraith cambia si podéis rematarlo; no convierte en buena cualquier llegada cuando termina.' },
    { title: 'Bastion', body: 'Si está en su configuración de mucho daño y tiene tiro sobre tu aterrizaje, la burbuja puede durar poco. Puedes presionarlo desde cobertura con el secundario o disputar otro ángulo mientras termina esa amenaza. Saltar sobre él no es la única forma de atenderlo. Mira también a quién protege: esperar sin mover al equipo puede dejarle gratis la siguiente posición.' },
    { title: 'Brigitte', body: 'Puede proteger al objetivo con curación y empujarte fuera de la distancia que necesitas. Mira si está junto al otro Support antes de comprometer el salto. Presionar desde otra entrada con un DPS puede obligarla a elegir a quién ayuda; entrar solo por la puerta que ya está defendiendo facilita que te expulse y ambos sigan curándose.' },
    { title: 'D.Va', body: 'No absorbe el disparo principal de Tesla con Matrix, pero puede volver con sus cañones y misiles para expulsarte o matarte antes de que remates al Support. El problema no se resuelve por poder dañarla: comprueba cuánto tiempo puedes quedarte y quién dispara contigo. Si vuelve a la backline, tus DPS quizá tengan otro ángulo disponible; deben poder aprovecharlo antes de que tú caigas.' },
    { title: 'Roadhog', body: 'Un Hook sobre una llegada expuesta puede quitarte la posición que necesitabas para seguir o salir. Usa cobertura para acercarte y mira si ya ha gastado el gancho antes de cruzar su línea. La burbuja puede interceptarlo si queda entre vosotros, pero no te protege de un Roadhog que ya está en el mismo lado. No confíes en que la mera presencia de la barrera arregle el aterrizaje.' },
    { title: 'Mauga', body: 'Mantenerte delante de sus armas mientras intentas bajar al Tank suele alargar un intercambio que no te interesa. Busca una ruta hacia el DPS o Support que puedas disputar con ayuda, sin dejar al resto del equipo solo ante él. Si el mapa y la posición rival impiden esa separación, quizá necesites otro plan de Tank; repetir el salto por el centro no crea un flanco.' },
  ],
  counterplay: [
    'Antes de cambiar por ver a Reaper, mira qué entrada estabas repitiendo. Puede haber una altura desde la que caer sobre otra línea, un DPS al que debías expulsar primero o una llegada más corta que conserve visión de Ana. Haz un ajuste concreto y comprueba si permite al grupo continuar.',
    'Si los dos Supports se ayudan dentro de la burbuja, no intentes ganar el mismo duelo solo por colocarla antes. Coordina otro ángulo sobre uno de ellos, obliga al grupo a separarse o disputa la altura desde la que reciben ayuda. Aislar requiere una posición, no solo pulsar Barrier Projector.',
    'Valora cambiar si, tras ajustar ruta y timing, seguís sin poder disputar una posición útil ni atender la presión sobre vuestro equipo. Elige un Tank que conozcas para ese problema. No hace falta demostrar que puedes sobrevivir a todos los counters si ninguna entrada permite ganar la pelea.',
  ],
  compositions: [
    { title: 'Tracer o Genji llegando al mismo objetivo', body: 'Acordad una llegada que ambos podáis hacer, no solo el nombre del Support. Tracer puede estar preparada en un lateral mientras tú subes; Genji quizá necesite conservar Dash para continuar o salir. Si ya han usado sus recursos de retirada, reduce lo que les pides. Tu burbuja no elimina la necesidad de una salida para los demás.' },
    { title: 'Ana con una línea de curación disponible', body: 'Comprueba desde qué esquina puede verte al terminar el salto. No tiene sentido pedirle Nano desde un interior al que aún no ha llegado. Nano Winston y Primal ofrecen cosas distintas: el primero puede sostener una presión con Tesla y el segundo cambia a golpes y desplazamientos. Decidid qué necesita la pelea antes de gastar las dos ultimates juntas.' },
    { title: 'DPS de rango aprovechando la atención dividida', body: 'Con Ashe o Soldier no siempre tendrás un compañero aterrizando a tu lado. Puedes obligar a un rival de altura a cubrirse mientras ellos cruzan o toman tiro desde lejos. Mira si ese ángulo existe antes de saltar. Si tu entrada desaparece detrás de tres paredes, no pueden acompañarla por mucho que el enemigo se haya girado.' },
  ],
  vodReview: [
    'Pausa antes del salto y mira al DPS que esperabas que te acompañara. Señala desde dónde podía disparar y cuándo tuvo al objetivo a la vista. Compara esa llegada con el momento en que gastaste burbuja.',
    'Sigue una burbuja desde fuera, no solo desde tu cámara. Marca qué enemigos estaban a cada lado y qué disparos de curación interceptó. Así distingues una separación real de una cúpula con todo el equipo rival dentro.',
    'Revisa un salto gastado para entrar y una caída desde altura con salto reservado. Compara las opciones que tenías cuando el objetivo se retiró. No busques una regla de no saltar nunca: busca cuándo la altura permitía conservar la salida.',
    'Elige una entrada tras la que forzaste una defensa pero perdisteis la pelea. Anota también vuestros recursos, la salud al volver y el espacio cedido. La habilidad rival gastada solo explica una parte del resultado.',
    'Con Primal, sigue al enemigo que recibió el primer golpe. ¿Lo acercaste a sus Supports, lo mantuviste alcanzable o lo apartaste del objetivo? Después mira dónde acabaste tú al terminar. No uses solo las bajas para evaluar esos desplazamientos.',
  ],
  checklist: [
    '¿Quién podrá presionar al mismo objetivo cuando aterrice?',
    '¿Puedo llegar desde una altura sin gastar el salto de salida?',
    '¿Qué pared tengo cerca si la burbuja se rompe?',
    '¿Dónde está el Support que ayudará al enemigo al que entro?',
    '¿Debo seguir la persecución o conservar la posición que hemos ganado?',
    'Con Primal, ¿hacia dónde quiero mover al rival y dónde terminaré yo?',
  ],
  faqs: [
    { question: '¿Tengo que saltar sobre un Support con Winston?', answer: 'No. Puede ser mejor expulsar a un DPS de una altura, presionar un ángulo con el secundario o atender una amenaza cerca del grupo. Elige una posición que tus compañeros puedan aprovechar. Un Support lejano no es un objetivo aislado si el resto del equipo rival puede protegerlo al verte llegar.' },
    { question: '¿La burbuja de Winston bloquea toda la curación?', answer: 'No. Puede interceptar ciertas trayectorias, como los disparos de Ana desde fuera, pero no elimina todas las formas de curar. Si quien cura está dentro con el objetivo, no has separado esa línea. Mira a ambos Supports y dónde queda el borde antes de dar por hecho que la burbuja ha aislado a alguien.' },
    { question: '¿Cuándo guardo Jump Pack para salir?', answer: 'Cuando puedes acercarte por cobertura o caer desde una altura sin gastarlo. Eso deja una salida disponible si el objetivo recibe ayuda o cambia de posición. Aun así, elige dónde aterrizarás al volver: tener el salto no sirve de mucho si solo puedes regresar a una línea abierta sin curación.' },
    { question: '¿Para qué sirve el disparo secundario de Winston?', answer: 'Para presionar desde más lejos con un disparo cargado y añadir daño sin comprometer de inmediato Jump Pack. Úsalo desde cobertura y mira si el equipo necesita entrar después. Acertar no obliga a saltar: el objetivo puede seguir con ayuda o retirarse hacia una posición donde no podéis continuar.' },
    { question: '¿Primal Rage necesita conseguir una baja?', answer: 'No. Puede ayudarte a sostener un objetivo, separar a un enemigo o retirarte. Revisa la dirección de los golpes y qué hizo el equipo con el movimiento rival. Empujar a alguien a salvo no es un buen remate, y perseguirlo lejos del punto puede ser innecesario si lo que necesitabais era mantener overtime.' },
    { question: '¿Qué perks tiene Winston en el kit normal?', answer: 'Las Minor son Electric Charge, que da velocidad mientras haces daño con el primario, y Heavy Landing, que mejora el aterrizaje durante Primal. Las Major son Chain Lightning, para rebotes del secundario completamente cargado, y Revitalizing Barrier, para curación dentro de la burbuja. Elige una de cada nivel según las situaciones que puedas aprovechar; no incluyen los resets ni las barreras adicionales de Stadium.' },
  ],
  conclusion: 'En el próximo replay, sigue al segundo Support enemigo durante una de tus entradas. Mira si pudo seguir ayudando al objetivo, si tu burbuja cambió esa línea y cuándo llegó tu DPS. Esa lectura explica mejor por qué el dive funcionó o falló que limitarte a preguntar si saltaste sobre el héroe correcto.',
  links: [
    { href: '/guides/como-jugar-winston-ranked-overwatch', label: 'Practicar el timing del dive con Winston' },
    { href: '/counters/winston', label: 'Cómo puede el rival frenar el dive de Winston' },
    { href: '/team-comps/winston', label: 'Coordinar el seguimiento de un dive' },
    { href: '/maps/numbani', label: 'Disputar las alturas de Numbani' },
    { href: '/maps/lijiang-tower', label: 'Entradas y objetivos de Lijiang Tower' },
    { href: '/heroes/ana', label: 'Conservar la línea de curación de Ana' },
    { href: '/heroes/genji', label: 'Preparar el seguimiento con Genji' },
    { href: '/heroes/dva', label: 'Comparar el dive con el peel de D.Va' },
    { href: '/heroes/reinhardt', label: 'Otra forma de acercarte con Reinhardt' },
    { href: '/roles/tank', label: 'Elegir qué posición necesita el equipo como Tank' },
    { href: '/guides/como-mejorar-como-tank-overwatch', label: 'Revisar las decisiones del Tank durante la pelea' },
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Comparar los recursos gastados en cada entrada' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Seguir el dive desde las cámaras del equipo' },
    { href: '/experts', label: 'Pedir una revisión de tus llegadas y retiradas' },
  ],
}
