import type { HeroPillar } from './hero-pillars'

export const reviewedKirikoHero: HeroPillar = {
  slug: 'kiriko', name: 'Kiriko', role: 'Support', roleSlug: 'support',
  publishedAt: '2026-06-26', schemaDate: '2026-10-03', updatedAt: '3 de octubre de 2026',
  seoTitle: 'Kiriko en Overwatch: Suzu, teleport y Kitsune Rush para ranked',
  seoDescription: 'Cuándo usar Suzu, cómo elegir un teleport seguro y cuándo alternar ofudas y kunais con Kiriko. Ejemplos de ranked, perks, amenazas y revisión de VOD.',
  h1: 'Kiriko en Overwatch: cómo usar Suzu, teleport y Rush',
  kicker: 'Decidir a quién ayudar sin perder una salida',
  intro: [
    'Con Kiriko, no esperes a tener una barra de vida roja para decidir dónde vas a jugar. Busca una posición desde la que puedas curar, probar unos kunais y volver junto a un compañero si te presionan. Swift Step permite salir de muchas situaciones, pero solo si hay un aliado al que puedas llegar y su posición no es peor que la tuya.',
    'Suzu sirve para responder al daño que está llegando, no para quedarse disponible toda la partida por si aparece una ultimate. La decisión cambia si vuestro Tank sigue peleando, si podéis retiraros o si el rival aún tiene otro recurso para castigaros. Aquí encontrarás cómo elegir ese momento, preparar Kitsune Rush y revisar los teleports que parecían un rescate y acabaron en dos muertes.',
  ],
  headerTips: [
    'Suzu: decide qué evita ahora y qué puede amenazar al equipo después de gastarlo.',
    'Teleport: comprueba quién está en el destino y qué cobertura tendrás al llegar.',
    'Rush: coloca el camino donde tus compañeros puedan pelear, no donde te gustaría que estuvieran.',
  ],
  quickAnswers: [
    { title: 'Si Suzu se queda siempre guardado', body: 'Revisa una pelea en la que murió un compañero mientras tú lo conservabas. Si el daño siguiente iba a matarlo y las ofudas no llegaban a tiempo, usar Suzu podía ser correcto aunque no hubiera un efecto que limpiar.' },
    { title: 'Si mueres justo después del teleport', body: 'Mira al aliado de destino antes de pulsar Swift Step: ¿estaba detrás de cobertura, rodeado o retirándose? Llegar con el cooldown gastado a la misma zona amenazada puede dejarte sin salida, aunque todavía tengas Suzu.' },
    { title: 'Si haces daño pero el equipo cae', body: 'Pausa antes del último kunai. Comprueba qué aliado estaba recibiendo focus y cuánto tardaba en llegar tu curación. El problema puede ser la distancia o haber mantenido el duelo cuando ya necesitaban las ofudas.' },
  ],
  facts: [
    { title: 'Curación', body: 'Las ofudas viajan hacia el aliado seleccionado; empezar a curar no significa que la ayuda ya haya llegado.' },
    { title: 'Movilidad', body: 'Puedes trepar y teletransportarte junto a un aliado. La cobertura del destino importa tanto como salir del sitio actual.' },
    { title: 'Defensa', body: 'Suzu ofrece protección breve y limpia muchos efectos negativos, pero no elimina todos los controles.' },
    { title: 'Ultimate', body: 'Kitsune Rush beneficia a quienes aprovechan su camino. No sustituye una ruta de entrada ni obliga al rival a quedarse allí.' },
  ],
  rankedPlan: [
    'Identifica una posición de curación y otra para retirarte. Puedes jugar un lateral con kunais, pero comprueba de vez en cuando dónde están tus compañeros: un aliado que se alejó puede dejar de ser una salida disponible para Swift Step.',
    'Mira qué compañero va a recibir el daño siguiente. Si vuestro Tank está cruzando un espacio abierto, prepara las ofudas antes de que termine el cruce. Una barra alta ahora no asegura que puedas dedicar varios tiros seguidos a un duelo.',
    'Antes de Suzu, distingue entre quitar un efecto y evitar una baja por daño directo. Ambas cosas pueden justificarlo. No lo gastes automáticamente sobre cada aliado morado, pero tampoco dejes morir a alguien solo porque esperabas reservarlo para la granada de Ana.',
    'Después de gastar Suzu, cambia cómo asomas y avisa si el equipo aún está comprometido. Si siguen empujando mientras tú te has cubierto o cambiado de lado, pueden esperar una ayuda que ya no puedes darles.',
    'Prepara Rush con la posición real del grupo. Si Reinhardt está peleando junto a una esquina, orienta el camino para que pueda seguir atacando y recibir ayuda. Una línea larga en un espacio que nadie puede cruzar no mejora la entrada por sí sola.',
  ],
  sections: [
    { title: 'Ofudas: piensa en cuándo llegará la cura', body: 'Un compañero que empieza a recibir focus necesita ayuda antes de que esté a un disparo de morir. Las ofudas tienen tiempo de viaje y pueden llegar tarde si juegas demasiado lejos. Acorta la distancia por una ruta protegida cuando el equipo avance; no uses teleport como sustituto de acompañar cada rotación. Si el aliado se tapa detrás de una esquina, recupera una línea de curación sin cruzar tú por delante del Tank rival.' },
    { title: 'Un lateral útil no te obliga a ganar un duelo', body: 'Asomar unos kunais desde otra puerta puede obligar al enemigo a girarse. Si te contestan, no tienes que quedarte hasta conseguir la baja. Vuelve a cubrirte y comprueba a quién debes curar. Si todos tus teleports son escapadas urgentes, mira cuánto tiempo mantienes el lateral después de que el rival te detecte y si tus compañeros aún estaban a tu alcance.' },
    { title: 'Suzu: limpiar el anti o cubrir el daño siguiente', body: 'Un Tank morado que ya está detrás de una pared puede esperar sin gastar Suzu. El mismo Tank, con enemigos disparándole y sin tiempo para retirarse, puede necesitarlo de inmediato. También puedes usarlo contra daño sin anti-heal si esa protección permite al aliado cubrirse o recibir curación. Después hay que acompañar la salida: la invulnerabilidad es breve y no vuelve segura una posición expuesta.' },
    { title: 'Qué no debes esperar del cleanse', body: 'Suzu puede quitar el anti de la granada de Ana y despertar a un aliado dormido, pero no levantar a alguien que ya ha caído por un derribo como Earthshatter. No trates todos los stuns como si fueran Sleep. Frente a Reinhardt, evita agruparte en su línea y conserva cobertura. Si ya hay compañeros en el suelo, Suzu puede protegerlos del daño posterior, pero no les permitirá levantarse antes.' },
    { title: 'Swift Step: llegar cerca no significa llegar a salvo', body: 'Puedes usarlo a través de paredes, así que no siempre ves los enemigos que rodean al aliado. Mira su movimiento y la presión que recibe antes de confirmar el destino. Si estás acompañando una entrada, llega con una cobertura o una pared que puedas trepar; no cuentes con poder volver a usar Swift Step inmediatamente. Suzu puede dar un margen, pero gastar los dos recursos para aterrizar donde nadie puede ayudarte deja muy pocas opciones.' },
    { title: 'Kitsune Rush: el camino debe servir durante la pelea', body: 'Rush aumenta movimiento y velocidad de ataque, y acelera la recuperación de cooldowns de quienes están en su camino. Eso ayuda si el grupo puede seguir atacando o volver a disponer de sus habilidades mientras disputa la zona. Comprueba la esquina siguiente: el rival puede retroceder fuera de vuestro alcance. No persigas una baja por obligación solo porque has tirado la ultimate; conserva una posición desde la que puedas curar a quienes sí la están aprovechando.' },
    { title: 'Lijiang: cubrir el cruce antes de separarte', body: 'En Garden, imagina que vuestro equipo cruza el puente mientras tú pruebas kunais desde otra puerta. Si el rival empieza a disparar al grupo, vuelve a curar antes de que termine el cruce y el Tank quede fuera de tu línea. Un teleport al último compañero del puente puede dejarte en la misma zona expuesta. Busca el lado del punto donde haya cobertura y compañeros, no solo el icono de aliado más cercano.' },
    { title: 'Dorado: no aterrizar detrás de todo el dive', body: 'Si Winston salta una altura y Genji sigue la entrada, comprueba si puedes ayudar desde abajo o desde una posición cercana antes de usar Swift Step. Teleportarte al jugador más adelantado puede separar tu curación del resto y dejarte sin regreso cuando se retiren. Acordad hacia qué esquina volverán. Si hay una baja posible con seguimiento, puedes acompañarla, pero distingue esa oportunidad de perseguir al último rival por otra habitación.' },
  ],
  abilities: [
    { title: 'Healing Ofuda', body: 'Lanzas talismanes que buscan al aliado seleccionado. Prepara la curación cuando esperas presión y sigue a ese compañero con la cámara para comprobar si la ayuda llega. Si terminas necesitando Suzu en cada cruce, revisa primero desde qué distancia estabas curando.' },
    { title: 'Kunai', body: 'Son proyectiles y sus críticos permiten amenazar al enemigo que asoma. Prueba tiros desde cobertura y cambia de prioridad cuando un aliado necesite ayuda; no conviertas una secuencia fija de kunais entre curas en una regla para cualquier pelea.' },
    { title: 'Swift Step', body: 'Te teletransporta junto a un aliado, incluso a través de paredes. Puede servir para escapar o llegar a una entrada, pero exige un objetivo válido. Antes de usarlo, comprueba si podrás cubrirte al llegar; la vida que le queda al aliado no te dice por sí sola si su posición es segura.' },
    { title: 'Protection Suzu', body: 'Cura, da una ventana breve de invulnerabilidad y elimina muchos efectos negativos. Decide si el aliado necesita esa protección ahora y qué podrá hacer cuando termine. No la confundas con inmunidad duradera ni con una respuesta universal a todos los derribos.' },
    { title: 'Kitsune Rush', body: 'Crea un camino que potencia movimiento, ataque y recuperación de cooldowns. Oriéntalo hacia una zona que tu equipo pueda disputar desde su posición actual. La ultimate puede apoyar una entrada o ayudar a mantener una pelea ya empezada, no solo anunciar un avance.' },
    { title: 'Wall Climb', body: 'Puedes trepar paredes para acceder a otra altura o cambiar de exposición. Mira dónde terminará la subida: salir por el borde que vigila una Widow puede ser peor que seguir protegida abajo. No dependas siempre del teleport para cambiar de posición.' },
  ],
  perksIntro: 'Estas elecciones Minor y Major son alternativas dentro del kit normal. Los poderes de Stadium, como el teleport direccional sin aliado o el reinicio de habilidades al usar Rush, no forman parte de estas elecciones.',
  perks: [
    { title: 'Minor · Urgent Care', body: 'Las ofudas viajan más rápido hacia aliados por debajo de media vida. Puede ayudar cuando empiezan a recibir focus, pero no convierte una línea cortada en curación ni justifica esperar a que el compañero esté crítico para atenderlo.' },
    { title: 'Minor · Fortune Teller', body: 'Acertar kunais envía ofudas adicionales a un aliado que tengas delante. Es alternativa a Urgent Care. Comprueba a quién beneficia esa curación; no da apoyo automático a cualquier compañero que esté en otro lado del mapa.' },
    { title: 'Major · Ready Step', body: 'Después de Swift Step recibes un aumento temporal de velocidad de ataque y recarga. Es una mejora para lo que haces al llegar, no un segundo teleport. No elijas un destino peligroso solo para activar el aumento.' },
    { title: 'Major · Foxtrot', body: 'Suzu aporta también velocidad de movimiento a los aliados afectados. Es alternativa a Ready Step y puede ayudar a llegar a cobertura o continuar una entrada. Comprueba si el compañero tiene una ruta que pueda aprovechar, en lugar de asumir que el extra de velocidad resuelve cualquier focus.' },
  ],
  mistakes: [
    'Guardar Suzu mientras un aliado cae por daño directo. Revisa si una protección breve le habría permitido cubrirse o recibir las ofudas; no hace falta que exista un efecto negativo para justificar su uso.',
    'Gastar Suzu sobre un anti que ya no tiene seguimiento. Un compañero morado detrás de cobertura puede esperar. Mira a los enemigos que todavía tienen tiro antes de decidir que quitar el color era urgente.',
    'Teleportarte a una barra roja sin mirar el destino. En el replay, comprueba qué rivales rodeaban al aliado y dónde podrías haberte cubierto al llegar. Que el botón estuviera disponible no prueba que fuera un rescate posible.',
    'Mantener el duelo de kunais después de que empiece el focus a vuestro Tank. La oportunidad de hacer daño puede terminar antes de que lo mate el rival. Vuelve a curar mientras aún hay tiempo para que llegue la ayuda.',
    'Tirar Rush por una línea que el grupo no puede ocupar. Si tus compañeros están separados, sin recursos o detrás de otra esquina, revisa cómo preparaste la posición antes de valorar el daño conseguido con la ultimate.',
    'Usar Swift Step y Suzu para abandonar un lateral demasiado tarde. No son dos errores por definición: pueden salvarte. Busca el momento anterior en que podías cubrirte sin gastar todo y seguir disponible para el equipo.',
  ],
  counters: [
    { title: 'Ana', body: 'La granada limita cuándo puedes recuperar la vida del compañero expuesto. No limpies por reflejo: distingue el anti que tiene seguimiento del que puede esperarse detrás de cobertura. Si Suzu ya no está, avisa antes de que el Tank vuelva a asomar.' },
    { title: 'Winston', body: 'Puede saltar hacia tu posición mientras el resto del equipo presiona por otro lado. Conserva un aliado de salida que no esté en la misma zona del salto. Si haces teleport junto a quien también está rodeado, habrás cambiado de sitio sin salir de la presión.' },
    { title: 'Tracer', body: 'Puede contestar tu lateral y volver a por otro aliado después de Recall. No te quedes persiguiéndola por orgullo. Recupera una esquina desde la que puedas curar y mira si el otro Support necesita ayuda antes de volver al duelo.' },
    { title: 'Widowmaker', body: 'Te castiga al trepar o asomar una línea larga. No prepares cada kunai desde el mismo borde. Cambia la exposición por cobertura y conserva visión de tus aliados, sin gastar teleport hacia una plataforma que ella también esté vigilando.' },
    { title: 'Reinhardt', body: 'Earthshatter cambia dónde puedes agruparte con tus compañeros. Suzu no elimina ese derribo una vez aplicado. Evita ofrecer una línea con varios jugadores y comprueba desde qué cobertura podrías ayudar a quienes reciban el daño posterior.' },
  ],
  counterplay: [
    'Contra Ana, mira también sus compañeros. Si nadie puede disparar al objetivo morado, esperar bajo cobertura puede conservar Suzu para el momento siguiente. Si un aliado sigue expuesto, la prioridad puede ser limpiarlo y ayudarlo a salir.',
    'Contra dive, acuerda dónde os vais a reunir con el otro Support y comprueba si sigue a tu alcance. Si ambos estáis rodeados en la misma habitación, hacer teleport a su lado no te saca del dive. Necesitas llegar a una esquina donde podáis cubriros o recibir ayuda de los demás.',
    'Frente a una defensa de sniper, usa otra puerta o trepa por un borde que no esté en su línea. No tienes que ganar el duelo de kunais para ayudar al equipo a cruzar. Cura desde una exposición corta y vuelve a cubrirte.',
    'Si el mismo problema se repite tras cambiar la posición y el uso de recursos, valora un Support que conozcas y que aporte la ayuda que falta. No hagas swap por una sola Suzu fallada ni por una estadística baja de daño: explica qué situación cambiará con el nuevo pick.',
  ],
  compositions: [
    { title: 'Junker Queen y Lúcio para llegar juntos', body: 'La velocidad de Lúcio ayuda al grupo a acercarse y Kiriko puede atender el daño que reciben al entrar. Guarda visión de Queen mientras sigue peleando; un lateral de kunais que te separa del grupo puede obligarte a gastar teleport para volver. En Lijiang, preparad el cruce antes de Rush y no asumáis que tirar las dos ayudas de velocidad hará segura cualquier ruta abierta.' },
    { title: 'Winston y Genji con una retirada acordada', body: 'Puedes apoyar una entrada sin aparecer siempre en el mismo sitio que Winston. En Dorado, mira si los aliados de la altura pueden volver hacia un borde que tú veas. Si acompañas con Swift Step, comprueba qué cobertura tendrás mientras recuperas la habilidad. Una baja conseguida no justifica seguir persiguiendo cuando el grupo ya necesita retirarse.' },
    { title: 'Sigma y un DPS que juegue otro ángulo', body: 'Kiriko puede atender al frente y ayudar a un DPS desde una segunda posición. Si estás intercambiando kunais, mira qué compañero está contestando el rival. Teleportarte al DPS puede resolver una amenaza local, pero deja de ser útil si Sigma se queda sin la curación que esperaba durante ese cambio. Avisar y ajustar la posición evita depender de dos rescates a la vez.' },
  ],
  vodReview: [
    'Busca un aliado que murió con Suzu disponible. Retrocede hasta antes del focus y mira distancia, cobertura y tiempo de llegada de las ofudas. Distingue una protección que podía darle margen de una situación en la que ya no había ayuda suficiente.',
    'Elige una Suzu que limpió anti-heal. Pausa al impactar y mira quién podía disparar al aliado y qué hizo después. Quitar el efecto no demuestra que el uso fuera urgente; sobrevivir tampoco demuestra que debieras gastarla siempre en ese mismo momento.',
    'Revisa un teleport sin seguir solo tu cámara. Mira la posición del aliado antes de llegar, los enemigos alrededor y la cobertura disponible. Si murieron los dos, busca si el rescate tenía una salida o si podías haber ayudado desde otra posición.',
    'En un duelo de kunais, localiza el primer momento en que otro aliado empezó a recibir presión. Comprueba si cambiaste de prioridad a tiempo para que llegaran las ofudas. Trabaja esa lectura antes de imponerte una cantidad fija de tiros entre cada cura.',
    'Pausa una Rush antes de activarla. Mira dónde están los compañeros, qué pueden atacar y hacia dónde puede retirarse el rival. Si apenas la usó el equipo, revisa la colocación y el momento, no solo cuántas bajas hubo al terminar.',
  ],
  checklist: [
    '¿A quién van a llegar las ofudas si empieza el focus?',
    '¿Qué aliado sigue siendo un destino seguro de teleport?',
    '¿El anti tiene seguimiento o puede esperarse bajo cobertura?',
    '¿Qué podrá hacer el compañero cuando termine Suzu?',
    '¿Puedo seguir curando después de asomar este lateral?',
    '¿Mis compañeros pueden disputar el camino de Rush desde aquí?',
  ],
  faqs: [
    { question: '¿Tengo que guardar siempre Suzu para la granada de Ana?', answer: 'No. La granada es una amenaza importante, pero Suzu también puede evitar una baja por daño directo. Compara el peligro actual con lo que puede venir después. Un anti sin seguimiento puede esperarse bajo cobertura; un aliado que va a morir antes de recibir curación puede necesitar protección ahora.' },
    { question: '¿Suzu elimina todos los stuns?', answer: 'No. Puede quitar Sleep, pero no un derribo ya aplicado como Earthshatter. No uses la misma respuesta para cualquier control. Frente a Reinhardt, evita ofrecer una línea con varios aliados y busca cómo ayudar frente al daño posterior.' },
    { question: '¿Swift Step puede atravesar paredes?', answer: 'Sí, permite llegar junto a un aliado incluso a través de paredes. Necesitas un objetivo válido y conviene comprobar su situación antes de usarlo. Una barra de vida baja avisa de presión, no garantiza que puedas llegar, salvarlo y salir.' },
    { question: '¿Cuántos kunais debería tirar entre curas?', answer: 'No hay una secuencia que funcione en todas las peleas. Mira quién recibe el daño siguiente y cuánto tarda en llegar tu curación. Si empieza un focus o pierdes visión del grupo, termina el duelo y recupera una posición desde la que puedas ayudar.' },
    { question: '¿Por qué nadie aprovecha mi Kitsune Rush?', answer: 'Comprueba la posición del equipo antes de lanzarla: puede estar demasiado separado, detrás de otra esquina o sin acceso al rival. Prepara el camino para la pelea que podéis jugar ahora, sin pedir a los compañeros que atraviesen una línea abierta solo para entrar en la ultimate.' },
    { question: '¿Puedo usar teleport sin aliado o reiniciar el kit con Rush?', answer: 'No son capacidades de estas elecciones de ranked. Hay poderes de Stadium que cambian el teleport o el efecto de Rush; no debes contar con ellos al preparar una partida con el kit normal. Las perks Minor y Major se eligen por separado.' },
  ],
  conclusion: 'Para la siguiente partida, elige un hábito concreto: comprobar el destino antes de un teleport o empezar las ofudas antes del focus. Revisa después una situación en la que ese hábito podía cambiar tu decisión. Acertar más kunais ayuda, pero saber cuándo dejar el duelo y a quién atender hace que esos tiros encajen en la pelea del equipo.',
  links: [
    { href: '/guides/como-jugar-kiriko-ranked-overwatch', label: 'Practicar Suzu y teleport en ranked' },
    { href: '/counters/kiriko', label: 'Leer los matchups frente a Kiriko' },
    { href: '/team-comps/kiriko', label: 'Preparar un equipo con Kiriko' },
    { href: '/roles/support', label: 'Prioridades de Support durante la pelea' },
    { href: '/heroes/ana', label: 'Entender la granada y el Sleep de Ana' },
    { href: '/heroes/genji', label: 'Acompañar las entradas de Genji' },
    { href: '/maps/lijiang-tower', label: 'Preparar los cruces de Lijiang Tower' },
    { href: '/maps/dorado', label: 'Jugar las alturas de Dorado' },
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Comparar recursos antes y después de Suzu' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Revisar una decisión en el replay' },
    { href: '/experts', label: 'Consultar una partida de Kiriko' },
  ],
}
