import type { HeroPillar } from './hero-pillars'

export const reviewedDoctrineHero: HeroPillar = {
  slug: 'doctrine', name: 'Doctrine', role: 'Support', roleSlug: 'support', analysisStatus: 'trial',
  publishedAt: '2026-09-12', schemaDate: '2026-10-04', updatedAt: '4 de octubre de 2026',
  seoTitle: 'Doctrine en Overwatch: habilidades, Imbuir y perks del trial',
  seoDescription: 'Qué hace cada versión de Imbuir, cómo funcionan los drones y qué coste tienen sus perks. Kit del trial de Doctrine antes del estreno anunciado para el 6 de octubre.',
  h1: 'Doctrine en Overwatch: habilidades y decisiones del kit de prueba',
  kicker: 'Cetro eterno, Imbuir y drones · antes de Season 5',
  intro: [
    'Doctrine es el nuevo Support anunciado para el 6 de octubre de 2026, con Season 5. Su trial del 12 al 14 de septiembre ya terminó. Aquí encontrarás el kit mostrado en aquella prueba: no lo confundas con los valores definitivos ni con una tier list de lanzamiento.',
    'La decisión más interesante es qué potenciar con Imbuir. Puedes mejorar el disparo, ganar vuelo con Impulso velado o recibir también los efectos de los drones. Por ejemplo, gastar esa mejora para perseguir a un enemigo deja de tener buena pinta si después necesitas escapar de un dive. Conviene mirar la posición del equipo antes de elegir la versión ofensiva.',
  ],
  headerTips: [
    'Busca cobertura desde la que veas al aliado al que debes curar, no solo al enemigo al que quieres disparar.',
    'Antes de Imbuir, decide si necesitas el disparo, el movimiento o el efecto propio de los drones.',
    'Si revisas un vídeo de septiembre, no des por hecho que sus cifras seguirán iguales en el estreno.',
  ],
  quickAnswers: [
    { title: '¿Qué mejora Imbuir?', body: 'El disparo de Cetro eterno se vuelve un proyectil perforador mayor; Impulso velado permite volar libremente; los Drones vigorizantes también afectan a Doctrine. Son usos distintos de la mejora de la siguiente acción. No cuentes con los tres a la vez para justificar una entrada.' },
    { title: '¿Los drones sirven para cualquier engage?', body: 'Curación y velocidad de ataque ayudan al aliado que está participando. Si los envías a alguien que todavía no tiene tiro o está volviendo del spawn, no estás reforzando la pelea que ocurre delante. Mira primero quién puede atacar y quién necesita sobrevivir.' },
    { title: '¿Se puede jugar ahora?', body: 'La prueba de septiembre terminó. El estreno está anunciado para el 6 de octubre; los clips del trial no indican que siga disponible. Los ejemplos de esta ficha sirven para entender las herramientas mostradas, no para prometer un resultado en ranked antes de su lanzamiento.' },
  ],
  facts: [
    { title: 'Support, héroe 54', body: 'Combina curación y daño con Cetro eterno. Que el arma tenga ambos usos no elimina la necesidad de elegir a quién apuntar en cada momento.' },
    { title: 'Ligado a Talon', body: 'Su presentación lo vincula con Doomfist. Compartir historia con otros héroes no demuestra que formen una buena composición jugable.' },
    { title: 'Balance por comprobar al estreno', body: 'Las habilidades y las cifras que aparecen aquí corresponden al kit del trial. No hay una comparación confirmada con los valores finales de Season 5 en esta revisión.' },
  ],
  rankedPlan: [
    'Empieza en una cobertura con visión de los aliados expuestos. Si solo ves al Tank enemigo, cambia el ángulo antes de intentar alternar daño y curación.',
    'Identifica la amenaza que podría alcanzarte. Si un flanker tiene acceso a tu posición, no planifiques el movimiento únicamente para acompañar una persecución.',
    'Elige el uso de Imbuir según la siguiente acción. El vuelo puede permitir cambiar de altura; los drones imbuidos pueden ayudarte a ti además de al aliado. No los trates como la misma respuesta defensiva.',
    'Tras ayudar al engage, comprueba que sigues viendo al grupo. Si el Tank dobla otra esquina, llegar tarde y solo puede ser peor que pedirle que vuelva a una línea de curación.',
    'Con Liberación, mira quién puede aprovechar la presión sobre los enemigos afectados y quién necesita el overhealth. Una ultimate no arregla por sí sola una entrada con el equipo separado.',
  ],
  sections: [
    { title: 'Imbuir: elegir también significa renunciar', body: 'Piensa en un rival que sale de cobertura mientras un Genji se acerca por otro acceso. Un disparo mejorado puede ser tentador, pero el siguiente problema quizá sea encontrar una salida. La elección no consiste en pulsar Imbuir siempre que esté disponible: mira qué vas a hacer después y qué alternativa estás dejando de usar. Antes de repetir la presión, comprueba que vuelves a disponer de la mejora; no prepares otra entrada contando con ella por costumbre.' },
    { title: 'Curar al compañero que recibe daño ahora', body: 'Imagina a tu Tank detrás de una esquina y a Cassidy expuesto junto a ti. Seguir buscando al Tank en la otra habitación puede dejar sin ayuda al compañero al que sí puedes curar. Mira la pelea presente: quién está recibiendo focus, quién puede taparse y quién está fuera de tu alcance. Si pierdes visión, comunicarlo es más útil que cruzar una sightline peligrosa para recuperar el mismo objetivo.' },
    { title: 'Lijiang, Control Center: seguir una entrada sin perder el acceso', body: 'Imagina que el grupo entra al interior y tú todavía estás junto a la puerta. Antes de asomarte para añadir daño, busca desde dónde podrás seguir curando si avanzan. Si giran hacia otra zona, no quedes en medio de la entrada intentando apuntar a dos direcciones. Puedes acompañarles hasta una cobertura con visión o pedir que no sigan solos; perseguirlos por la puerta mientras recibes focus puede dejaros sin ayuda a ambos.' },
    { title: 'Gibraltar: vuelo no significa que el equipo pueda seguirte', body: 'La versión imbuida del movimiento permite volar libremente según el kit mostrado. Eso no asegura que ocupar una altura sea buena idea: mira quién puede acompañarte, qué ángulo se abre y si el aliado al que ayudabas queda fuera de visión. Subir para cubrir una entrada no es lo mismo que subir para perseguir una kill dejando el resto de la pelea abajo.' },
    { title: 'Liberación: preparar el siguiente focus', body: 'La reducción de salud máxima del rival y el overhealth aliado ofrecen cosas distintas. Decide con el equipo qué enemigo podéis presionar y desde dónde. No asumas que la reducción equivale a matar ni que elimina otras defensas. Si varios compañeros están retirándose, mira si pueden volver a participar antes de gastar la ultimate intentando cambiar una pelea que ya abandonaron.' },
  ],
  abilities: [
    { title: 'Cetro eterno', body: 'Arma de alcance medio que sana a aliados e inflige daño a enemigos. Con Imbuir lanza un disparo perforador mayor. La descripción del trial no basta para afirmar que atraviese barreras: no prepares un tiro contra un escudo contando con una interacción que no está comprobada.' },
    { title: 'Imbuir', body: 'Añade un efecto potente a la siguiente habilidad. Elige entre el disparo mejorado, el vuelo de Impulso velado y los drones que también te afectan. Haz esa elección antes de comprometer la posición; buscar una salida después de usar la mejora ofensiva es otro problema.' },
    { title: 'Impulso velado', body: 'Desplazamiento horizontal durante el que sufres menos daño. Imbuir permite volar libremente. Menos daño no significa inmunidad ni cleanse: busca una cobertura de llegada y no dependas de atravesar cualquier ataque sin consecuencias.' },
    { title: 'Drones vigorizantes', body: 'Despliegas drones hacia un aliado para darle curación y velocidad de ataque. Con Imbuir también te afectan. Comprueba si ese compañero puede participar en el intercambio; aplicar la mejora mientras no tiene tiro no consigue el mismo seguimiento que ayudarle durante su entrada.' },
    { title: 'Liberación', body: 'Lanza un enjambre de drones que reduce la salud máxima del enemigo y otorga exceso de salud a los aliados. Para aprovecharlo, prepara el focus antes de lanzarlo y revisa qué defensa conserva el rival. Reducir su máximo no equivale a asegurar una baja; el daño y el seguimiento del equipo siguen importando.' },
    { title: 'Superviviente', body: 'La pasiva de subrol inicia la regeneración de salud pasiva al usar habilidades de movimiento. No es lo mismo que recuperar toda la vida de inmediato. Recolocarte hacia una cobertura permite separar la salida del siguiente intercambio, en lugar de volver a exponerte esperando que la pasiva aguante el focus.' },
  ],
  perksIntro: 'El kit del trial muestra dos alternativas Minor al nivel 2 y dos Major al nivel 3. Eliges una de cada nivel, no las cuatro. Las cifras siguientes pertenecen a esa prueba y no se presentan como balance final de lanzamiento.',
  perks: [
    { title: 'Minor · Salvación', body: 'Los Drones vigorizantes sanan 40 de salud al aplicarse. Añade una cura inicial al uso de la habilidad. Si el aliado sigue recibiendo focus en abierto, ese primer aporte no sustituye la cobertura ni garantiza que sobreviva al siguiente ataque.' },
    { title: 'Minor · Succión sanguinaria', body: 'Te sana un 50% del daño infligido con Cetro eterno imbuido. Depende de acertar el disparo mejorado y hacer daño; no es recuperación por cada tiro normal. Elegirlo no elimina la necesidad de ayudar al aliado que está bajo presión.' },
    { title: 'Major · Transfusión', body: 'El daño y la curación realizados reducen el tiempo de reutilización de Imbuir. Si pierdes visión de la pelea mientras buscas un flanco, también pierdes oportunidades de aportar desde allí. Mantén una posición que te permita participar y mira cuándo vuelve la mejora antes de decidir el siguiente uso; la descripción del perk no fija una reducción concreta.' },
    { title: 'Major · El precio de la vida', body: 'Sacrificas 25 de salud máxima para aumentar un 20% la curación de Cetro eterno. Es una reducción de tu máximo, no simplemente recibir 25 de daño que luego puedas curar. Antes de escogerlo, considera cuánto te están presionando y si puedes mantener una posición protegida.' },
  ],
  mistakes: [
    'Usar Imbuir para buscar daño sin mirar por dónde puede llegar un flanker. Revisa qué opción de movimiento o de drones necesitabas cuando apareció la amenaza.',
    'Mantener el crosshair sobre el rival mientras un compañero visible recibe focus. Mira si el cambio de objetivo llegaba a tiempo y si ese aliado podía taparse; no atribuyas todo a un fallo de aim.',
    'Enviar los drones al nombre habitual en vez de al aliado que está participando. Sigue su cámara: quizá aún estaba recargando, sin tiro o demasiado lejos de la entrada.',
    'Volar hasta una altura desde la que ya no ves a tu equipo. Anota qué línea de curación pierdes y si puedes volver sin cruzar otro ángulo peligroso.',
    'Tomar el overhealth de Liberación como permiso para entrar solo. Comprueba qué compañeros podían seguir el focus, no solo cuántos enemigos alcanzó la ultimate.',
    'Copiar las cifras de un clip de septiembre como si fueran valores actuales. Conserva la fecha de la partida y compara el kit antes de convertir el resultado en una recomendación.',
  ],
  counters: [
    { title: 'Winston, Tracer o Genji llegando juntos', body: 'Si uno te obliga a moverte y otro cubre la llegada, no basta con salir del primer ataque. Necesitas un destino con ayuda y saber qué uso de Imbuir conservabas. En un replay del trial, sigue a ambos enemigos: así puedes distinguir una mala llegada de una salida razonable que nadie pudo cubrir.' },
    { title: 'Widowmaker o Ashe desde otra línea', body: 'Buscar daño a media distancia puede exponerte a alguien que apunta desde más lejos. Puedes conservar una línea de curación sin mantener el cuerpo delante del sniper. Mira qué pared tapa su ángulo y si la posición que eliges permite seguir al aliado sin volver a asomarte al mismo tiro.' },
    { title: 'Presión mientras el grupo dobla una esquina', body: 'Si el Tank desaparece de tu visión y te atacan desde un lateral, tienes dos problemas distintos. No persigas la cura cruzando por delante del segundo enemigo. Comunica que no ves al compañero y busca una salida con los que siguen cerca.' },
    { title: 'Sombra: separar el kit actual del rework', body: 'El cambio anunciado a Support llegará con Season 5; en esta revisión no se da por comprobado su nuevo kit. No extrapoles el matchup de su versión DPS ni supongas que pertenecer a Talon convierte a ambos en una buena pareja. Habrá que distinguir qué interacciones existen tras el cambio.' },
  ],
  counterplay: [
    'Contra el kit de prueba, observa qué acción acaba de potenciar Doctrine antes de presionar. Que haya usado una versión ofensiva no demuestra un cooldown concreto; evita anunciar un tiempo libre que no has comprobado.',
    'Divide sus líneas de visión con posiciones distintas, en vez de asumir que disparar al mismo Tank siempre le obliga a dejar de curar. Mira también si tus compañeros pueden sostener esos ángulos sin ayuda.',
    'Para valorar un duelo, conserva el momento del replay y el estado de ambos equipos. Una kill con ventaja de jugadores no demuestra que el héroe gane ese matchup por su kit.',
  ],
  compositions: [
    { title: 'Un aliado que puede aprovechar los drones', body: 'El primer criterio no es la facción ni una lista de nombres: es si quien recibe curación y velocidad de ataque tiene tiro durante ese momento. Imagina a Cassidy buscando un enemigo junto a tu cobertura: puedes seguir su entrada sin alejarte del grupo. Si luego cruza detrás de otra pared, revisa si puede seguir recibiendo ayuda antes de acompañar la persecución.' },
    { title: 'Entradas que conservan la línea de curación', body: 'En una pelea cercana, imagina una entrada de Reinhardt hasta una esquina que puedes ver. Si sigue hasta otra habitación, el problema ya no es elegir la mejor mejora ofensiva: necesitas recuperar visión sin quedar expuesto. Decidid dónde vais a parar y quién cubre el acceso lateral; entrar por separado hace más difícil repartir la ayuda aunque todos estéis cerca del punto.' },
    { title: 'Ayuda defensiva cuando tienes que salir', body: 'Valora qué puede hacer el otro Support o un DPS cuando te presionan. Que Doctrine tenga movimiento no obliga a dejarlo solo ni demuestra que pueda seguir cada dive del Tank. Reparte quién acompaña la entrada y quién mantiene una posición desde la que responder al atacante de atrás.' },
  ],
  vodReview: [
    'Localiza un uso de Imbuir y pausa antes de la acción mejorada. Anota quién recibía daño, la amenaza que se acercaba y las opciones que dejaste de usar.',
    'Sigue al receptor de los drones durante ese intercambio. Comprueba si tenía tiro o podía participar; separa el buff bien elegido de uno aplicado demasiado pronto.',
    'Revisa un Impulso velado desde salida y llegada. Mira cobertura, visión del equipo y ayuda disponible, no solo si evitaste el primer ataque.',
    'Para Liberación, comprueba qué compañeros seguían peleando y quién tenía tiro sobre los afectados. No atribuyas la victoria a la ultimate si la pelea ya estaba ganada.',
    'Si comparas clips, anota que pertenecen al trial de septiembre. No uses esa comparación para afirmar daño, alcance o cooldowns definitivos sin contrastarlos.',
  ],
  checklist: [
    'Sé qué aliado visible necesita ayuda durante este intercambio.',
    'Tengo cobertura al cambiar de curación a daño.',
    'He elegido una acción concreta para Imbuir, sin contar con todas sus mejoras a la vez.',
    'Mi posición de llegada conserva visión o ayuda del equipo.',
    'Distingo el kit de prueba de los valores de lanzamiento.',
  ],
  faqs: [
    { question: '¿Qué rol tiene Doctrine?', answer: 'Es Support, presentado como el héroe 54. Cetro eterno cura a los aliados y daña a los enemigos; los drones aportan curación y velocidad de ataque.' },
    { question: '¿Cuándo sale Doctrine?', answer: 'El estreno está anunciado para el 6 de octubre de 2026 con Season 5. Esta ficha se revisó antes de ese lanzamiento y describe el kit mostrado en el trial.' },
    { question: '¿Sigue abierto el trial de Doctrine?', answer: 'No. La prueba temporal fue del 12 al 14 de septiembre de 2026 y ya terminó. Que haya vídeos disponibles no significa que puedas seguir jugando aquella prueba.' },
    { question: '¿Qué versiones tiene Imbuir?', answer: 'Mejora el disparo de Cetro eterno, permite volar libremente con Impulso velado o hace que los Drones vigorizantes también afecten a Doctrine. Potencia la siguiente acción; no se presentan las tres mejoras como simultáneas.' },
    { question: '¿El disparo imbuido atraviesa barreras?', answer: 'La descripción del kit mostrado dice que es un disparo perforador mayor, pero eso no permite afirmar aquí que atraviese barreras. Esa interacción no está comprobada en esta revisión.' },
    { question: '¿Qué perks Minor y Major se mostraron?', answer: 'Minor: Salvación y Succión sanguinaria. Major: Transfusión y El precio de la vida. Son alternativas por nivel; las cifras de esta ficha corresponden al trial, no a una comprobación del balance final.' },
    { question: '¿El precio de la vida hace daño a Doctrine?', answer: 'El perk mostrado sacrifica 25 de salud máxima para mejorar un 20% la curación del arma. Reduce el máximo, no equivale simplemente a perder 25 de vida que puedas recuperar después con una cura.' },
    { question: '¿Ya se conocen sus mejores counters y composiciones?', answer: 'Esta ficha propone situaciones que conviene comprobar, no una clasificación definitiva. La posición, el seguimiento y la elección de Imbuir pueden estudiarse con el kit mostrado; los matchups y el balance de lanzamiento necesitan comprobarse aparte.' },
  ],
  conclusion: 'Para entender a Doctrine antes del estreno, sigue una decisión cada vez: qué necesitaba el equipo, qué acción mejoraste y dónde acabaste. Esa lectura permite aprender del trial sin convertir cada clip en una promesa sobre Season 5.',
  links: [
    { href: '/guides/como-mejorar-como-support-overwatch', label: 'Posición y prioridades como Support' },
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Revisar qué necesitabas antes de gastar un cooldown' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Separar decisiones y ejecución en una VOD' },
    { href: '/doctrine-support-sombra-roadhog-rework-overwatch', label: 'El anuncio de Doctrine y los reworks de Season 5' },
    { href: '/roles/support', label: 'Opciones dentro del rol de Support' },
    { href: '/heroes/ana', label: 'Ana: mantener la visión durante una entrada' },
    { href: '/heroes/kiriko', label: 'Kiriko: elegir la llegada y conservar una salida' },
    { href: '/maps/watchpoint-gibraltar', label: 'Gibraltar: alturas y seguimiento del equipo' },
    { href: '/maps/lijiang-tower', label: 'Lijiang Tower y las entradas a Control Center' },
    { href: '/news', label: 'Noticias de Overwatch' },
    { href: '/counters', label: 'Consultar otros matchups de Overwatch' },
    { href: '/team-comps', label: 'Condiciones de victoria de las composiciones' },
    { href: '/experts', label: 'Buscar ayuda para revisar tus decisiones como Support' },
  ],
}
