import type { HeroPillar } from './hero-pillars'

export const reviewedShionHero: HeroPillar = {
  slug: 'shion', name: 'Shion', role: 'DPS', roleSlug: 'dps',
  publishedAt: '2026-06-15', schemaDate: '2026-10-04', updatedAt: '4 de octubre de 2026',
  seoTitle: 'Shion en Overwatch: Joyride, Execution, perks y counters',
  seoDescription: 'Prepara el flanco con Shion, apunta Execution y vuelve a cobertura con Evade. Habilidades, perks Minor y Major, cambios de balance y decisiones para ranked.',
  h1: 'Shion en Overwatch: entrar con ventaja y salir del flanco',
  kicker: 'Flanker · movilidad, remates y rutas de salida',
  intro: [
    'Antes de subirte a la moto, mira dónde está tu equipo y qué te espera al desmontar. Si llegas detrás de Ana mientras tus compañeros siguen volviendo del spawn, ella puede dedicarte Sleep y recibir ayuda sin dejar ninguna otra amenaza desatendida. La movilidad te permite llegar; no garantiza que ese sea un buen momento para pelear.',
    'Shion combina Kira Pistols, Execution, Joyride y Evade para presionar por un lateral y volver a cobertura. Esta guía explica cómo elegir ese lateral, cuándo cerrar un duelo y qué cambia con sus perks. También separa el nerf de junio de los ajustes posteriores: el historial importa si comparas un vídeo antiguo con lo que puedes hacer ahora.',
  ],
  headerTips: [
    'Antes del engage, elige dónde desmontas y por dónde vuelves si no cae nadie.',
    'Mira a quién puede disparar tu equipo, no solo a quién alcanzas con Joyride.',
    'Evade añade overhealth durante un momento; no te vuelve invulnerable.',
  ],
  quickAnswers: [
    { title: 'Si llegas al flanco demasiado pronto', body: 'Puedes esperar tapada o enseñar el ángulo sin gastar toda la movilidad. Mira cuándo tu Tank y el otro DPS empiezan a presionar. Si todavía no pueden seguir, cruzar hasta la espalda rival puede convertir una ruta buena en un duelo contra varios. No necesitas entrar por main, pero sí coincidir con una amenaza aliada.' },
    { title: 'Si fallas el remate de Execution', body: 'Comprueba el aim, la dispersión y la ayuda que recibió el objetivo. Mantener pulsado concentra la descarga, pero no obliga al enemigo a quedarse en tu línea. Si se tapa o llega peel, no encadenes Evade hacia delante solo para acabar el intento: puedes retirarte y preparar otro contacto.' },
    { title: 'Si Shion está atacando a tus Supports', body: 'Ayuda desde una posición que siga cubriendo al equipo. Vigila el acceso, avisa y espera una oportunidad real para usar el control. Seguir la moto por varias esquinas puede alejarte del compañero al que querías proteger. Mira quién sigue recibiendo daño cuando Shion se retira.' },
  ],
  facts: [
    { title: 'Rol y lanzamiento', body: "DPS de subrol Flanker, disponible desde el 16 de junio de 2026 con Season 3: Into the Tiger's Den. Es una ómnica al frente del Clan Hashimoto de Tokio." },
    { title: 'Kira Pistols y Execution', body: 'Las pistolas mantienen presión y Execution permite concentrar una descarga. Antes de usarla, mira el movimiento del objetivo y si un aliado puede seguir el daño.' },
    { title: 'Evade', body: 'Dash con overhealth breve. Puedes usarlo para cambiar de posición, pero necesitas una llegada donde no te siga alcanzando todo el focus.' },
    { title: 'Joyride', body: 'Al reactivarla desmontas y lanzas la moto. Decide por separado dónde acaba Shion y hacia dónde va el vehículo.' },
  ],
  rankedPlan: [
    'Mientras el equipo se reúne, localiza un acceso lateral y una cobertura de regreso. Mira si el rival lo está vigilando; que sea una ruta distinta de main no significa que esté libre.',
    'Acércate con munición y comprueba dónde puede curarte tu equipo. Un pack puede ayudar a sostener el flanco, pero no sustituye la vuelta si el rival ocupa esa zona. No cuentes con un pack que ya está recogido o al que no puedes llegar.',
    'Empieza a presionar cuando tus compañeros también puedan intervenir. Busca al enemigo que se ha separado o que acaba de gastar una defensa, sin asumir que todo cooldown visto desde lejos sigue en recarga cuando llegas.',
    'Durante el duelo, distingue avanzar, apuntar y salir. Execution requiere una línea útil; Joyride y Evade pueden cambiar tu posición, pero gastar ambas hacia el mismo enemigo deja menos alternativas si recibe ayuda.',
    'Después de forzar una respuesta, mira qué consiguió el equipo. Si ganó una posición, vuelve a un ángulo desde el que puedas ayudar a mantenerla. Si nadie pudo aprovechar la distracción, ajusta el timing del siguiente intento antes de repetir la misma vuelta.',
  ],
  sections: [
    { title: 'Desmontar no es lo mismo que tener cobertura', body: 'Antes de lanzar la moto, mira dónde quedará tu cuerpo. Puedes acertar al objetivo y aun así desmontar en una línea que otro DPS ya cubre. Prepara un lateral desde el que puedas seguir con las pistolas o taparte si aparece ayuda. No valores Joyride solo por el impacto: sigue también la posición de Shion después de soltarla.' },
    { title: 'Execution necesita una línea, no una persecución', body: 'Si el enemigo retrocede a una esquina, puedes preparar el siguiente ángulo mientras tu equipo avanza. Cargar la descarga y perseguirlo hasta una habitación sin curas no asegura el remate. Mira cuándo tienes tiro y cuánto durará: una rotación previsible ofrece una oportunidad distinta de un rival que ya puede esconderse. Si no se abre esa línea, sigue presionando desde una posición segura o cambia de objetivo.' },
    { title: 'Evade puede servir para atacar, pero mira lo que queda después', body: 'No hay que reservarlo siempre para huir. Puede ayudarte a esquivar una amenaza o alcanzar otro ángulo durante un duelo. La pregunta es qué te queda al terminar: cobertura, Joyride disponible, ayuda aliada o una retirada a pie. El overhealth breve no compensa acabar en medio de varios enemigos que todavía pueden disparar.' },
    { title: 'Neon Junction: no te adelantes sola al siguiente tramo', body: 'Al capturar el punto empieza la escolta de ANDROMEDA III hacia Zuiko-za. Antes de recorrer el siguiente lateral, comprueba dónde quedó el equipo que acaba de ganar y quién está empujando. Si llegas a la nueva defensa antes que tus compañeros, puedes consumir toda la movilidad mientras ellos aún se colocan. Prepara el ángulo sin asomarte de más y coincide con su avance; después comprueba si tu presión permitió mover la carga.' },
    { title: 'Esperança: mira el robot antes de repetir la vuelta', body: 'Tras una baja, el rival puede reagruparse por otra calle mientras el robot sigue moviéndose. Volver al mismo lateral porque funcionó antes puede dejarte buscando a un enemigo que ya no está allí. Mira la nueva posición de ambos equipos y el recorrido de regreso. La moto permite rotar deprisa, pero una vuelta larga sigue costando el tiempo en que tu equipo pelea sin tu daño.' },
    { title: 'Tres avances de la ultimate no son tres entradas independientes', body: 'Con Satsuriku Spree, prepara hacia dónde continuarás después del primer avance. Si solo miras al primer objetivo, los siguientes pueden llevarte lejos del daño aliado o contra una cobertura que corta el seguimiento. Úsala cuando puedes disputar la pelea que queda, no para salvar por tu cuenta una situación en la que tus compañeros ya han caído. Acabar una baja importa, pero también qué posición conservas después.' },
  ],
  abilities: [
    { title: 'Kira Pistols', body: 'Pistolas de anima de disparo rápido. Mantén el objetivo a la vista sin quedarte quieta en un acceso que el rival ya está cubriendo. Puedes añadir daño al enemigo que pelea con tu Tank o presionar desde el lateral; recarga al taparte antes de comprometer el siguiente duelo. No necesitas abrir siempre con Execution si las pistolas ya permiten forzar una retirada.' },
    { title: 'Execution', body: 'Dispara una descarga en X y puedes mantener pulsado para estrechar la dispersión. Elige cuándo soltarla según la línea y el movimiento que tienes delante. Un objetivo por debajo de media vida puede beneficiarte con X Machina, pero todavía puede taparse o recibir ayuda. No confundas el tiempo de recuperación tras disparar con el cooldown completo de la habilidad.' },
    { title: 'Joyride', body: 'Activa la moto; al reactivarla desmontas y la lanzas hacia delante. Piensa en el traslado, la llegada de Shion y el lanzamiento como decisiones relacionadas, no como una baja automática al tocar al enemigo. Si el rival cubre la salida de la ruta, puedes cambiar de recorrido antes de comprometerte. El impacto mientras conduces y el lanzamiento no son el mismo daño ni se ajustaron del mismo modo.' },
    { title: 'Evade', body: 'Es un dash que concede overhealth brevemente. No es invulnerabilidad ni una limpieza de todos los efectos. Úsalo para cambiar una línea de tiro o completar un paso hacia cobertura; si termina frente a una nueva amenaza, el bonus puede desaparecer antes de resolver el duelo. Con Rapid Reload también devuelve munición, pero no reemplaza la salud que te falta.' },
    { title: 'Satsuriku Spree', body: 'Avanzas tres veces entre disparos. Antes de activarla, comprueba las salidas del objetivo, el espacio disponible y quién puede seguir. No des por hecho que todo el recorrido será seguro porque el primer avance acierta. Si la pelea ya no tiene seguimiento, conservar la ultimate puede ayudarte en el siguiente intento completo.' },
    { title: 'Flanker', body: 'Su subrol favorece aprovechar los health packs. Para jugar alrededor de uno necesitas comprobar su estado y la ruta de acceso. Si el rival coloca presión allí, no tienes una retirada segura solo por conocer su ubicación. Tampoco conviertas el bonus del pack en una razón para abandonar las curas de tu equipo antes de cada pelea.' },
  ],
  perksIntro: 'En partidas con perks eliges una Minor y una Major al desbloquear sus niveles. Rapid Reload compite con X Machina; Refuel, con Faces of Death. Decide qué necesitas sostener: la munición del duelo, un remate, la salud durante Joyride o las pasivas de los otros subroles. La opción que te ayuda en este duelo no tiene por qué ser la misma que necesitas en otro mapa.',
  perks: [
    { title: 'Minor · Rapid Reload', body: 'Evade recarga 9 de munición. Puede ayudarte a seguir disparando después de cambiar de posición. Antes de elegirlo, mira si tus duelos se interrumpen por recargar o por quedarte sin salud y cobertura. No gastes el dash en campo abierto solo para recuperar esas balas si puedes recargar tapada.' },
    { title: 'Minor · X Machina', body: 'Execution inflige un 20% más de daño a enemigos por debajo de la mitad de salud. Es alternativa a Rapid Reload y refuerza el remate, no todos los disparos sobre un objetivo sano. Comprueba la salud del rival al soltar la descarga y si alcanzaste el tiro; el perk no corrige un fallo de aim ni impide que llegue una defensa.' },
    { title: 'Major · Refuel', body: 'Joyride restaura 50 de salud al activarse y regenera 20 por segundo mientras permanece activa. Puede ayudarte a recuperar salud durante una rotación, pero no aumenta la vida máxima ni garantiza sobrevivir al focus. Mira cuándo necesitas desmontar: no sigas conduciendo delante del enemigo únicamente para esperar más regeneración.' },
    { title: 'Major · Faces of Death', body: 'Obtienes las pasivas de los otros subroles de DPS: Recon, Specialist y Sharpshooter. Es alternativa a Refuel. La elección añade pasivas, no las habilidades de esos héroes ni un botón de activación. Si lo eliges, sigue revisando tu entrada y tu retirada: añadir pasivas no convierte cualquier flanco en una pelea favorable.' },
  ],
  balanceReview: [
    { title: '25 de junio: el nerf inicial de Execution', body: 'El tamaño del proyectil pasó de 0,17 a 0,07 y se añadió una recuperación de 0,4 segundos después del disparo. Ese ajuste redujo el margen para acertar y continuar el ataque. Nuestra valoración del cambio fue que endurecía demasiado los remates y la fluidez de una heroína recién llegada; preferíamos que Blizzard reconsiderara parte de ese ajuste. Con los cambios posteriores, no basta con aquel nerf para juzgar cómo está ahora.' },
    { title: '14 de julio: menos recuperación y menos daño al conducir', body: 'La recuperación de Execution se redujo de 0,4 a 0,3 segundos. Blizzard sí recortó parte de la pausa inicial, aunque eso no demuestra por sí solo cómo rinde Shion en todos los rangos. Joyride también pasó de 60 a 30 de daño de impacto mientras conduces: no es una reducción que debas trasladar automáticamente al lanzamiento de la moto.' },
    { title: '11 de agosto: apuntar el lanzamiento de Joyride', body: 'El radio de detección del lanzamiento por el suelo pasó de 1,5 a 1 metro. Conviene distinguirlo del daño al conducir y preparar mejor la línea de la moto. Una grabación del estreno puede mostrar un impacto que ahora exige más precisión. No se trata de que Shion haya perdido toda su movilidad ni de que siempre debas lanzar desde el aire.' },
    { title: 'Cómo comparar tu replay con una guía antigua', body: 'Comprueba el parche y el modo antes de copiar un combo. La pausa tras Execution, el impacto al conducir y la detección del lanzamiento cambiaron en fechas distintas. Si un intento falla, separa aim, daño, posición y ayuda rival. Un lanzamiento mal apuntado y una llegada sin cobertura requieren correcciones diferentes; no los atribuyas siempre al nerf de junio.' },
  ],
  mistakes: [
    'Lanzar la moto sin mirar dónde desmontas. En la VOD, sigue a Shion después de que el vehículo salga: quizá el daño acertó, pero tu posición quedó a tiro de otro enemigo.',
    'Tratar Evade como una inmunidad. Mira qué amenaza evitó el dash y cuál te alcanzó al terminar. Un bonus breve de salud no permite quedarse intercambiando sin cobertura.',
    'Cargar Execution mientras persigues fuera del alcance del equipo. Comprueba cuándo perdiste la línea y si el objetivo ya había recibido ayuda antes de soltar el disparo.',
    'Repetir el mismo acceso después de que el rival lo vea. Si alguien dejó de mirar a main para vigilarte, busca cómo coordinar la presión aliada o cambia la ruta antes de volver a cruzar.',
    'Confundir distraer con ganar la pelea. Dos enemigos que te siguen pueden dejar espacio, pero ese espacio solo ayuda si el equipo lo puede ocupar o disputar. Revisa qué ocurrió con ellos, no solo cuántos miraron hacia ti.',
    'Gastar la ultimate para arreglar una pelea perdida. Comprueba quién seguía vivo y podía añadir daño cuando la activaste. Una baja tardía puede no compensar perder la herramienta para el siguiente engage.',
  ],
  counters: [
    { title: 'Ana', body: 'Sleep castiga una llegada que puede ver y apuntar. Mira su posición y si otra amenaza le obliga a atender al equipo antes de cruzar. Haber visto un Sleep lejos no permite asumir que seguirá sin él cuando completes toda la ruta. Si falla el tiro y recibe peel, decide si todavía tienes una salida; no conviertas esa oportunidad en una persecución obligatoria.' },
    { title: 'Brigitte', body: 'Puede ayudar al Support al que intentas llegar y desplazarte con Whip Shot. Observa dónde termina el dash y si el aliado sigue al alcance de su ayuda. No hace falta ganarle el duelo para presionar desde otro ángulo. Tampoco confundas el Shield Bash normal con todos los efectos de Rally al valorar cómo puede frenarte.' },
    { title: 'D.Va', body: 'Matrix puede cubrir el daño de las pistolas hacia un compañero y D.Va puede reposicionarse para disputar el lateral. Mira quién queda libre cuando se gira, sin seguirla a una altura que te aleja del equipo. Puedes esperar a que termine la cobertura o cambiar la línea de tiro; no bases el plan en que la moto y todos tus ataques compartan exactamente la misma interacción con Matrix.' },
    { title: 'Cassidy', body: 'Una entrada visible a corta distancia le permite preparar Flashbang. Mira la esquina desde la que asoma y conserva un recorrido de salida si el rival tiene control disponible. No basta con moverte rápido si desmontas frente a él. Presiona cuando otra amenaza también le exija atención, sin depender de que falle toda su respuesta.' },
    { title: 'Junkrat', body: 'Sus granadas y la trampa pueden castigar una ruta estrecha o un pack al que vuelves por costumbre. Comprueba el suelo y los accesos antes de comprometer la vuelta. La movilidad no limpia una amenaza que sigue en la zona de llegada. Si ese lateral está cubierto, puedes elegir otro o ayudar a main mientras el equipo disputa el espacio.' },
    { title: 'Sombra: importa el kit de la partida', body: 'Frente al kit de DPS con Hack, presta atención a una llegada que permita interrumpir tus opciones y al daño que puede seguirla. El cambio de Sombra a Support está anunciado para Season 5: no traslades automáticamente estos consejos al rework ni a una prueba con otras reglas. Identifica primero qué kit estás jugando y qué respuesta tiene disponible.' },
  ],
  counterplay: [
    'Si el rival protege bien la backline, puedes presionar al enemigo que tu equipo sí alcanza. Obligar a un Support a atender daño puede abrir otra oportunidad; no tienes que llegar hasta él en cada intento.',
    'Si te controlan al desmontar, cambia la cobertura de llegada y observa qué acceso están mirando. Esperar una respuesta usada contra tu Tank puede ofrecer un timing mejor, pero comprueba que la pelea sigue en marcha cuando llegas.',
    'Si no hay un recorrido desde el que aportar daño y volver, considera un DPS que conozcas y que dispute la posición necesaria. Cambia para resolver el alcance o la ruta que falta, no solo porque apareció un nombre en una lista de counters.',
  ],
  compositions: [
    { title: 'Dive con Winston o D.Va', body: 'Busca el mismo objetivo o una amenaza próxima a la entrada del Tank. Puedes preparar el lateral antes del salto, pero observa cuándo llega el otro DPS y desde dónde alcanzan las curas. Una burbuja o Matrix puede ayudar al contacto; no protege cualquier persecución posterior. Si el Tank vuelve para recibir ayuda, comprueba si tú también necesitas salir.' },
    { title: 'Brawl con Junker Queen o Ramattra', body: 'Añade un ángulo cercano al frente que el Tank puede disputar. Si cruzas toda la defensa para buscar una baja muy atrás, quizás el daño de la comp ya no te siga. Ayuda a terminar al objetivo que sale de la pelea corta y vuelve a cobertura cuando el grupo tenga que recuperar salud. La speed no sustituye un destino donde podáis pelear juntos.' },
    { title: 'Dos DPS móviles sin abandonar a los Supports', body: 'Con Tracer, Genji o Echo, acordad a quién presionar y cuándo empezar. Si ambos vais muy lejos, el rival puede atacar al Support que quedó detrás antes de que cerréis una baja. Mira el dive enemigo y la situación de las curas; a veces conviene volver o mantener un lateral más corto. No hace falta que todos los duelos ocurran en la backline rival.' },
  ],
  video: {
    id: '9abTdz8uD3g',
    title: 'No juegues SHION sin saber esto antes | Guía Shion Overwatch',
    description: 'Al comparar el gameplay del vídeo con tu partida, ten presentes los ajustes de Execution y Joyride recogidos arriba; los números y los combos del estreno no describen necesariamente el balance actual.',
    channel: 'Ivajpro',
  },
  vodReview: [
    'Sigue un lanzamiento de Joyride desde antes de activar la moto hasta después de desmontar. Anota a quién acertó, dónde acabó Shion y qué enemigo tenía tiro sobre esa llegada.',
    'En un Execution fallado, pausa al soltar la descarga. Comprueba aim, línea de visión, movimiento y salud del objetivo. Después mira si recibió una defensa o una cura; separa esas causas del perk que habías elegido.',
    'Revisa un Evade hacia delante. Mira el espacio ganado y las opciones que quedaban después. Si sobreviviste por ayuda de un compañero, inclúyela en la lectura en vez de atribuirlo todo al overhealth.',
    'Compara tu entrada con las cámaras del Tank y del otro DPS. Si la distracción dejó espacio, comprueba si pudieron usarlo. Si todavía estaban volviendo, prueba en la siguiente partida a esperar el contacto aliado.',
    'En Satsuriku Spree, sigue los tres avances y la posición final. No mires solo la primera baja: anota qué seguimiento había y si el equipo pudo conservar el objetivo después.',
  ],
  checklist: [
    '¿Quién de mi equipo puede pelear cuando yo llegue?',
    '¿Dónde desmontaré y por dónde volveré?',
    '¿El objetivo de Execution sigue a tiro?',
    '¿Qué amenaza me espera al terminar Evade?',
    '¿El pack de la vuelta está disponible y accesible?',
    '¿Tengo un recorrido útil para los tres avances de la ultimate?',
  ],
  faqs: [
    { question: '¿Shion es una DPS Flanker y cuándo salió?', answer: "Sí. Es una heroína de daño de subrol Flanker, disponible desde el 16 de junio de 2026 con Season 3: Into the Tiger's Den. Su kit combina las pistolas con movilidad y una descarga concentrable; el rol no significa que debas alejarte del equipo en cada pelea." },
    { question: '¿Evade hace invulnerable a Shion?', answer: 'No. Hace un dash y concede overhealth breve. Puedes cambiar la línea de tiro o llegar a cobertura, pero aún tienes que mirar qué amenaza sigue alcanzándote. Tampoco se describe como una limpieza general de efectos. Rapid Reload añade munición, no una cura completa.' },
    { question: '¿Hay que usar Execution solo para rematar?', answer: 'No es una regla obligatoria. Puede añadir presión si tienes un disparo claro, aunque X Machina favorece a objetivos por debajo de media vida. Mira la línea, el movimiento rival y el seguimiento. Gastarla para perseguir fuera de ayuda es un problema distinto de dispararla contra un enemigo que todavía está sano.' },
    { question: '¿El nerf de junio sigue describiendo toda Execution?', answer: 'No. El 25 de junio se redujo el tamaño del proyectil y se añadió una recuperación de 0,4 segundos; el 14 de julio esa recuperación bajó a 0,3. No confundas recuperación con cooldown ni presentes la cifra de junio como si no hubiera habido otro ajuste.' },
    { question: '¿Qué cambió en Joyride después del lanzamiento?', answer: 'El 14 de julio bajó de 60 a 30 el daño de impacto mientras conduces. El 11 de agosto se redujo de 1,5 a 1 metro la detección del lanzamiento por el suelo. Son cambios distintos: no apliques la cifra del impacto al lanzamiento ni supongas que una trayectoria antigua acierta con el mismo margen.' },
    { question: '¿Faces of Death es un buff temporal?', answer: 'La elección concede las pasivas de Recon, Specialist y Sharpshooter, no un botón para activar un buff de unos segundos ni las habilidades de otros DPS. Es una opción Major alternativa a Refuel. Elige según lo que necesitas sostener, sin tratar esas pasivas como una victoria automática en el duelo.' },
    { question: '¿Shion se juega igual que Tracer?', answer: 'Comparten la idea de presionar desde un lateral, pero sus herramientas son distintas. Con Shion decides dónde desmontar, hacia dónde lanzar la moto y cómo apuntar Execution. No copies el plan de Recall ni el número de salidas de Tracer: mira las opciones que le quedan a Shion al terminar cada acción.' },
    { question: '¿Qué hago si no consigo entrar a por los Supports?', answer: 'Puedes añadir daño al objetivo que ya disputa tu equipo, preparar otro lateral o esperar a que una defensa se use. Revisa qué te bloquea antes de cambiar: ruta cubierta, falta de seguimiento o un alcance que no puedes disputar. Una comp con peel no te obliga a repetir un duelo perdido en su backline.' },
  ],
  conclusion: 'Para la siguiente partida, cambia una sola cosa: decide la cobertura de llegada antes de Joyride. Después, en el replay, mira si desmontaste donde querías y si tu equipo podía intervenir. Así puedes distinguir una ruta mal preparada de un remate fallado sin echar la culpa a toda la comp o al mismo parche en cada muerte.',
  links: [
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Revisar qué te queda al terminar la entrada' },
    { href: '/counters/shion', label: 'Matchups y respuestas frente a Shion' },
    { href: '/team-comps/shion', label: 'Coordinar el equipo alrededor de Shion' },
    { href: '/maps/neon-junction', label: 'Captura y escolta en Neon Junction' },
    { href: '/maps/esperanca', label: 'Rotaciones y peleas alrededor del robot en Esperança' },
    { href: '/heroes/tracer', label: 'Las diferencias entre Blink, Recall y un flanco preparado' },
    { href: '/heroes/genji', label: 'Preparar el timing de Genji' },
    { href: '/heroes/ana', label: 'La posición de Ana y sus defensas' },
    { href: '/heroes/dva', label: 'Movilidad y protección con D.Va' },
    { href: '/heroes/cassidy', label: 'Ángulos y Flashbang con Cassidy' },
    { href: '/roles/dps', label: 'Decisiones del rol de DPS' },
    { href: '/guides/como-usar-ultimates-overwatch', label: 'Preparar el seguimiento de una ultimate' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Revisar una entrada completa en tu VOD' },
    { href: '/overwatch-temporada-3-into-the-tigers-den', label: 'Los anuncios de Season 3 y el estreno de Shion' },
    { href: '/experts', label: 'Pedir una revisión de tus flancos y tus remates' },
    { href: '/news', label: 'Noticias de Overwatch' },
  ],
}
