import type { HeroPillar } from './hero-pillars'

export const reviewedZaryaHero: HeroPillar = {
  slug: 'zarya', name: 'Zarya', role: 'Tank', roleSlug: 'tank',
  publishedAt: '2026-06-26', schemaDate: '2026-10-04', updatedAt: '4 de octubre de 2026',
  seoTitle: 'Zarya en Overwatch: burbujas, energía y Graviton',
  seoDescription: 'Decide cuándo usar cada burbuja con Zarya, avanza sin perder a tus Supports y prepara el seguimiento de Graviton. Perks y ejemplos de Oasis y Eichenwalde.',
  h1: 'Zarya en Overwatch: aprovechar las burbujas sin quedarte vendida',
  kicker: 'Proteger un cruce, mantener el rango y preparar Grav',
  intro: [
    'Si cargas mucha energía y mueres al salir de la esquina, mira qué te quedaba cuando terminó la burbuja. Puede que ya hubieras perdido salud, que tus Supports no tuvieran visión o que el objetivo pudiera retirarse sin recibir más daño. La energía aumenta el daño del cañón; no sustituye una posición desde la que puedas seguir disparando.',
    'Con Zarya, prepara el siguiente paso antes de protegerlo: dónde termina el cruce, quién te puede seguir y a quién hará falta ayudar después. Aquí tienes decisiones para las burbujas propias y aliadas, el beam y las granadas, los perks y Graviton Surge, con ejemplos de Oasis y Eichenwalde que puedes comprobar en tu replay.',
  ],
  headerTips: [
    'Elige una cobertura de llegada antes de gastar la burbuja para cruzar.',
    'Mira la salud y la posición de tu equipo, además del medidor de energía.',
    'Antes de Grav, comprueba quién tiene munición y tiro para continuar.',
  ],
  quickAnswers: [
    { title: 'Si tienes energía pero no puedes avanzar', body: 'Busca qué te está frenando. Quizá el enemigo está en una altura, tus curas no llegan a la siguiente esquina o el otro DPS sigue detrás. No gastes otra burbuja solo para perseguir la misma línea. Puedes presionar desde cobertura, cambiar el recorrido o esperar a que un aliado dispute ese ángulo.' },
    { title: 'Si el rival deja de disparar a la burbuja', body: 'No tienes que conseguir energía en cada uso. Si te permitió cruzar o dio tiempo a un compañero para ponerse a salvo, ya cumplió una función. El problema aparece cuando la activas en una posición que ya era segura y luego te expones sin protección. Revisa el cruce y el daño evitado, no solo el medidor.' },
    { title: 'Si Grav atrapa enemigos pero no cae nadie', body: 'Mira el seguimiento antes de buscar un combo distinto. ¿Tus DPS estaban recargando, los Supports atendían a alguien fuera de posición o una defensa rival permitió aguantar el daño? También puede bastar atrapar a un objetivo accesible. No necesitas juntar al equipo entero si luego nadie puede dispararle.' },
  ],
  facts: [
    { title: 'Rango del beam', body: 'Necesitas estar cerca para mantener el daño principal. Usa las granadas para presionar desde más lejos, pero no trates una calle abierta como si fuera un duelo a corta distancia.' },
    { title: 'Cobertura de llegada', body: 'La esquina a la que llegas importa tanto como la burbuja al salir. Si el cruce termina en terreno abierto, la protección puede acabarse antes de que tengas una retirada.' },
    { title: 'Energía y supervivencia', body: 'Son cosas distintas. Un cañón cargado no te devuelve la salud ni permite que tus Supports curen a través de una pared.' },
    { title: 'Burbuja aliada', body: 'Protege a quien recibe la amenaza ahora. No hace falta elegir siempre al mismo DPS ni reservarla para una entrada que todavía no va a ocurrir.' },
  ],
  rankedPlan: [
    'Reconoce desde la esquina qué enemigos tienen tiro al cruce y dónde están tus Supports. Si el rival controla una altura, decide quién va a disputarla; caminar debajo no obliga a sus ocupantes a bajar.',
    'Cuando necesites pasar, utiliza la protección para llegar a otra cobertura, no para quedarte disparando en medio. Puedes bloquear daño o evitar que te lo tiren: ambas cosas ayudan si el equipo alcanza una posición mejor.',
    'Después del cruce, comprueba el estado de tus barreras y la siguiente amenaza. Un Genji aliado que acaba de recibir focus puede necesitar la proyectada antes que tú otra burbuja para perseguir. No decidas mirando solo tu salud.',
    'Presiona al enemigo que tengas a rango y al alcance del equipo. Si se retira tras una esquina que corta tus curas, no tienes que seguirlo. Mantener el espacio ganado puede permitir que el objetivo avance o que tus compañeros cambien de ángulo.',
    'Antes de la siguiente entrada, recupera munición y confirma que el grupo está preparado. Haber sobrevivido con poca salud y sin protección no significa que debas continuar porque conservas energía.',
  ],
  sections: [
    { title: 'Una burbuja sin energía también puede ser útil', body: 'Imagina que tu Support cruza una puerta bajo una línea de tiro. Si lo proteges y el enemigo espera, el aliado puede alcanzar cobertura sin daño. No necesitas provocar disparos para justificar ese uso. En cambio, poner la misma burbuja cuando ya está tapado puede dejarte sin respuesta cuando vuelva a asomarse. Mira qué cambió durante la protección: la posición, la salud o el tiempo disponible para actuar.' },
    { title: 'No lleves la pelea más lejos que tus curas', body: 'Cuando un enemigo tocado retrocede, comprueba desde dónde te cura Ana o Baptiste. Si doblas otra esquina, puedes perder esa ayuda aunque el DPS rival siga dentro del beam. La burbuja da un margen breve, no un permiso para salir del alcance de todos. Si tus compañeros no pueden seguir, mantén la nueva esquina y deja que se acerquen antes de continuar.' },
    { title: 'La proyectada se decide mirando al aliado', body: 'Para ayudar a Reaper o Genji, mira cuándo reciben daño y dónde quieren acabar. Si el rival ya se ha girado, protegerlos puede permitir que terminen el duelo o vuelvan; si aún están preparando la entrada, la burbuja puede gastarse antes de que la necesiten. También sirve para un Support al que acaba de llegar el dive. No hay un receptor fijo: compara la amenaza actual con la protección que tú necesitas conservar.' },
    { title: 'Oasis: entra por la puerta que tu equipo puede seguir', body: 'En University, el acceso al espacio del punto puede obligarte a pelear muy cerca. Mira la otra puerta antes de avanzar: un enemigo que aparece por allí puede tener tiro sobre tus Supports mientras tú sigues al Tank. Cruza hasta una cobertura desde la que mantengáis contacto, y usa la proyectada si el compañero que sigue recibe focus. Si te separan por las entradas, vuelve a reunir al grupo en lugar de intentar ganar dos duelos con energía alta.' },
    { title: 'Eichenwalde: no termines el cruce del puente aislada', body: 'Durante el tramo del puente, el rival puede presionar desde arriba mientras el payload sigue una ruta más expuesta. Decide antes dónde podrás taparte y si tus Supports tienen visión de ese lugar. Al llegar al castillo, no sigas a un defensor por el interior mientras el resto continúa fuera. Una burbuja que te permite entrar no garantiza que el equipo pueda recorrer la misma distancia; compruébalo antes de convertir ese cruce en una persecución.' },
    { title: 'Graviton se prepara con los compañeros que están presentes', body: 'Antes de lanzar, mira a quién puedes atrapar y quién tiene tiro sobre ese lugar. Cassidy detrás de una pared no añade daño por tener la ultimate; Genji que todavía vuelve del spawn tampoco llega a tiempo por haber anunciado el combo. Puedes usar Grav para cerrar una baja importante con daño normal si la pelea lo permite. Cuando varios enemigos quedan juntos, sigue también sus defensas y tu munición: el control no elimina su capacidad de recibir ayuda.' },
  ],
  abilities: [
    { title: 'Particle Cannon', body: 'El disparo principal es un beam corto y el secundario lanza granadas de energía. Usa el primero cuando puedes mantener al objetivo a rango y las granadas cuando necesitas presionar una entrada desde más lejos. Frente a D.Va, Matrix puede negar tus granadas, pero no el beam. Eso te permite presionarla de cerca; no significa que debas perseguirla fuera de cobertura. Recarga al taparte cuando puedas, antes del intercambio que quieres sostener.' },
    { title: 'Particle Barrier', body: 'La barrera propia protege durante un intervalo limitado y el daño que bloquea puede cargar Energy. Piensa qué vas a hacer al terminar: alcanzar una esquina, acabar un duelo con ayuda o retirarte. No puedes bajarla manualmente como el escudo de Reinhardt. Si el rival espera o la rompe, necesitas seguir teniendo una posición desde la que sobrevivir.' },
    { title: 'Projected Barrier', body: 'Aplica una barrera a un aliado. Mira su posición y la amenaza que recibe antes de usarla: proteger la llegada de Genji y salvar a Ana del dive son decisiones distintas. En el kit normal no te lleva volando hacia ese compañero ni cubre a varios aliados a la vez. Tampoco sustituye la curación que necesitará después de la protección.' },
    { title: 'Energy', body: 'El daño bloqueado por las barreras aumenta el daño del Particle Cannon. Para valorar cómo la conseguiste, mira lo que gastaste y dónde acabaste: tener el medidor alto mientras el equipo está junto a ti permite presionar; cargarlo lejos de cobertura puede dejarte sin tiempo para aprovecharlo. El perk Extra Oomph añade otra forma de generar energía, pero no elimina la necesidad de defender el siguiente intercambio.' },
    { title: 'Graviton Surge', body: 'Lanza un pozo gravitatorio que atrae enemigos. Elige una posición a la que tus compañeros puedan añadir daño y piensa qué defensa puede mantener vivos a los atrapados. No es lo mismo responder al lanzamiento que proteger al equipo durante el seguimiento. Si una Matrix rival cubre los disparos de tus DPS, por ejemplo, tendrás que mirar quién puede mantener daño o cambiar de ángulo; no des la baja por hecha al acertar Grav.' },
    { title: 'Bruiser', body: 'Su subrol aporta resistencia a impactos críticos y velocidad cuando está por debajo de la mitad de salud. Ese bonus no cura ni garantiza que aguantes el focus. Si aparece al retirarte, úsalo para llegar a cobertura y recuperar ayuda; no esperes a quedarte herida para intentar un cruce que podías haber preparado con el equipo.' },
  ],
  perksIntro: 'En las partidas con perks eliges una opción Minor y una Major al desbloquear sus niveles. Estas son las alternativas del kit normal; no son los poderes de Stadium. La proyectada que te desplaza hacia el aliado, las barreras múltiples o la curación periódica de esos poderes no forman parte de estas cuatro elecciones.',
  perks: [
    { title: 'Minor · Jump-Ups', body: 'Aumenta el impulso que te produce tu propio disparo secundario. Puede ayudarte a preparar un acceso, pero no equivale a los Boosters de D.Va. Comprueba en el mapa la subida y la cobertura de llegada; no estrenes una ruta durante el focus rival suponiendo que siempre te dejará en la altura deseada.' },
    { title: 'Minor · Spotter', body: 'La proyectada activa la regeneración de salud del aliado y aumenta su velocidad. Es alternativa a Jump-Ups. Puede ayudar a completar un cruce o una retirada, pero el compañero aún necesita una llegada segura. No lo confundas con una cura instantánea que resuelva cualquier daño recibido durante el engage.' },
    { title: 'Major · Extra Oomph', body: 'Mientras hay una barrera activa, hacer daño con el beam genera energía. Puedes aprovechar una protección que ya necesitabas para mantener presión sobre un objetivo a rango. No hace falta esperar que el enemigo dispare a la burbuja, pero sí tener tiro con el beam. Si activas una barrera sin ningún enemigo a su alcance, este perk no te dará energía por disparar al aire.' },
    { title: 'Major · Energy Lance', body: 'El beam atraviesa enemigos y es alternativa a Extra Oomph. No exige alcanzar 50 de energía y no significa que atraviese todas las barreras. Puede aprovechar rivales alineados dentro de su alcance; no te obliga a colocarte en campo abierto buscando una fila ni convierte las granadas en disparos penetrantes.' },
  ],
  mistakes: [
    'Valorar una burbuja solo por la energía obtenida. Sigue al receptor: quizá llegó sano a cobertura o pudo completar una entrada aunque el enemigo dejara de disparar. Separa ese uso de activar una barrera sin ninguna amenaza ni movimiento previsto.',
    'Perseguir porque el medidor está alto. Pausa cuando termina la protección y comprueba salud, cobertura y visión de tus Supports. La baja posible no muestra cuánto daño puedes recibir antes de alcanzarla.',
    'Usar la proyectada siempre sobre el DPS del combo. Mira si ya está entrando o si un Support necesita salvarse del dive ahora. La siguiente pelea también depende de que ese Support siga vivo.',
    'Cruzar debajo de una altura sin preparar quién la disputa. Comprueba desde dónde recibe daño cada compañero y si tus granadas realmente desplazan al ocupante. Si no, cambia el acceso o coordina otra amenaza.',
    'Lanzar Grav mientras el equipo está recargando o volviendo. Revisa las cámaras de los DPS al soltarla, no solo el resultado desde la tuya. Acertar el lanzamiento y preparar mal el seguimiento son errores diferentes.',
    'Juzgar todas las defensas igual frente al cañón. Identifica qué disparo estabas usando y cuándo llegó la respuesta. No extrapoles una interacción del beam a las granadas, a Grav o a un poder de otro modo.',
  ],
  counters: [
    { title: 'D.Va', body: 'Puede disputar una altura y cambiar de posición antes de que puedas sostener el beam. En el suelo y a corto alcance puedes presionarla, pero eso no convierte el duelo en una victoria automática: quizá esté protegiendo a un compañero mientras otro ángulo te dispara. Mira qué espacio deja al irse y no gastes tus barreras siguiendo una subida que no puedes completar.' },
    { title: 'Widowmaker', body: 'Una línea larga amenaza a tus compañeros antes de que tú llegues a rango. Usa cobertura para organizar el cruce y mira quién puede disputar su posición. Proteger un aliado puede darle tiempo para pasar, pero no elimina al sniper ni hace seguro el siguiente acceso. No consumas toda la protección intentando responderle con beam desde lejos.' },
    { title: 'Pharah y Echo', body: 'Pueden atacar desde posiciones verticales donde te cuesta mantener el disparo principal. Ayuda a cruzar a quien sí tiene tiro y presta atención al enemigo que os presiona desde el suelo. Si el equipo no consigue disputar el aire, valora un cambio que conozcas y que resuelva ese alcance; no basta con subir la energía y mirar arriba.' },
    { title: 'Mei', body: 'Ice Wall puede separar tu posición de las curas y del seguimiento. Antes de entrar por una puerta estrecha, mira por dónde se reuniría el equipo si aparece la pared. La burbuja puede proteger un momento, pero no permite a tus compañeros disparar o curar a través de esa separación. No conviertas cada muro en una persecución por otra habitación.' },
    { title: 'Baptiste y Zenyatta', body: 'Sus recursos defensivos pueden dar tiempo a los enemigos atrapados en Grav. Si aparece Immortality Field, mira quién puede destruirlo; si Zenyatta responde con Transcendence, comprueba qué puede conseguir el equipo durante esa defensa antes de gastar otra ultimate. No son el mismo recurso ni garantizan que cualquier objetivo quede a salvo: importa el daño y la ayuda presentes.' },
  ],
  counterplay: [
    'Contra poke, cambia la ruta si cada cruce te deja herida antes de tener tiro. Coordina cuándo pasa el equipo y qué aliado necesita la proyectada; no necesitas recibir todo el daño para poder avanzar.',
    'Si el rival espera las burbujas, conserva la cobertura y prepara la amenaza aliada que coincide con ellas. Haber protegido un paso puede ser suficiente. No te expongas más solo para obligar al enemigo a cargarte.',
    'Si el problema es una altura o un objetivo al que nadie alcanza, prueba un acceso distinto y una entrada coordinada. Cuando eso tampoco permite disputar la posición, considera otro Tank que sepas jugar allí. Cambia por la necesidad del mapa, no porque una lista llame counter a un enemigo.',
  ],
  compositions: [
    { title: 'Brawl 5v5 junto a Reaper o Mei', body: 'Zarya ocupa el puesto de Tank. La cercanía permite seguir el daño de Reaper o proteger a quien recibe focus al entrar; Mei puede ayudar a limitar una salida. Los Supports tienen que alcanzar esa pelea y conservar visión. Si el grupo se divide entre una calle y un interior, no basta con añadir speed para que todos coincidan.' },
    { title: 'Ayudar a Genji sin abandonar a los Supports', body: 'Prepara con él cuándo usará Dash y dónde terminará. La proyectada puede proteger la presión o la retirada, pero no obliga a gastar también tu barrera y seguirlo hasta la última habitación. Mantén una posición desde la que el otro DPS y los Supports puedan participar. Si reciben dive detrás, decide primero qué amenaza necesita respuesta.' },
    { title: 'Un segundo Tank pertenece a otro formato', body: 'Reinhardt o Winston aliados no forman una composición estándar de cola por roles 5v5 junto a Zarya. En un formato que permita dos Tanks, puedes estudiar cómo proteger su entrada y repartir quién ocupa el frente, pero revisa las reglas y el balance de ese modo. No copies automáticamente el plan, las cargas o los cooldowns de 6v6 a una partida 5v5.' },
  ],
  vodReview: [
    'Elige una burbuja propia y sigue desde la activación hasta la llegada. Anota qué daño evitaste, si el rival esperó y si acabaste junto al equipo. Una barra de energía que no sube no basta para llamar malo al uso.',
    'Revisa una proyectada desde la cámara del aliado. Mira qué amenaza recibía y qué pudo hacer durante la protección. Después comprueba qué te quedaba a ti para el siguiente intercambio.',
    'En una muerte con mucha energía, retrocede a la última esquina segura. Comprueba cuándo perdiste visión de las curas y si el enemigo al que seguías todavía estaba al alcance de tus DPS.',
    'Sigue una Grav desde las cámaras de quienes podían añadir daño. Anota munición, visión, distancia y defensa rival. Así separas un lanzamiento fallado de uno acertado sin seguimiento.',
    'Compara un cruce por main con la ruta alternativa disponible. No busques una ruta perfecta: comprueba si el grupo podía recorrerla junto y si evitaba el ángulo que gastó vuestra protección.',
  ],
  checklist: [
    '¿Dónde me tapo cuando termine la burbuja?',
    '¿Mis Supports tienen visión de la siguiente posición?',
    '¿Qué aliado recibe la amenaza que merece la proyectada ahora?',
    '¿Puedo mantener el beam sin perseguir fuera de ayuda?',
    '¿Quién tiene munición y tiro sobre mi objetivo de Grav?',
    '¿Estoy aplicando las reglas del modo que estamos jugando?',
  ],
  faqs: [
    { question: '¿Una burbuja sin energía es una burbuja mal usada?', answer: 'No. Puede permitir cruzar o retirarse sin que el rival dispare. Mira qué consiguió el receptor durante ese tiempo. El uso es dudoso si ya estaba seguro, no necesitaba moverse y la protección faltó después; no solo porque el medidor no subiera.' },
    { question: '¿Puedo cancelar la burbuja como el escudo de Reinhardt?', answer: 'No puedes bajarla manualmente para conservarla como haces con ese escudo. Prepara el lugar donde terminarás y qué respuesta tendrás cuando expire o la rompan. Llegar a cobertura ayuda a sobrevivir después, pero no convierte el tiempo restante en una barrera guardada.' },
    { question: '¿Conviene burbujear siempre al Genji del equipo?', answer: 'No. Mira si ya recibe focus y qué intenta hacer; puede necesitar protección al entrar o al volver. Si todavía está preparando el flanco y un Support recibe dive, ese Support puede ser la prioridad. La decisión depende de la amenaza actual, no del héroe al que asignaste la burbuja al inicio.' },
    { question: '¿Cuándo merece la pena lanzar Graviton sobre un solo enemigo?', answer: 'Cuando ese objetivo es importante para la pelea y el equipo puede rematarlo antes de que reciba ayuda suficiente. Comprueba quién tiene tiro y recursos, y qué conseguiréis después de la baja. Atrapar a varios fuera del alcance de todos no es necesariamente mejor que cerrar un duelo útil.' },
    { question: '¿Energy Lance necesita 50 de energía?', answer: 'No en el perk actual. Hace que el beam atraviese enemigos y compite con Extra Oomph como elección Major. No implica que atraviese todas las barreras ni que se aplique a las granadas. Para aprovecharlo necesitas enemigos alineados dentro del rango del beam.' },
    { question: '¿Zarya con Reinhardt es una composición de cola por roles 5v5?', answer: 'No: ambos son Tanks y ese formato tiene un único puesto para el rol. La pareja puede estudiarse en un modo que permita varios Tanks, con sus propias reglas. Para 5v5, decide qué DPS y Supports pueden seguir a Zarya sin plantear un segundo Tank como requisito.' },
  ],
  conclusion: 'En la siguiente VOD, elige un cruce y una Grav. Sigue dónde acabaste cuando terminó la burbuja y quién podía disparar al objetivo de la ultimate. Esas dos secuencias dicen más que la energía máxima de la partida: te muestran qué protección ayudó al equipo y dónde faltó preparar el paso siguiente.',
  links: [
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Revisar el uso de las barreras entre intercambios' },
    { href: '/counters/zarya', label: 'Matchups y respuestas frente a Zarya' },
    { href: '/team-comps/zarya', label: 'Organizar un equipo alrededor de Zarya' },
    { href: '/maps/oasis', label: 'Las entradas y las alturas de Oasis' },
    { href: '/maps/eichenwalde', label: 'El puente y el castillo de Eichenwalde' },
    { href: '/heroes/genji', label: 'Preparar la entrada y la retirada de Genji' },
    { href: '/heroes/ana', label: 'La posición de Ana y sus líneas de cura' },
    { href: '/heroes/dva', label: 'La movilidad y las alturas con D.Va' },
    { href: '/roles/tank', label: 'Decisiones del rol de Tank' },
    { href: '/guides/como-mejorar-como-tank-overwatch', label: 'Avanzar y proteger al equipo como Tank' },
    { href: '/guides/como-usar-ultimates-overwatch', label: 'Preparar el seguimiento de las ultimates' },
    { href: '/guides/cuando-cambiar-de-heroe-overwatch', label: 'Cuándo un cambio puede resolver el alcance' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Revisar decisiones concretas en una VOD' },
    { href: '/experts', label: 'Pedir una revisión de tus cruces y tus Graviton' },
  ],
}
