import type { HeroPillar } from './hero-pillars'

export const reviewedTracerHero: HeroPillar = {
  slug: 'tracer', name: 'Tracer', role: 'DPS', roleSlug: 'dps',
  publishedAt: '2026-06-26', schemaDate: '2026-10-04', updatedAt: '4 de octubre de 2026',
  seoTitle: 'Tracer en Overwatch: flancos, Recall y Pulse Bomb',
  seoDescription: 'Aprende a llegar con recursos al flanco, elegir el regreso de Recall y preparar Pulse Bomb con Tracer. Perks actuales y ejemplos de Esperança y Gibraltar.',
  h1: 'Tracer en Overwatch: entrar al flanco y volver con vida',
  kicker: 'Llegar a tiempo, elegir el duelo y conservar una salida',
  intro: [
    'Si llegas detrás del rival, disparas un cargador y tienes que usar Recall antes de que empiece la pelea, revisa el recorrido antes de culpar al aim. Quizá tu Tank todavía estaba cruzando la calle, el objetivo tenía dos compañeros al lado o habías gastado los Blinks para acercarte. Tracer necesita llegar en condiciones de pelear, no solo llegar antes que los demás.',
    'Empieza por un lateral cercano con cobertura y una vuelta que conozcas. Desde allí puedes reconocer la posición de los Supports, presionar a quien se separa y aparecer cuando tu equipo pueda aprovecharlo. Esta guía explica qué mirar antes de entrar, cómo decidir entre Blink, Recall y un health pack, y cuándo Pulse Bomb tiene un objetivo que podéis rematar.',
  ],
  headerTips: [
    'Mira qué está haciendo tu equipo antes de empezar el duelo del flanco.',
    'Llega con munición, movilidad disponible y una cobertura a la que volver.',
    'Antes de Recall, recuerda dónde estabas y quién puede esperarte allí.',
  ],
  quickAnswers: [
    { title: 'Si Recall sale nada más entrar', body: 'Usarlo para sobrevivir puede ser la decisión correcta. Revisa lo anterior: de dónde vino el primer daño, cuántos Blinks gastaste y si el equipo ya podía presionar. Si el rival se giró entero porque no tenía otra amenaza, cambia el momento de entrada. No retrases Recall solo para que el replay parezca más agresivo.' },
    { title: 'Si te giran todos y aun así perdéis', body: 'Comprueba si tus compañeros podían actuar durante ese giro. Si estaban reapareciendo o no tenían tiro, quizá solo conseguiste que te expulsaran. Busca una entrada más corta que coincida con su avance. Distraer a varios enemigos sirve cuando permite ganar una posición, una baja o tiempo necesario para el objetivo.' },
    { title: 'Si pegas Pulse Bomb pero el enemigo vive', body: 'Sigue la respuesta en el replay: una defensa puede salvarlo y un compañero puede curarlo o protegerlo. Mira qué habilidad necesitabas forzar antes y si tu equipo podía continuar después de la explosión. Un impacto confirma la puntería del lanzamiento, no que el momento fuera bueno.' },
  ],
  facts: [
    { title: 'Distancia', body: 'Las Pulse Pistols pierden eficacia desde lejos. Si apenas haces daño desde tu esquina, avanza a otra cobertura con el equipo; no gastes toda la movilidad para llegar a un duelo aislado.' },
    { title: 'Blink', body: 'Cuenta las cargas que quedan después de llegar, no solo las que tenías al salir. Una puerta o una esquina pueden ser una retirada sin obligarte a gastar otro Blink.' },
    { title: 'Recall', body: 'Vuelve a una posición y un estado de salud anteriores. Ese lugar también puede haber quedado expuesto. Recuerda el recorrido, no lo trates como un teleport hacia tu equipo.' },
    { title: 'Health packs', body: 'Ayudan a mantener el lateral sin pedir que un Support te siga por cada habitación. Primero comprueba que el pack está disponible y que puedes recogerlo sin regalar el siguiente duelo.' },
  ],
  rankedPlan: [
    'Reconoce una ruta corta antes del intercambio. Localiza una cobertura desde la que puedas mirar al rival y una salida que no dependa de ganar el duelo. Si necesitas cruzar varias habitaciones, confirma que aún llegarás a la pelea del equipo.',
    'Recarga antes de enseñar el ángulo. Llegar con poca munición puede obligarte a detener el daño justo cuando aparece la oportunidad. Usa la cobertura para preparar el cargador en lugar de gastar movilidad solo para recargar delante del enemigo.',
    'Elige a quien puedas presionar ahora. Un Support aislado puede ser un objetivo, pero también un DPS tocado que vuestro Tank ya está disputando. No recorras media backline para buscar a Ana mientras otro enemigo accesible pierde su salida.',
    'Después del primer giro rival, vuelve a mirar el frente. Si tu grupo ya entra, puedes mantener un segundo ángulo; si todavía no llega, quizá debas taparte y conservar recursos. Que alguien te mire no obliga a continuar el duelo.',
    'Al salir, recupera salud y movilidad antes de decidir la siguiente entrada. No hay un retraso fijo que sirva para todas las peleas: comprueba qué respuesta enemiga sigue gastada, qué posición tiene tu equipo y si el objetivo continúa accesible.',
  ],
  sections: [
    { title: 'Una entrada corta puede tener más seguimiento', body: 'Si Ana enemiga se gira desde la esquina donde vuestro Tank ya la presiona, tus tiros pueden obligarla a elegir a quién atiende. Si te has ido hasta la última habitación, quizá el resto no pueda alcanzar a nadie aunque consigas ese giro. Empieza cerca de la pelea y amplía la ruta solo cuando sepas qué vas a encontrar. Un flanco largo no es mejor por quedar más detrás.' },
    { title: 'Recuerda el lugar de regreso de Recall', body: 'Piensa en el recorrido que acabas de hacer. Si pasaste por una puerta vigilada antes de entrar, volver allí puede dejarte dentro de otra línea de tiro. No siempre puedes elegir un regreso perfecto, pero sí evitar quedarte demasiado tiempo lejos de la última cobertura. En una VOD, compara el lugar de activación con el de vuelta y mira quién tenía visión en ambos.' },
    { title: 'No confundas un enemigo que huye con un duelo ganado', body: 'Moira puede usar Fade hacia su equipo y Tracer puede gastar todos sus Blinks siguiéndola. Haber forzado esa salida no exige terminar la persecución: quizá puedas volver a disparar a otro objetivo o dejar que vuestros compañeros ocupen la esquina. Sigue solo si conoces la llegada, tienes recursos y la baja ayuda a la pelea actual. Una barra de salud baja no muestra quién la está esperando detrás.' },
    { title: 'Esperança: sal del interior donde sigue la pelea', body: 'En las calles junto al robot, un interior permite aparecer por otra puerta mientras el grupo presiona fuera. Antes de cruzarlo, mira a qué esquina va vuestro Tank. Si la pelea se mueve, sal por una puerta desde la que aún puedas disparar a sus enemigos, en lugar de seguir a un Support por todo el edificio. Después de ganar, puedes vigilar un acceso de regreso mientras alguien empuja TS-1; no hace falta perseguir hasta la zona de reaparición.' },
    { title: 'Gibraltar: presiona a quien baja del hangar', body: 'Si Winston disputa una plataforma del hangar, Tracer puede colocarse en el suelo para disparar al defensor que baje. No des por hecho que va a hacerlo: mira por qué lado se retira y quién puede ayudarlo. Si el rival sigue arriba y nadie lo desplaza, disparar desde debajo no reemplaza el control de altura. Busca la ruta de subida o atiende un objetivo accesible con el equipo; Blink no te coloca automáticamente en cualquier plataforma.' },
    { title: 'Prepara Pulse Bomb antes de acercarte', body: 'Decide sobre quién quieres lanzarla y qué puede impedir la baja. Kiriko con Suzu o un objetivo que todavía puede escapar obligan a ajustar la entrada. Puedes mostrar presión normal antes y lanzar cuando veas una respuesta gastada, siempre que el enemigo siga a tu alcance. No guardes Pulse esperando una jugada múltiple imposible, pero tampoco uses el primer objetivo grande como garantía de valor.' },
  ],
  abilities: [
    { title: 'Pulse Pistols', body: 'Son armas automáticas de corto alcance. Busca una distancia donde puedas seguir el movimiento del objetivo sin quedarte quieto delante de su respuesta. Si el cargador se acaba mientras conserva mucha ayuda, vuelve a cobertura para recargar o cambia la línea con tus compañeros. Acercarte más no compensa por sí solo que haya dos enemigos listos para contestarte.' },
    { title: 'Blink', body: 'Te desplaza en la dirección de movimiento. Mira la llegada antes de usarlo: un cambio lateral puede mantener el tiro sin ponerte junto al Tank enemigo. También puedes guardarlo para rodear una esquina al salir. Evita encadenar cargas detrás de una baja sin comprobar la ruta; cuando necesites corregir otra amenaza, esas cargas ya no estarán disponibles.' },
    { title: 'Recall', body: 'Regresas a tu posición y salud anteriores. Úsalo si necesitas cortar un intercambio peligroso, aunque no hayas conseguido una baja ni forzado una habilidad. Después, vuelve a comprobar salud, cobertura y cargas de Blink: Recall no restaura por defecto todos los Blinks. Tampoco es una protección automática al recibir daño letal; tienes que activar la habilidad a tiempo.' },
    { title: 'Pulse Bomb', body: 'Lanzas un explosivo que puede adherirse al enemigo. Asegura la aproximación y conserva una forma de salir en vez de gastar todas las cargas solo para intentar pegarlo. Las defensas y la movilidad del rival siguen importando después del lanzamiento. Si el objetivo vive, comprueba qué ocurrió y si el equipo pudo aprovechar la respuesta antes de dar la ultimate por buena o mala.' },
    { title: 'Flanker', body: 'Los health packs te restauran más salud. Esa ayuda puede permitir mantener una ruta lateral, pero no crea packs ni asegura que el elegido esté disponible. Mira quién controla el acceso y dónde volverás a disparar después. Usar los packs no impide recibir curación de tus Supports cuando estás a su alcance; evita exigirles que abandonen cobertura para seguir cada duelo.' },
  ],
  perksIntro: 'Eliges una Minor y una Major. Estas son las opciones del kit normal: no incluyen Auto Recall, el portal para aliados ni otras mejoras de Stadium. Compartir Recall con el equipo o recibir ultimate de los packs fueron reglas de un evento, no efectos normales de estos perks.',
  perks: [
    { title: 'Minor · Temporal Regen', body: 'La regeneración pasiva de salud empieza antes. Puede ayudar entre intercambios si consigues dejar de recibir daño; no es una cura inmediata al girarte ni una razón para seguir expuesto. Aprovecha una cobertura mientras recuperas recursos y mira si hace falta un pack o ayuda aliada antes de entrar de nuevo.' },
    { title: 'Minor · Kinetic Reload', body: 'Conectar un melee recarga parte de la munición. Es alternativa a Temporal Regen y puede alargar un intercambio cercano, pero exige acertar ese golpe. No sustituyas todas las recargas por perseguir un melee: si el enemigo ya sale por la puerta, puedes acabar gastando Blink para conseguir munición en una posición peor.' },
    { title: 'Major · Blink Packs', body: 'Recoger un health pack restaura una carga de Blink. Puede facilitar una ruta que ya utiliza packs, pero no recupera todas las cargas ni convierte el lugar en una salida segura. Mira el estado del pack y la cobertura al recogerlo. Si lo necesitas para sobrevivir, no dejes que otro enemigo te espere entre ese punto y la pelea.' },
    { title: 'Major · Quantum Entanglement', body: 'Recall concede exceso de salud y munición que decaen con el tiempo. Es alternativa a Blink Packs y puede ayudarte a responder después del regreso. Comprueba la posición y el bonus que queda antes de volver a entrar: no son mejoras permanentes y no eliminan el cooldown de Recall. Tener más salud al volver no hace seguro el mismo duelo que acabas de abandonar.' },
  ],
  mistakes: [
    'Empezar el duelo mientras el Tank aún está llegando. Sigue ambas cámaras: quizá el rival pudo expulsarte antes de tener que responder al frente. Ajusta la llegada al intercambio real, no a un número fijo de segundos.',
    'Gastar los Blinks para acercarte sin mirar la puerta de salida. En el replay, cuenta los recursos al primer disparo y comprueba qué cobertura quedaba si el objetivo recibía ayuda.',
    'Continuar después de Recall como si conservaras la misma seguridad. Mira qué salud recuperaste, dónde apareciste y quién podía alcanzar ese lugar. Necesitas volver a evaluar antes del segundo intento.',
    'Perseguir un Support tocado hasta dejar de coincidir con la pelea. Pausa en cada esquina y mira si tus compañeros aún podían añadir daño o si solo te quedabas dentro de otro duelo aislado.',
    'Dar por ganado el flanco porque se giraron varios enemigos. Comprueba qué consiguió el resto del equipo durante ese tiempo. Si no podía actuar, cambia la ruta o espera en una cobertura más cercana.',
    'Valorar Pulse Bomb solo por el impacto. Sigue al portador y su ayuda hasta después de la explosión; distingue un lanzamiento fallado de una defensa que debías haber forzado antes.',
  ],
  counters: [
    { title: 'Brigitte', body: 'Puede ayudar al Support que estás presionando y apartarte con Whip Shot. Reconoce dónde está antes de insistir sobre su compañero. Un ángulo que permita concentrar daño con vuestro Tank puede ser mejor que entrar entre ambos. Si te expulsa, recupera la cobertura y no gastes toda la movilidad en volver por la misma puerta.' },
    { title: 'Torbjörn', body: 'Su torreta puede detectar la llegada y hacerte gastar recursos antes del duelo. Mira si un compañero tiene tiro para limpiarla o si otra entrada permite presionarla desde cobertura. No recorras el mismo flanco una y otra vez esperando que el dispositivo te ignore; quitarlo o cambiar la ruta también forma parte de preparar el engage.' },
    { title: 'Cassidy', body: 'Flashbang limita tu movilidad y sus tiros pueden obligarte a salir pronto. No te quedes delante repitiendo el mismo strafe solo porque Recall está disponible. Puedes presionar otra línea o aprovechar un momento en que ya atiende al frente. Si recibes daño y necesitas salir, no esperes una granada acertada para aceptar que el duelo se ha vuelto peligroso.' },
    { title: 'Kiriko', body: 'Puede responder con kunáis, proteger con Suzu y usar Swift Step para irse hacia un aliado. Mira a quién puede teleportarse antes de perseguir la llegada. Forzar una salida puede permitir presionar al compañero que deja, pero tampoco garantiza un objetivo libre. Para Pulse Bomb, ten en cuenta que una Suzu a tiempo puede evitar la baja.' },
    { title: 'Moira', body: 'Fade permite abandonar la presión y volver hacia ayuda. Si lo usa, puedes comunicar la dirección y decidir si tu equipo alcanza ese lugar; no hace falta seguirla por todas las habitaciones. Un duelo largo contra su sustain puede dejarte fuera del intercambio que vuestro Tank estaba intentando ganar.' },
    { title: 'D.Va', body: 'Puede volver a proteger la backline, negar tus disparos con Matrix y presionar tu ruta de salida. No te acerques a vaciar el cargador mientras ella atiende esa misma línea. Cambia el ángulo con un compañero o tápate hasta que la amenaza frontal le exija otra respuesta. Vigila también su posición al preparar Pulse Bomb, no solo la del objetivo.' },
  ],
  counterplay: [
    'Contra varias respuestas de peel, acorta el flanco y prepara dos amenazas que coincidan. Si Brigitte y Cassidy te miran desde el principio, quizá vuestro grupo todavía no esté en condiciones de aprovecharlo. Puedes reconocer la entrada sin comprometer la vida.',
    'Si cada ruta empieza con daño de una torreta, comunica dónde está y quién puede limpiarla sin gastar toda la movilidad. Cambiar de puerta o ayudar en esa limpieza puede preparar una entrada mejor que repetir el duelo sin recursos.',
    'Si has probado rutas más cortas, otro objetivo y coordinación con el grupo y seguís sin poder disputar una altura o una línea larga, valora otro DPS que conozcas. El cambio debería cubrir esa necesidad del mapa; no demuestra que Tracer sea mala ni garantiza que el siguiente pick gane solo.',
  ],
  compositions: [
    { title: 'Seguir una entrada de Winston o D.Va', body: 'Colócate antes del salto o los Boosters, sin enseñar el duelo demasiado pronto. Cuando el Tank presione, mira a quién puedes añadir daño o por dónde se retira el rival. No tienes que gastar todos los Blinks para acabar exactamente junto al Tank: un segundo ángulo cercano puede ayudar y conservar tu salida.' },
    { title: 'Un lateral corto junto al poke de Sigma', body: 'Si Sigma y vuestro otro DPS tienen tiro sobre la misma esquina, puedes amenazar una puerta lateral y obligar al defensor a cambiar de posición. Si el poke queda demasiado lejos o se tapa, quizá nadie pueda seguir tu daño. Ajusta la distancia del flanco antes de pedir que todo el núcleo cruce para rescatarte.' },
    { title: 'Dos DPS coordinados sin abandonar el frente', body: 'Con Genji puedes presionar al enemigo que recibe el Dash o preparar su retirada, pero no hace falta que ambos desaparezcáis detrás al mismo tiempo. Mira también a los Supports propios: si están recibiendo dive, una respuesta corta puede permitir que el equipo vuelva a entrar. Coordinar amenazas incluye decidir cuándo parar.' },
  ],
  vodReview: [
    'Revisa una llegada desde tu cámara y la del Tank. Anota cuándo empiezan los tiros y cuándo el rival tiene que atender al frente. Así puedes distinguir llegar temprano de entrar a tiempo con poca munición.',
    'Sigue un Recall completo: cobertura anterior, daño recibido, lugar de activación y punto de regreso. Mira la amenaza desde una cámara enemiga. Sobrevivir fue correcto; la siguiente mejora puede estar en el recorrido previo.',
    'Revisa un viaje al health pack. ¿Estaba disponible, quién podía ver el acceso y cuándo volviste a tener tiro sobre la pelea? Llegar sano después de que termine todo no es el mismo resultado que mantener el lateral durante el engage.',
    'En una persecución sin baja, cambia a la cámara del objetivo. Comprueba a qué ayuda se acercó y qué parte de la pelea dejaste de atender al seguirlo. La oportunidad pudo terminar en la primera esquina.',
    'Con Pulse Bomb, sigue el lanzamiento, la defensa y el seguimiento aliado. Si el objetivo sobrevivió, identifica qué respuesta faltaba gastar; si cayó, comprueba qué hizo el equipo después. No te quedes solo con haber pegado la bomba.',
  ],
  checklist: [
    '¿El equipo puede presionar cuando yo empiece a disparar?',
    '¿Llego con munición y movilidad para corregir el duelo?',
    '¿Qué puerta o cobertura usaré si el objetivo recibe ayuda?',
    '¿Recuerdo por dónde puede devolverme Recall?',
    '¿El pack está disponible y puedo llegar sin quedar atrapado?',
    '¿Qué defensa puede salvar al objetivo de Pulse Bomb?',
  ],
  faqs: [
    { question: '¿Está mal usar Recall nada más entrar?', answer: 'No por definición. Si evita que mueras, usarlo puede ser correcto. Revisa por qué necesitaste salir tan pronto: quizá tu equipo aún no podía ayudar, llegaste sin recursos o apareció una amenaza que no habías visto. La corrección suele estar antes de la activación, no en obligarte a aguantar más daño.' },
    { question: '¿Recall restaura todos los Blinks?', answer: 'No en el kit normal. Comprueba las cargas después de regresar antes de iniciar otro duelo. Blink Packs puede recuperar una carga al recoger un health pack, pero eso es un perk y exige llegar al pack. No importes los efectos de versiones antiguas o modos especiales a una partida de ranked.' },
    { question: '¿Tengo que atacar siempre a los Supports?', answer: 'No. Puedes ayudar sobre un DPS tocado o el objetivo que vuestro Tank ya alcanza. Elige según acceso, defensas y seguimiento. Cruzar toda la backline para buscar un Support acompañado puede ser peor que mantener un segundo ángulo sobre una pelea que tus compañeros ya están ganando.' },
    { question: '¿Forzar que se giren ya gana la pelea?', answer: 'Solo si permite a tu equipo hacer algo útil: ocupar una posición, añadir daño o sostener el objetivo. Mira quién podía actuar durante ese giro. Si aún estaba reapareciendo o no tenía línea, quizá solo gastaste recursos. Acorta el flanco o espera en cobertura hasta que las dos presiones puedan coincidir.' },
    { question: '¿Pulse Bomb tiene que conseguir una baja?', answer: 'No siempre, pero tampoco cuenta como buen uso solo por forzar una defensa. Comprueba si el equipo aprovechó esa respuesta, ganó una posición o pudo continuar el daño. Antes de lanzarla, elige el objetivo y mira qué puede salvarlo. Un impacto sin seguimiento puede dejar la pelea igual que estaba.' },
    { question: '¿Qué perks tiene Tracer actualmente?', answer: 'Las Minor son Temporal Regen, que adelanta la regeneración pasiva, y Kinetic Reload, que recarga munición al conectar melee. Las Major son Blink Packs, que restaura una carga al recoger un health pack, y Quantum Entanglement, que añade exceso de salud y munición temporales con Recall. Eliges una de cada nivel; Auto Recall y los portales aliados pertenecen a Stadium.' },
  ],
  conclusion: 'Elige una entrada de tu próxima VOD y sigue todo el recorrido, no solo el duelo: cuándo saliste de cobertura, con qué recursos empezaste a disparar y dónde terminaste después de Recall. Compara esos momentos con el avance del equipo. Podrás decidir si necesitas una ruta más corta, una recarga antes de asomarte o esperar a la presión frontal, sin convertir cada partida en una persecución de bajas.',
  links: [
    { href: '/guides/como-revisar-cooldowns-overwatch', label: 'Revisar Blink y Recall durante una pelea' },
    { href: '/counters/tracer', label: 'Cómo prepara el rival su respuesta a Tracer' },
    { href: '/team-comps/tracer', label: 'Coordinar el flanco con la presión del equipo' },
    { href: '/maps/esperanca', label: 'Interiores y rotaciones junto al robot en Esperança' },
    { href: '/maps/watchpoint-gibraltar', label: 'Recorridos del suelo y las alturas de Gibraltar' },
    { href: '/heroes/winston', label: 'Preparar el salto al que vas a dar seguimiento' },
    { href: '/heroes/dva', label: 'Reconocer cuándo D.Va entra o vuelve a proteger' },
    { href: '/heroes/genji', label: 'Coordinar el daño con el Dash de Genji' },
    { href: '/heroes/kiriko', label: 'Entender las respuestas de Suzu y Swift Step' },
    { href: '/heroes/cassidy', label: 'Disputar una posición que Cassidy está defendiendo' },
    { href: '/roles/dps', label: 'Elegir una tarea para tu DPS dentro de la pelea' },
    { href: '/guides/como-mejorar-como-dps-overwatch', label: 'Revisar tus decisiones de daño y posición' },
    { href: '/guides/cuando-cambiar-de-heroe-overwatch', label: 'Cambiar de pick para resolver un problema concreto' },
    { href: '/guides/como-mejorar-en-overwatch-revisando-vod', label: 'Comparar tu entrada con las cámaras del equipo' },
    { href: '/experts', label: 'Pedir una revisión de tus rutas y entradas' },
  ],
}
