import { expect, test } from '@playwright/test'

test('composition selector respects hero compatibility and both formats', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/team-comps')
  const picker = page.locator('.counter-picker')
  const panel = page.locator('.team-comp-panel')
  await picker.getByRole('button', { name: 'Reinhardt Tank', exact: true }).click()
  await expect(panel.locator('.team-comp-card')).toHaveCount(1)
  await expect(panel.locator('.team-comp-card h3')).toHaveText('Brawl de objetivo con Reinhardt')
  await expect(panel.locator('.team-comp-line strong')).toHaveCount(5)
  await picker.getByRole('button', { name: '6v6', exact: true }).click()
  await expect(panel.locator('.team-comp-line strong')).toHaveCount(6)
  await picker.getByLabel('Filtrar por estilo').selectOption('dive')
  await expect(panel.locator('.team-comp-card')).toHaveCount(0)
  await expect(panel.getByText('No hay un equipo de ejemplo', { exact: false })).toBeVisible()
  await expect(panel).not.toContainText('Dive recomendado')
  await picker.getByLabel('Filtrar por estilo').selectOption('all')
  await picker.getByRole('button', { name: 'Pharah DPS', exact: true }).click()
  await expect(panel.locator('.team-comp-card h3')).toHaveText('Flyers y presión vertical con Pharah')
  await picker.getByRole('button', { name: '5v5', exact: true }).click()
  await expect(panel.locator('.team-comp-line strong')).toHaveCount(5)
  await picker.getByRole('button', { name: 'Doctrine Support', exact: true }).click()
  await expect(panel.locator('.team-comp-card')).toHaveCount(0)
  const guideLink = panel.getByRole('link', { name: 'guía de héroe', exact: true })
  await expect(guideLink).toHaveAttribute('href', '/heroes/doctrine')
  await guideLink.click()
  await expect(page.locator('h1')).toContainText('Doctrine')
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  expect(errors).toEqual([])
})
