-- One video-first guide per current Overwatch hero.
-- Spanish creator videos are preferred when verified; otherwise a hero-specific English or official video is used.

with hero_video_seed(hero_slug, hero_name, role, guide_slug, video_id, video_title, video_channel, video_language, video_published_at, video_summary) as (
  values
    ('ana', 'Ana', 'support', 'ana-primeros-habitos-impactar-mas', '7DrtWksik9I', 'The Only Ana Guide You Need', 'Awkward', 'en', '2025-06-23'::date, 'Guia reciente de Ana con foco en posicionamiento, presion, cooldowns y decisiones para ganar peleas.'),
    ('anran', 'Anran', 'dps', 'anran-guia-video-overwatch', 'eVYF5am80UQ', 'A Complete Anran Guide', 'Awkward', 'en', '2026-02-06'::date, 'Guia completa y reciente de Anran para entender habilidades, perks, plan de partida y ritmo de engage.'),
    ('ashe', 'Ashe', 'dps', 'ashe-guia-video-overwatch', 'HF-fyYaGKIA', 'ASHE Unranked to Champion (Educational) - Ep. 1', 'qrxu', 'en', '2025-12-28'::date, 'Serie educativa reciente de Ashe para revisar posicionamiento, duelos de hitscan, dinamita y toma de angulos.'),
    ('baptiste', 'Baptiste', 'support', 'baptiste-guia-video-overwatch', '2QTnQGpyUVc', 'Guia basica: Baptiste | Overwatch', 'LeonDrummer', 'es', '2022-10-14'::date, 'Guia en espanol para revisar sustain, dano, botas, campo de inmortalidad y ventanas de matriz.'),
    ('bastion', 'Bastion', 'dps', 'bastion-guia-video-overwatch', 'RccPsvYJiCU', 'How THIS 16 Year Old DOMINATES On Bastion | #1 Bastion Guide', 'Kajor', 'en', '2025-03-31'::date, 'Guia reciente de Bastion para entender presion, timing de transformacion, rutas seguras y castigo al frontal rival.'),
    ('brigitte', 'Brigitte', 'support', 'brigitte-guia-video-overwatch', 'sv-1GxJ_eVY', 'How to ACTUALLY Play Brigitte | A Top500''s COMPLETE Guide', 'JeffyJA', 'en', '2025-07-03'::date, 'Guia completa y reciente de Brigitte centrada en peel, Inspire, packs, brawl y proteccion de backline.'),
    ('cassidy', 'Cassidy', 'dps', 'cassidy-guia-video-overwatch', 'CS-hiY9EysU', 'Educational Unranked To GM CASSIDY (93% Winrate)', 'Awkward', 'en', '2025-10-11'::date, 'Guia educativa reciente de Cassidy para revisar rango medio, precision, castigo a flankers y valor constante.'),
    ('dva', 'D.Va', 'tank', 'dva-guia-video-overwatch', 'h6ITrTAqIUM', 'D.VA for Dummies (Guide & Tips from a GM/4500 Player)', 'yeatle', 'en', '2020-11-03'::date, 'Guia especifica de D.Va con foco en matriz, peel, boosters, ultimate y lectura de engages.'),
    ('domina', 'Domina', 'tank', 'domina-guia-video-overwatch', 'jNbnhZRZx2I', 'Give me 6m 51s and I''ll teach you EVERY DOMINA ABILITY in Overwatch', 'KarQ', 'en', '2026-02-14'::date, 'Desglose reciente de Domina para entender cada habilidad, ventanas defensivas y uso de recursos como tank.'),
    ('doomfist', 'Doomfist', 'tank', 'doomfist-guia-video-overwatch', 'NwKQke_Btcg', 'How These DOOMFIST OTPs BROKE the META... | #1 Doomfist Guide', 'Kajor', 'en', '2025-05-28'::date, 'Guia reciente de Doomfist para estudiar engages, ciclos de cooldowns, objetivos y salida despues de entrar.'),
    ('echo', 'Echo', 'dps', 'echo-guia-video-overwatch', 'W_OiDdCV3c8', 'RANK UP EASY! FULL 2026 ECHO MASTERY GUIDE - Secrets Revealed', 'Samito', 'en', '2026-03-01'::date, 'Guia reciente de Echo para mejorar movilidad, burst, beam, angulos aereos y decisiones de Duplicate.'),
    ('emre', 'Emre', 'dps', 'emre-guia-video-overwatch', 'AtlaU2S8ci8', 'How To Carry on Emre', 'Awkward', 'en', '2026-03-04'::date, 'Guia reciente de Emre para revisar como convertir recursos, off-angles, presion y decisiones de carry.'),
    ('freja', 'Freja', 'dps', 'freja-guia-video-overwatch', 'oYfzFwSGGXU', 'Overwatch - EVERY FREJA ABILITY | Full Breakdown Guide & Tips', 'KarQ', 'en', '2025-03-22'::date, 'Desglose reciente de Freja con habilidades, movilidad, perks, presion con ballesta y uso de ultimate.'),
    ('genji', 'Genji', 'dps', 'genji-guia-video-overwatch', 'PpqRqH0M9sk', 'How To Play Genji So Well it Feels Like CHEATING', 'Awkward', 'en', '2025-06-01'::date, 'Guia reciente de Genji para revisar timing de dive, resets, duelos, blade y presion sobre supports.'),
    ('hanzo', 'Hanzo', 'dps', 'hanzo-guia-video-overwatch', 'Dgry7Q8AtSk', 'Can Hanzo EVER Be Meta? | #1 Hanzo Guide', 'Kajor', 'en', '2025-12-14'::date, 'Guia reciente de Hanzo para entender angulos, sonic arrow, spam util, picks y control de rutas.'),
    ('hazard', 'Hazard', 'tank', 'hazard-guia-video-overwatch', 'BhcQIK8TZlU', 'Spilo''s Comprehensive Hazard Guide', 'Spilo', 'en', '2025-01-20'::date, 'Guia completa y reciente de Hazard para revisar movilidad, muro, mitigacion y toma de espacio.'),
    ('illari', 'Illari', 'support', 'illari-guia-video-overwatch', 'fS1XT6P3XJM', 'Educational Unranked To GM Illari Only (100% Winrate)', 'ChoseN', 'en', '2025-10-11'::date, 'Guia educativa reciente de Illari para entender pylon, angulos de dano, supervivencia y ritmo de carry.'),
    ('jetpack-cat', 'Jetpack Cat', 'support', 'jetpack-cat-guia-video-overwatch', 'DaR2n3jkLSM', 'How To Play Jetpack Cat Better Than 99% Of Players', 'Awkward', 'en', '2026-02-26'::date, 'Guia reciente de Jetpack Cat para mejorar verticalidad, movilidad, utilidad y decisiones de soporte agresivo.'),
    ('junker-queen', 'Junker Queen', 'tank', 'junker-queen-guia-video-overwatch', 'LqADtfRQzok', 'Educational Unranked To GM JUNKER QUEEN (95% Winrate)', 'Awkward', 'en', '2025-11-20'::date, 'Guia educativa reciente de Junker Queen para brawl, shout, sangrados, cuchillo y timing de Rampage.'),
    ('junkrat', 'Junkrat', 'dps', 'junkrat-guia-video-overwatch', '92NKffQofl4', 'How JUNKRAT Could''ve BEATEN The Pros... | Junkrat Guide', 'Kajor', 'en', '2025-10-01'::date, 'Guia reciente de Junkrat para revisar spam inteligente, trampas, rutas cerradas y conversion de picks.'),
    ('juno', 'Juno', 'support', 'juno-guia-video-overwatch', 'IJUYdqTJYS8', 'THIS Is How To Play Juno In Overwatch || 23 Tips to Rank Up on Juno', 'oatmilk_ow', 'en', '2025-07-16'::date, 'Guia reciente de Juno con consejos para movilidad, torpedos, Hyper Ring, posicionamiento y ultimate.'),
    ('kiriko', 'Kiriko', 'support', 'kiriko-guia-video-overwatch', 'hgHc2YZY3WE', 'Kiriko Positioning Guide: How to Position in EVERY Situation', 'bozo', 'en', '2025-02-11'::date, 'Guia reciente de Kiriko centrada en posicionamiento, suzu, TP, presion con kunais y supervivencia.'),
    ('lifeweaver', 'Lifeweaver', 'support', 'lifeweaver-guia-video-overwatch', 'kvp0MqV6Zm8', 'The ULTIMATE Lifeweaver Guide in Overwatch (How To Carry)', 'HolyShiftKid', 'en', '2025-03-05'::date, 'Guia reciente de Lifeweaver para revisar agarre, plataforma, arbol, posicionamiento y como ganar valor.'),
    ('lucio', 'Lucio', 'support', 'lucio-guia-video-overwatch', 'tcABXj7t6IE', 'The ULTIMATE 2025 Lucio Guide.', 'ohwell', 'en', '2025-09-03'::date, 'Guia reciente de Lucio para revisar wallride, speed, peel, boop y ritmo de composiciones rapidas.'),
    ('mauga', 'Mauga', 'tank', 'mauga-guia-video-overwatch', 'EjvWwXcGUXc', 'Mauga Is META AGAIN?!?! Here''s Why... | Mauga Guide', 'Kajor', 'en', '2025-03-05'::date, 'Guia reciente de Mauga para entender engages, sustain, counters, presion constante y Cage Fight.'),
    ('mei', 'Mei', 'dps', 'mei-guia-video-overwatch', 'GAUa8H5aQSQ', 'Mei Unranked to Champion (Full Series)', 'qrxu', 'en', '2026-03-02'::date, 'Serie educativa reciente de Mei para revisar muro, Ice Block, control de espacio y castigo de engages.'),
    ('mercy', 'Mercy', 'support', 'mercy-guia-video-overwatch', 'iRrAATLilao', '5 Mercy tips to improve your gameplay FAST!', 'ILeadHunter', 'en', '2025-08-26'::date, 'Video reciente de Mercy con consejos practicos para mejorar supervivencia, beam priority, movimiento y decisiones.'),
    ('mizuki', 'Mizuki', 'support', 'mizuki-guia-video-overwatch', '-moRm7IfWrk', 'I finally understand how to play Mizuki in Overwatch', 'mL7', 'en', '2026-03-01'::date, 'Guia reciente de Mizuki para entender ritmo de soporte, cooldowns, posicionamiento y ventanas de impacto.'),
    ('moira', 'Moira', 'support', 'moira-guia-video-overwatch', 'v8vc9-ZHD5E', 'Why Moira Is SECRETLY Busted...| #1 Moira Guide', 'Kajor', 'en', '2025-05-07'::date, 'Guia reciente de Moira para revisar recursos, presion, supervivencia, orbes y decisiones de Coalescence.'),
    ('orisa', 'Orisa', 'tank', 'orisa-guia-video-overwatch', 'sdf_-Ep780A', 'Orisa ISN''T Boring...Here''s Why | Orisa Guide', 'Kajor', 'en', '2025-06-25'::date, 'Guia reciente de Orisa para entender control frontal, javelin, fortify, spin y conversion de espacio.'),
    ('pharah', 'Pharah', 'dps', 'pharah-guia-video-overwatch', 'H7rcdxH4_0s', 'How to reach TOP500 Pharah - Complete Guide', 'Isterman', 'en', '2025-08-09'::date, 'Guia reciente de Pharah para revisar combustible, angulos aereos, concussive, rockets y Barrage.'),
    ('ramattra', 'Ramattra', 'tank', 'ramattra-guia-video-overwatch', 'IdYM3nWCWVk', 'The Complete Ramattra Guide 2026', 'redeznt', 'en', '2026-01-14'::date, 'Guia completa y reciente de Ramattra para alternar formas, bloquear, usar vortex y cerrar peleas con ultimate.'),
    ('reaper', 'Reaper', 'dps', 'reaper-guia-video-overwatch', 'FkN1shWryWI', 'Reaper GUIDE to climb the ranks', 'ChoiceOW', 'en', '2025-07-27'::date, 'Guia reciente de Reaper para revisar flancos cortos, presion a tanks, wraith, teleport y Death Blossom.'),
    ('reinhardt', 'Reinhardt', 'tank', 'reinhardt-guia-video-overwatch', 'WV8V7UMqyAg', 'Guia basica: Reinhardt | Overwatch', 'LeonDrummer', 'es', '2022-10-17'::date, 'Guia en espanol para escudo, swings, fire strike, charge y ventanas de Earthshatter.'),
    ('roadhog', 'Roadhog', 'tank', 'roadhog-guia-video-overwatch', 'vA288jtjUJY', 'Guia basica: Roadhog | Overwatch', 'LeonDrummer', 'es', '2022-10-17'::date, 'Guia en espanol para hook, picks, sustain, presion lateral y Whole Hog.'),
    ('sierra', 'Sierra', 'dps', 'sierra-guia-video-overwatch', '9Zf6JgPjTls', 'Sierra | New Hero Gameplay Trailer | Overwatch', 'Overwatch LatAm', 'es', '2026-04-09'::date, 'Gameplay oficial en espanol de Sierra para revisar Helix Rifle, drone Dorothy, tracking, movilidad y ultimate.'),
    ('sigma', 'Sigma', 'tank', 'sigma-guia-video-overwatch', 'Q2SWvV217o0', 'The ULTIMATE Sigma Guide - Everything You Need To Know (Beginner To Advanced) - Overwatch', 'emongg', 'en', '2025-03-21'::date, 'Guia reciente de Sigma para revisar poke, escudo, cooldowns, mapas, matchups y Flux.'),
    ('sojourn', 'Sojourn', 'dps', 'sojourn-guia-video-overwatch', 'tGRzoJi7LnI', 'Guia basica: Sojourn | Overwatch', 'LeonDrummer', 'es', '2022-10-12'::date, 'Guia en espanol para railgun, slide, disruptor, carga de dano y Overclock.'),
    ('soldier-76', 'Soldier: 76', 'dps', 'soldier-76-guia-video-overwatch', 'YbZP-K67QDw', 'How to play Soldier 76 (Best Method) | In-Depth Tutorial (Overwatch)', 'Metro', 'en', '2022-10-29'::date, 'Guia completa de Soldier: 76 para posicionamiento, high ground, Helix, Biotic Field, aim y visor.'),
    ('sombra', 'Sombra', 'dps', 'sombra-guia-video-overwatch', 'yOB_mrkOul8', 'Guia basica: Sombra | Overwatch', 'LeonDrummer', 'es', '2022-10-13'::date, 'Guia en espanol para hack, translocator, timing de engage, picks aislados y EMP.'),
    ('symmetra', 'Symmetra', 'dps', 'symmetra-guia-video-overwatch', 'a-DofsY2tHg', 'SYMMETRA PERKS GUIDE! | Overwatch', 'Levin', 'en', '2025-02-27'::date, 'Guia reciente de perks de Symmetra para entender opciones actuales, teleport, torretas y ritmo de valor.'),
    ('torbjorn', 'Torbjorn', 'dps', 'torbjorn-guia-video-overwatch', 'skWtpVhwlUA', 'Guia basica: Torbjorn | Overwatch', 'LeonDrummer', 'es', '2022-10-12'::date, 'Guia en espanol para torreta, Overload, angulos defensivos, control de flancos y Molten Core.'),
    ('tracer', 'Tracer', 'dps', 'tracer-guia-video-overwatch', 'SRGJ7xZoZZ0', 'Give me 15 minutes, I will teach you how to play Tracer', 'Awkward', 'en', '2025-09-01'::date, 'Guia reciente de Tracer para revisar blink management, off-angles, recall, duelos y Pulse Bomb.'),
    ('vendetta', 'Vendetta', 'dps', 'vendetta-guia-video-overwatch', 'c3guhZL477Q', 'Vendetta | New Hero Gameplay Trailer | Overwatch', 'PlayOverwatch', 'en', '2025-11-20'::date, 'Gameplay oficial de Vendetta para entender movilidad melee, Warding Stance, dash, Soaring Slice y ultimate.'),
    ('venture', 'Venture', 'dps', 'venture-guia-video-overwatch', 'LcrOe4VBvL0', 'How to Play Venture | Overwatch', 'PlayOverwatch', 'en', '2024-04-18'::date, 'Guia oficial de Venture con consejos para burrow, Drill Dash, combos, supervivencia y Tectonic Shock.'),
    ('widowmaker', 'Widowmaker', 'dps', 'widowmaker-guia-video-overwatch', '9ZoF_0ti85U', 'Top 500 Widowmaker Guide 2025 (+ Settings) | Overwatch', 'Luna Webcore', 'en', '2025-07-12'::date, 'Guia reciente de Widowmaker para revisar sightlines, grapple, settings, ritmo de picks y supervivencia.'),
    ('winston', 'Winston', 'tank', 'winston-guia-video-overwatch', 'QduGAeDb1tM', 'A Completely Serious Guide To Winston', 'The WatchOver', 'en', '2025-04-03'::date, 'Guia reciente de Winston para revisar engages, bubble, dives, salidas y errores comunes de posicionamiento.'),
    ('wrecking-ball', 'Wrecking Ball', 'tank', 'wrecking-ball-guia-video-overwatch', 'OpLJfoD_bvU', 'Guia basica: Wrecking Ball | Overwatch', 'LeonDrummer', 'es', '2022-10-12'::date, 'Guia en espanol para setups, grapple, piledriver, adaptacion, escudos y minas.'),
    ('wuyang', 'Wuyang', 'support', 'wuyang-guia-video-overwatch', 'cDBCYwJTGEQ', 'Wuyang''s Complete Guide | Understanding Overwatch', 'Bachiko', 'en', '2026-02-20'::date, 'Guia completa de Wuyang para habilidades, posicionamiento, uso de cobertura, compatibilidades y matchups.'),
    ('zarya', 'Zarya', 'tank', 'zarya-guia-video-overwatch', 'ssWnCfolWa0', 'Guia basica: Zarya | Overwatch', 'LeonDrummer', 'es', '2022-10-14'::date, 'Guia en espanol para burbujas, energia, timing defensivo/ofensivo y Graviton Surge.'),
    ('zenyatta', 'Zenyatta', 'support', 'zenyatta-guia-video-overwatch', 'nq0xjLnZO4k', 'Educational Unranked To GM On ZENYATTA (80% Winrate Overwatch)', 'Awkward', 'en', '2022-12-16'::date, 'Guia educativa de Zenyatta para Discord, angulos, presion, vulnerabilidad y Transcendence.')
)
insert into guides (
  title,
  slug,
  body,
  category,
  published,
  excerpt,
  seo_title,
  seo_description,
  author,
  hero,
  role,
  map,
  tags,
  content_type,
  video_url,
  video_platform,
  video_id,
  video_title,
  video_channel,
  video_language,
  video_published_at,
  video_summary,
  created_at,
  updated_at
)
select
  'Guía de ' || hero_name || ' en Overwatch: cómo jugar, counters y consejos',
  guide_slug,
  '## Qué aprender de ' || hero_name || E'\n\n' ||
  '- Plan de juego: qué pelea busca, desde qué rango aporta más y qué errores castiga.' || E'\n' ||
  '- Prioridades: posicionamiento, cooldowns clave, objetivo principal y cuándo retirarte.' || E'\n' ||
  '- Revisión de VOD: muertes tempranas, recursos gastados sin ventana y peleas donde no convertiste ventaja.' || E'\n\n' ||
  '## Cómo usar esta guía' || E'\n\n' ||
  'Mira primero el vídeo y vuelve a esta página para quedarte con tres ideas accionables. Después, revisa una partida tuya buscando un patrón concreto: una muerte repetida, una mala ventana de cooldown o una pelea donde llegaste tarde.' || E'\n\n' ||
  '> **6V6**' || E'\n' ||
  '> En 6v6 hay más recursos, más peel y más cuerpos ocupando espacio. Con ' || hero_name || ', comprueba si tus ventanas siguen funcionando cuando el rival tiene un segundo tank o más herramientas defensivas.',
  'Video guía',
  true,
  video_summary,
  'Guía de ' || hero_name || ' en Overwatch: consejos, counters y vídeo',
  'Aprende a jugar ' || hero_name || ' en Overwatch con una guía en vídeo, resumen práctico, prioridades, counters y nota para 6v6.',
  coalesce(video_channel, 'Replaid Lab'),
  hero_slug,
  role,
  null,
  array[hero_slug, role, 'video', 'youtube', '6v6', 'overwatch'],
  'guide',
  'https://www.youtube.com/watch?v=' || video_id,
  'youtube',
  video_id,
  video_title,
  video_channel,
  video_language,
  video_published_at,
  video_summary,
  now(),
  now()
from hero_video_seed
on conflict (slug) do update set
  title = excluded.title,
  body = excluded.body,
  category = excluded.category,
  published = excluded.published,
  excerpt = excluded.excerpt,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  author = excluded.author,
  hero = excluded.hero,
  role = excluded.role,
  map = excluded.map,
  tags = excluded.tags,
  content_type = excluded.content_type,
  video_url = excluded.video_url,
  video_platform = excluded.video_platform,
  video_id = excluded.video_id,
  video_title = excluded.video_title,
  video_channel = excluded.video_channel,
  video_language = excluded.video_language,
  video_published_at = excluded.video_published_at,
  video_summary = excluded.video_summary,
  updated_at = now();
