-- One video-first guide per current Overwatch hero.
-- Spanish creator videos are preferred when verified; otherwise a provisional YouTube fallback is used.

with hero_video_seed(hero_slug, hero_name, role, guide_slug, video_id, video_title, video_channel, video_language, video_published_at, video_summary) as (
  values
    ('ana', 'Ana', 'support', 'ana-primeros-habitos-impactar-mas', 'esfNxqdpGuE', 'COMPLETE GUIDE TO ANA OVERWATCH: THE MOST VERSATILE SUPPORT | Ivajpro', 'Ivajpro', 'es', '2022-10-28'::date, 'Guía dedicada de Ana por Ivajpro. Úsala para entender posicionamiento, cooldowns, ventanas de granada, sleep y Nano.'),
    ('anran', 'Anran', 'dps', 'anran-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Anran. Sirve como referencia general de lectura de héroes y prioridades, pero debe sustituirse por una guía específica.'),
    ('ashe', 'Ashe', 'dps', 'ashe-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Ashe para entender su valor relativo, rango y rol dentro de composiciones de poke.'),
    ('baptiste', 'Baptiste', 'support', 'baptiste-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Baptiste para entender cuándo aporta sustain, daño y utilidad defensiva.'),
    ('bastion', 'Bastion', 'dps', 'bastion-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Bastion para entender cuándo su presión directa abre espacio y cuándo se vuelve castigable.'),
    ('brigitte', 'Brigitte', 'support', 'brigitte-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Brigitte para revisar peel, protección de backline y valor contra dive.'),
    ('cassidy', 'Cassidy', 'dps', 'cassidy-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Cassidy para entender control de rango medio, castigo a flankers y toma de duelos.'),
    ('dva', 'D.Va', 'tank', 'dva-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de D.Va para revisar peel, matriz, presión sobre ángulos y tempo de entrada.'),
    ('domina', 'Domina', 'tank', 'domina-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Domina. Sirve como referencia general de tanques y prioridades, pero debe sustituirse por una guía específica.'),
    ('doomfist', 'Doomfist', 'tank', 'doomfist-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Doomfist para entender ventanas de entrada, engages cortos y castigo de backline.'),
    ('echo', 'Echo', 'dps', 'echo-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Echo para revisar ángulos aéreos, burst, beam y valor de Duplicate.'),
    ('emre', 'Emre', 'dps', 'emre-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Emre. Sirve como referencia general de DPS y prioridades, pero debe sustituirse por una guía específica.'),
    ('freja', 'Freja', 'dps', 'freja-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Freja. Sirve como referencia general de DPS y prioridades, pero debe sustituirse por una guía específica.'),
    ('genji', 'Genji', 'dps', 'genji-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Genji para entender timing de dive, resets, Blade y presión sobre supports.'),
    ('hanzo', 'Hanzo', 'dps', 'hanzo-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Hanzo para revisar spam útil, control de ángulos y castigo de rotaciones.'),
    ('hazard', 'Hazard', 'tank', 'hazard-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Hazard. Sirve como referencia general de tanques y prioridades, pero debe sustituirse por una guía específica.'),
    ('illari', 'Illari', 'support', 'illari-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo para ubicar a Illari dentro del rol de support: pylon, ángulos, daño útil y ultimate.'),
    ('jetpack-cat', 'Jetpack Cat', 'support', 'jetpack-cat-guia-video-overwatch', 'xTvTCowH6zs', 'How To Actually Play Jetpack Cat in Overwatch | Quick Guide', 'Rakattack', 'en', '2026-03-10'::date, 'Guía rápida dedicada de Jetpack Cat. Úsala para entender movilidad, valor de utilidad y cómo jugar alrededor de su verticalidad.'),
    ('junker-queen', 'Junker Queen', 'tank', 'junker-queen-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Junker Queen para revisar brawl, shout, sangrados y tempo de engage.'),
    ('junkrat', 'Junkrat', 'dps', 'junkrat-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Junkrat para entender spam, trampas, control de zonas y castigo de rutas cerradas.'),
    ('juno', 'Juno', 'support', 'juno-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Juno. Sirve como referencia general de supports y prioridades, pero debe sustituirse por una guía específica.'),
    ('kiriko', 'Kiriko', 'support', 'kiriko-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Kiriko para revisar suzu, flanqueos, kunais y timing de Kitsune.'),
    ('lifeweaver', 'Lifeweaver', 'support', 'lifeweaver-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Lifeweaver. Sirve como referencia general de supports y prioridades.'),
    ('lucio', 'Lúcio', 'support', 'lucio-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Lúcio para entender speed, peel, boops y ritmo de rush.'),
    ('mauga', 'Mauga', 'tank', 'mauga-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Mauga. Sirve como referencia general de tanques y prioridades.'),
    ('mei', 'Mei', 'dps', 'mei-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Mei para revisar muro, control de espacio y castigo de engages.'),
    ('mercy', 'Mercy', 'support', 'mercy-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Mercy para entender pocket, resurrección, supervivencia y prioridades.'),
    ('mizuki', 'Mizuki', 'support', 'mizuki-guia-video-overwatch', 'Bfa4BTNonok', 'OVERWATCH | BASIC GUIDE TO MIZUKI - ABILITIES, PASSIVES, PERKS & ULTIMATE', 'I CMG I', 'en', '2026-02-15'::date, 'Guía básica dedicada de Mizuki centrada en habilidades, pasivas, perks y ultimate.'),
    ('moira', 'Moira', 'support', 'moira-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Moira para revisar recursos, supervivencia y cuándo hacer daño útil.'),
    ('orisa', 'Orisa', 'tank', 'orisa-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Orisa para entender fortify, javelin, control de frente y tempo defensivo.'),
    ('pharah', 'Pharah', 'dps', 'pharah-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Pharah para revisar ángulos aéreos, presión y ventanas de Barrage.'),
    ('ramattra', 'Ramattra', 'tank', 'ramattra-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Ramattra. Sirve como referencia general de tanques y prioridades.'),
    ('reaper', 'Reaper', 'dps', 'reaper-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Reaper para entender flancos cortos, presión a tanks y Death Blossom.'),
    ('reinhardt', 'Reinhardt', 'tank', 'reinhardt-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Reinhardt para revisar shield, swing timing, pin y Earthshatter.'),
    ('roadhog', 'Roadhog', 'tank', 'roadhog-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Roadhog para entender hook, picks, supervivencia y presión lateral.'),
    ('sierra', 'Sierra', 'dps', 'sierra-guia-video-overwatch', 'HKAuji3Zg38', 'Overwatch - Official Sierra Gameplay Trailer', 'GameTrailers', 'en', '2026-04-09'::date, 'Gameplay trailer oficial de Sierra. Úsalo como referencia inicial de habilidades, movilidad con drone, tracking y ultimate hasta encontrar una guía dedicada.'),
    ('sigma', 'Sigma', 'tank', 'sigma-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Sigma para revisar poke, escudo, grasp y control de sightlines.'),
    ('sojourn', 'Sojourn', 'dps', 'sojourn-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Sojourn para entender presión constante, railgun y timing de Overclock.'),
    ('soldier-76', 'Soldier: 76', 'dps', 'soldier-76-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Soldier: 76 para revisar off-angles, constancia, biotic field y visor.'),
    ('sombra', 'Sombra', 'dps', 'sombra-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Sombra para entender hack, timing de engage y presión sobre objetivos aislados.'),
    ('symmetra', 'Symmetra', 'dps', 'symmetra-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Symmetra para revisar teleport, turrets, control de choke y ramp-up.'),
    ('torbjorn', 'Torbjörn', 'dps', 'torbjorn-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Torbjörn para entender turret, overdrive y control de flancos.'),
    ('tracer', 'Tracer', 'dps', 'tracer-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Tracer para revisar atención, blink management, recall y Pulse Bomb.'),
    ('vendetta', 'Vendetta', 'dps', 'vendetta-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Vendetta. Sirve como referencia general de flankers y prioridades.'),
    ('venture', 'Venture', 'dps', 'venture-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Venture. Sirve como referencia general de DPS agresivos y prioridades.'),
    ('widowmaker', 'Widowmaker', 'dps', 'widowmaker-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Widowmaker para revisar sightlines, presión antes del disparo e Infra-Sight.'),
    ('winston', 'Winston', 'tank', 'winston-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Winston para entender jump timing, bubble, dive y salidas.'),
    ('wrecking-ball', 'Wrecking Ball', 'tank', 'wrecking-ball-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Wrecking Ball para revisar setups, slam, adaptación y minas.'),
    ('wuyang', 'Wuyang', 'support', 'wuyang-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Vídeo provisional mientras curamos una guía dedicada de Wuyang. Sirve como referencia general de supports y prioridades.'),
    ('zarya', 'Zarya', 'tank', 'zarya-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Zarya para revisar burbujas, energía, timing y Graviton.'),
    ('zenyatta', 'Zenyatta', 'support', 'zenyatta-guia-video-overwatch', '5HvfRXUXoZs', 'OVERWATCH 2 TIER LIST', 'BRO YOU WACK', 'en', '2022-10-22'::date, 'Referencia en vídeo con capítulo de Zenyatta para entender Discord, presión, vulnerabilidad y Transcendence.')
)
insert into guides (
  title,
  slug,
  body,
  category,
  published,
  excerpt,
  seo_title,
  seo_description,
  author,
  hero,
  role,
  map,
  tags,
  content_type,
  video_url,
  video_platform,
  video_id,
  video_title,
  video_channel,
  video_language,
  video_published_at,
  video_summary,
  created_at,
  updated_at
)
select
  hero_name || ': guía en vídeo para empezar mejor',
  guide_slug,
  '## Qué ver antes de jugar ' || hero_name || E'\n\n' ||
  '- Identidad del héroe: qué tipo de pelea quiere jugar y qué errores castiga.' || E'\n' ||
  '- Prioridades básicas: posicionamiento, cooldowns, objetivo principal y cuándo retirarte.' || E'\n' ||
  '- Señales para revisar tus partidas: muertes tempranas, recursos gastados sin ventana y peleas donde no convertiste ventaja.' || E'\n\n' ||
  '## Cómo usar esta guía' || E'\n\n' ||
  'Mira primero el vídeo y después vuelve a esta página para quedarte con tres ideas accionables. Si el vídeo está marcado como provisional, úsalo como punto de partida mientras curamos una guía dedicada mejor en español o inglés.' || E'\n\n' ||
  '> **6V6**' || E'\n' ||
  '> En 6v6 hay más recursos, más peel y más cuerpos ocupando espacio. Para ' || hero_name || ', revisa especialmente si tus ventanas siguen funcionando cuando el rival tiene un segundo tank o más herramientas defensivas.',
  'Video guía',
  true,
  video_summary,
  'Guía en vídeo de ' || hero_name || ' en Overwatch',
  'Guía en vídeo de ' || hero_name || ' en Overwatch con resumen rápido, puntos clave y nota para 6v6.',
  coalesce(video_channel, 'Replaid Lab'),
  hero_slug,
  role,
  null,
  array[hero_slug, role, 'video', 'youtube', '6v6'],
  'guide',
  'https://www.youtube.com/watch?v=' || video_id,
  'youtube',
  video_id,
  video_title,
  video_channel,
  video_language,
  video_published_at,
  video_summary,
  now(),
  now()
from hero_video_seed
on conflict (slug) do update set
  title = excluded.title,
  body = excluded.body,
  category = excluded.category,
  published = excluded.published,
  excerpt = excluded.excerpt,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  author = excluded.author,
  hero = excluded.hero,
  role = excluded.role,
  map = excluded.map,
  tags = excluded.tags,
  content_type = excluded.content_type,
  video_url = excluded.video_url,
  video_platform = excluded.video_platform,
  video_id = excluded.video_id,
  video_title = excluded.video_title,
  video_channel = excluded.video_channel,
  video_language = excluded.video_language,
  video_published_at = excluded.video_published_at,
  video_summary = excluded.video_summary,
  updated_at = now();
